DungeonGuide_Guides["dung-floodgate-tww-s3"] = {
  unitMapIDs = { 2214, 2387, 2388 },
  challengeMapID = {525},
  name = "Operation: Floodgate",
  id = "dung-floodgate-tww-s3",
  season = "TWW-S3",
  guideType = "M+",
  
  ["Operation: Floodgate"] = {
    id = "enc-floodgate-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "33-minute timer with open layout - first two bosses can be done in any order.", type = "Mechanic", id = "gui-QxQcPCBm1m4" }, -- S3 timer,
      { order = 2, role = "ALL", text = "Destroy all 5 Weapon Stockpiles to unlock n[Swampface] - some are off-path.", type = "Mechanic", id = "gui-FRC8JriiY" },
      { order = 3, role = "ALL", text = "After n[Demolition Duo], use the rocket to shoot down the zeppelin over the river.", type = "Mechanic", id = "gui-cwPcbC3y51U" },
      { order = 4, role = "ALL", text = "Use gliders by the dam stockpile for shortcuts - let the tank jump first.", type = "Mechanic", id = "gui-EEwVk5gaKL4" },
      { order = 5, role = "ALL", text = "Interrupt priority: s[Surveying Beam], s[Trick Shot], s[Harpoon].", type = "Interrupt", id = "gui-HEjvgko9dJ8" },
      { order = 6, role = "ALL", text = "Dispel priority: s[Overcharge] fast (stuns if left). Other bleeds/DoTs are mitigated/healed.", type = "Mechanic", id = "gui-SX3s2nONwg" },
      { order = 7, role = "ALL", text = "n[Shreddinator 3000] s[Shreddation]: move instantly or stand on boxes/braziers (Z-axis avoids blades).", type = "Mechanic", id = "gui-5ajsNsmnSBs" },
      { order = 8, role = "ALL", text = "n[Darkfuse Jumpstarter]: focus to stop s[Battery Discharge] AoE; bait circles tight then rotate.", type = "Mechanic", id = "gui-JkSo19S0HV4" },
      { order = 9, role = "ALL", text = "n[Venture Co. Architect]: break Scaffolding (removes 90% DR); s[Nail Gun] roots/bleeds (Freedom/Lust helps).", type = "Mechanic", id = "gui-rAmAviRqHE" },
      { order = 10, role = "ALL", text = "Bubbles is removed in S3 - RP auto-kill before n[Swampface].", type = "Mechanic", id = "gui-bKXyL3fW2g" },
      { order = 11, role = "TANK", text = "n[Shreddinator 3000] flamethrower frontal rotates - face away and mitigate ticks.", type = "Mechanic", id = "gui-atjZ7dyg" },
      { order = 12, role = "HEALER", text = "Prep CDs for s[Warp Blood] and s[Turbocharge] / heavy overlaps later.", type = "Mechanic", id = "gui-Tzh4YS0EAk" },
      { order = 13, role = "DPS", text = "Prio kills: n[Bloodwarper], n[Surveyor], n[Electrician]. Use CC when kicks are tight.", type = "Mechanic", id = "gui-EmQNoLGRfcU" }
    },
  },

  ["Route"] = {
    id = "enc-floodgate-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1,  role = "ALL", text = "We are starting with n[Shreddinator 3000], n[Darkfuse Soldier], n[Venture Co. Contractor], and n[Venture Co. Surveyor]. Bloodlust here and spread for s[Shreddation].", type = "Call", id = "gui-PsZu5j8k2s" },
      { order = 2,  role = "ALL", text = "Click the first Weapon Stockpile, then drop down and sweep the pool packs. Assign kicks to s[Surveying Beam]; stun n[Loaderbot] s[Wind-Up].", type = "Call", id = "gui-X52huObRoo" },
      { order = 3,  role = "ALL", text = "CC and Kill n[Venture Co. Surveyor] to stop s[Surveying Beam] ticks and puddles.", target = "Venture Co. Surveyor", type = "Target", id = "gui-4UXcoIPi36s" },
      { order = 4,  role = "ALL", text = "Stun and Kill n[Loaderbot] when it fixates - stop s[Wind-Up].", target = "Loaderbot", type = "Target", id = "gui-OqMBsQ6lwc" },
      { order = 5,  role = "ALL", text = "Head LEFT toward n[Demolition Duo]. Pull n[Darkfuse Demolitionist], n[Mechadrone Sniper], and n[Darkfuse Inspector] on the stairs. Kick s[Trickshot]; watch swirls.", type = "Call", id = "gui-IabP1UDZ2uk" },
      { order = 6,  role = "ALL", text = "Priority kill n[Mechadrone Sniper] to reduce s[Trickshot] bounces.", target = "Mechadrone Sniper", type = "Target", id = "gui-jMWUV3v2Oc8" },
      { order = 7,  role = "ALL", text = "Grab the nearby Weapon Stockpile en route. Keep packs small if s[Surveying Beam] overlaps.", type = "Call", id = "gui-hrajOGVXg6s" },
      { order = 8,  role = "ALL", text = "Boss Fight: Demolition Duo", type = "Jump", target = "Demolition Duo", id = "gui-ezzRicFCtLM" },
      { order = 9,  role = "ALL", text = "After I loot the rocket, use it to shoot down the zeppelin over the river. Click the Stockpile behind the bosses.", type = "Call", id = "gui-PxwLUDBRVxg" },
      { order = 10, role = "ALL", text = "Route to n[Big M.O.M.M.A.]: chain n[Loaderbot]s into a n[Darkfuse Bloodwarper] pack if safe. Interrupt s[Blood Bolt]; stop s[Maximum Distortion] on adds.", type = "Call", id = "gui-OI8ihXCOsg" },
      { order = 11, role = "ALL", text = "CC and Kill n[Darkfuse Bloodwarper] - kick s[Blood Bolt] and prep healing for channel overlap.", target = "Darkfuse Bloodwarper", type = "Target", id = "gui-HV2gVuu2lRc" },
      { order = 12, role = "ALL", text = "Double n[Shreddinator 3000] into n[Venture Co. Contractor]s on the platform. Move instantly for s[Shreddation] or use Z-axis (boxes/braziers).", type = "Call", id = "gui-sC3C4qBcASk" },
      { order = 13, role = "ALL", text = "Focus n[Shreddinator 3000] to reduce s[Shreddation] overlap.", target = "Shreddinator 3000", type = "Target", id = "gui-l3qMbHTeTm4" },
      { order = 14, role = "ALL", text = "Short pull up the steps, stabilise kicks, then go in.", type = "Call", id = "gui-YblZePxDZQI" },
      { order = 15, role = "ALL", text = "Boss Fight: Big M.O.M.M.A.", type = "Jump", target = "Big M.O.M.M.A.", id = "gui-fEQkf0ShUVo" },
      { order = 16, role = "ALL", text = "Click the nearby Weapon Stockpile. Use dam gliders for a shortcut to the swamp.", type = "Call", id = "gui-dZR3OSuhWPs" },
      { order = 17, role = "ALL", text = "Clear the shore: mass-CC n[Disturbed Kelp] to stop s[Jettison Kelp]; purge/interrupt s[Restorative Algae].", type = "Call", id = "gui-ndUtW56dKUY" },
      { order = 18, role = "ALL", text = "Kill n[Disturbed Kelp] first to prevent overlapping s[Jettison Kelp] channels.", target = "Disturbed Kelp", type = "Target", id = "gui-XxKTIeaH6P0" },
      { order = 19, role = "ALL", text = "Confirm 5/5 Weapon Stockpiles. If not, backfill the nearest crate before boss.", type = "Call", id = "gui-FW5pYeIzklQ" },
      { order = 20, role = "ALL", text = "Boss Fight: Swampface", type = "Jump", target = "Swampface", id = "gui-j2MjvKhAJbg" },
      { order = 21, role = "ALL", text = "Through the tunnel to finale: pull n[Venture Co. Electrician]s and n[Darkfuse Jumpstarter]s carefully. Kick s[Lightning Bolt]; focus Jumpstarters to end s[Battery Discharge].", type = "Call", id = "gui-inIrK3ABiWM" },
      { order = 22, role = "ALL", text = "Kick and Kill n[Venture Co. Electrician] fast to reduce s[Lightning Bolt]/DoT pressure.", target = "Venture Co. Electrician", type = "Target", id = "gui-sdukLF7qnZA" },
      { order = 23, role = "ALL", text = "Priority Kill n[Darkfuse Jumpstarter] to stop s[Battery Discharge] ground spam.", target = "Darkfuse Jumpstarter", type = "Target", id = "gui-7rtyUGlemQo" },
      { order = 24, role = "ALL", text = "Bait Jumpstarter circles tight in melee, then rotate as a group. Clean up n[Darkfuse Soldier] packs on the bridge if needed for count.", type = "Call", id = "gui-0ngoslU52s" },
      { order = 25, role = "ALL", text = "Stabilise before boss - no extra trash with the pull. Use personals if s[Battery Discharge] overlaps.", type = "Call", id = "gui-j32br4Dhawg" },
      { order = 26, role = "ALL", text = "Boss Fight: Geezle Gigazap", type = "Jump", target = "Geezle Gigazap", id = "gui-ezMuFDvNTM" }
    }
  },
  
  ["Big M.O.M.M.A."] = {
    id = "enc-floodgate-big-momma",
    order = 3,
    header = "Boss: Big M.O.M.M.A.",
    entries = {
      { order = 1, role = "ALL", text = "Burn phase on s[Jumpstart] - boss takes +200% dmg, AoE every 1.5s. Save lust/CDs.", type = "Call", id = "gui-b0fQVYhuJK4" },
      { order = 2, role = "ALL", text = "Interrupt s[Maximum Distortion] - pulsing AoE + pushback.", type = "Interrupt", id = "gui-UMRsvAebtHc" },
      { order = 3, role = "ALL", text = "s[Sonic Boom] targets a player - aim away and dodge explosion to avoid silence.", type = "Call", id = "gui-SMUqJLakWCM" },
      { order = 4, role = "ALL", text = "If s[Jumpstart] begins with adds alive, s[Kill-o-Block Barrier] will shield boss - avoid this at all costs.", type = "Mechanic", id = "gui-djrhtSd980" },
      { order = 5, role = "TANK", text = "Use CD for s[Electrocrush] - nature hit + DoT. Nerfed in S3 but still dangerous.", type = "Mechanic", id = "gui-QvcHh12P4Uo" },
      { order = 6, role = "TANK", text = "Keep boss near edge pre-burn for space. Avoid overlap with puddles.", type = "Position", id = "gui-Gm72lsvugo" },
      { order = 7, role = "TANK", text = "Pick up n[Darkfuse Mechadrone] adds fast - prevent healer stress.", type = "Mechanic", id = "gui-mryJ3dOyeY" },
      { order = 8, role = "TANK", text = "Stack adds for cleave and interrupts. Interrupt s[Maximum Distortion].", type = "Position", id = "gui-lteTl4VxHQY" },
      { order = 9, role = "TANK", text = "Mark adds if kicks are missed. Rotate interrupts to avoid group wipe.", type = "Mechanic", id = "gui-WpuVdztjpI" },
      { order = 10, role = "TANK", text = "Reposition boss early during burn to avoid puddle overlap.", type = "Mechanic", id = "gui-o5OAk87pc70" },
      { order = 11, role = "TANK", text = "s[Electrocrush] DoT stacks with ambient pulses - mitigate or self-heal quickly.", type = "Mechanic", id = "gui-9ysarp3V4" },
      { order = 12, role = "TANK", text = "Keep gap behind boss to bait s[Doom Storm] safely.", type = "Position", id = "gui-Fn0VWBmpSUY" },
      { order = 13, role = "HEALER", text = "CDs for s[Jumpstart] burn phase - heavy AoE every 1.5s.", type = "Call", id = "gui-VrQam3LKhU" },
      { order = 14, role = "HEALER", text = "Spot heal s[Electrocrush] DoT - overlaps with ambient damage.", type = "Mechanic", id = "gui-gGgSzPmXhQ" },
      { order = 15, role = "HEALER", text = "s[Sonic Boom] target may overlap with group - be ready to top off.", type = "Mechanic", id = "gui-XBrm7r4hR7o" },
      { order = 16, role = "DPS", text = "Kill adds quickly to avoid s[Kill-o-Block Barrier] cast.", type = "Mechanic", id = "gui-KxwT4VGlDxo" },
      { order = 17, role = "DPS", text = "Spread for s[Doom Storm] dash - don't overlap hits.", type = "Mechanic", id = "gui-GHXh9mi1Ee4" },
      { order = 18, role = "DPS", text = "Save cooldowns for s[Jumpstart] burn window.", type = "Call", id = "gui-F92JUl2fJ4" }
    },
  },

  ["Demolition Duo"] = {
    id = "enc-floodgate-demolition-duo",
    order = 4,
    header = "Boss: Demolition Duo",
    entries = {
      { order = 1, role = "ALL", text = "Two s[Gel] debuffs per bomb wave - each dispel clears nearby bombs. Stack on bomb before dispel.", type = "Call", id = "gui-Nr39DnSeD4" },
      { order = 2, role = "ALL", text = "n[Bront] charges three times: first two at random, third at tank. Aim charges through bombs to clear them.", type = "Call", id = "gui-Xl7XgQ3SCD0" },
      { order = 3, role = "ALL", text = "Interrupt s[Quick Shot] or s[Trick Shot] from n[Keeza].", type = "Interrupt", id = "gui-YPTaz9MRguA" },
      { order = 4, role = "TANK", text = "Major CD for s[Wallop] - tank buster + 5yd cleave/knockup.", type = "Mechanic", id = "gui-Mz7hZ9W3eE0" },
      { order = 5, role = "TANK", text = "Drag n[Bront] to n[Keeza] for cleave and efficient bomb clears.", type = "Position", id = "gui-Q9twjJ2Hgr0" },
      { order = 6, role = "TANK", text = "Final s[Charge] targets you - position near last bomb to clear it.", type = "Mechanic", id = "gui-PeeLugULB4" },
      { order = 7, role = "TANK", text = "Swap targets as needed - both bosses must die together.", type = "Call", id = "gui-qFj1MxV7Nc" },
      { order = 8, role = "TANK", text = "Save short CD if s[Wallop] overlaps s[BBBFG] or s[Quick Shot].", type = "Mechanic", id = "gui-YitphMQMBQ0" },
      { order = 9, role = "TANK", text = "Face n[Bront] away from group to avoid cleaving them.", type = "Position", id = "gui-ikRcU74Fcms" },
      { order = 10, role = "HEALER", text = "CDs if bombs fail - s[BBBFG] + bomb DoT overlaps will wipe group.", type = "Call", id = "gui-NYatPNUuIjo" },
      { order = 11, role = "HEALER", text = "Dispel s[Gel] when player stacks on bomb to clear it.", type = "Mechanic", id = "gui-KSEqgoL2gjk" },
      { order = 12, role = "HEALER", text = "Top group before s[BBBFG] + s[Quick Shot] overlaps.", type = "Mechanic", id = "gui-ffyjWsheeUE" },
      { order = 13, role = "DPS", text = "Help clear bombs early. Move for s[Gel], then dispel at bomb.", type = "Mechanic", id = "gui-LS74MGG03u4" },
      { order = 14, role = "DPS", text = "Dodge s[BBBFG] lines from n[Keeza].", type = "Mechanic", id = "gui-PU0NpX99M" },
      { order = 15, role = "DPS", text = "Balance boss HPs to prevent enrage.", type = "Mechanic", id = "gui-gqbt095aNw" }
    },
  },
  
  ["Swampface"] = {
    id = "enc-floodgate-swampface",
    order = 5,
    header = "Boss: Swampface",
    entries = {
      { order = 1, role = "ALL", text = "Move LEFT with your partner for s[Mudslide] - dodging also avoids tether snaps.", type = "Call", id = "gui-gGtMyDXgr7E" },
      { order = 2, role = "ALL", text = "s[Awaken the Swamp] - heavy group damage + waves. Pop defensives and dodge.", type = "Call", id = "gui-UmVJy2VSEw8" },
      { order = 3, role = "ALL", text = "Tethered by s[Razor Choke Vines] - stay <14yds from partner or be yanked/stunned.", type = "Mechanic", id = "gui-gueaHx5RDZ0" },
      { order = 4, role = "ALL", text = "Bubbles RP removed in S3 - boss is active immediately after trash.", type = "Mechanic", id = "gui-osjwJS9M4WY" },
      { order = 5, role = "TANK", text = "Use CD for s[Sludge Claws] - big hit + absorb shield. Self-heal to break faster.", type = "Mechanic", id = "gui-hVJDndFV0B8" },
      { order = 6, role = "TANK", text = "Hold boss steady during wave casts - erratic movement breaks tethers.", type = "Position", id = "gui-EWnYdHWY13E" },
      { order = 7, role = "TANK", text = "If tethered, stay near group - avoid dragging partner into danger.", type = "Mechanic", id = "gui-78Hz57phy5o" },
      { order = 8, role = "TANK", text = "Dodge LEFT with group on s[Mudslide] for consistent positioning.", type = "Call", id = "gui-SfDm8KgvbQ" },
      { order = 9, role = "HEALER", text = "Major CDs for s[Awaken the Swamp] - sustained ramp damage.", type = "Call", id = "gui-YcO05dntb4M" },
      { order = 10, role = "HEALER", text = "Heal s[Razor Choke Vines] pairs - DoT ramps for 30s.", type = "Mechanic", id = "gui-WYJuy75fM30" },
      { order = 11, role = "HEALER", text = "Top group after s[Mudslide] before wave damage starts.", type = "Mechanic", id = "gui-kh3mT5PAJcM" },
      { order = 12, role = "DPS", text = "Stay paired for tethers. Move LEFT for s[Mudslide] together.", type = "Mechanic", id = "gui-yZsdz8H9to" },
      { order = 13, role = "DPS", text = "Use personals if s[Awaken the Swamp] overlaps tether or swirls.", type = "Call", id = "gui-JME9OQtGUo" },
      { order = 14, role = "DPS", text = "Spread during tether phase to avoid overlapping swirlies.", type = "Position", id = "gui-eE3HYDW6yhs" }
    },
  },
  
  ["Geezle Gigazap"] = {
    id = "enc-floodgate-geezle-gigazap",
    order = 6,
    header = "Boss: Geezle Gigazap",
    entries = {
      { order = 1, role = "ALL", text = "s[Turbocharge] - heavy AoE every sec + swirlies. Pop defensives and keep moving.", type = "Call", id = "gui-EYYn7P5LaSQ" },
      { order = 2, role = "ALL", text = "Leaping Sparks fixate - drag them through water puddles to remove. One spark per puddle.", type = "Mechanic", id = "gui-AHipHj0ccc" },
      { order = 3, role = "ALL", text = "Avoid cleaving s[Gigazap] DoT onto allies or puddles - it spreads damage.", type = "Mechanic", id = "gui-0UtFPvzmWVI" },
      { order = 4, role = "ALL", text = "Puddles are harmless until used - manage locations to avoid Shock Water overlaps.", type = "Mechanic", id = "gui-u8JJa2Fjkwg" },
      { order = 5, role = "TANK", text = "Major CD for s[Thunder Punch] - phys + nature hit + knockback.", type = "Mechanic", id = "gui-6LpFQlwGM8k" },
      { order = 6, role = "TANK", text = "Face boss toward console to avoid being knocked off platform.", type = "Position", id = "gui-WGbeXEYrRMQ" },
      { order = 7, role = "TANK", text = "Shift boss slightly between casts to rotate safe puddles.", type = "Position", id = "gui-N3zspdjymbk" },
      { order = 8, role = "TANK", text = "Avoid dragging boss or adds through puddles with s[Thunder Punch] DoT active.", type = "Mechanic", id = "gui-TVfJhPOfA88" },
      { order = 9, role = "HEALER", text = "Ramp healing during s[Turbocharge] while dodging swirlies and lines.", type = "Call", id = "gui-vE9RFxG3u8s" },
      { order = 10, role = "HEALER", text = "Top off s[Gigazap] targets before they move to puddles.", type = "Mechanic", id = "gui-x3DQuTIf3k" },
      { order = 11, role = "DPS", text = "Spread with s[Gigazap] DoT - avoid hitting group or puddles.", type = "Mechanic", id = "gui-DOPv4swWzb8" },
      { order = 12, role = "DPS", text = "Drag Leaping Sparks through water (one per puddle) to clear them quickly.", type = "Mechanic", id = "gui-stag4qOkERc" },
      { order = 13, role = "DPS", text = "During s[Turbocharge], keep moving to dodge and maintain uptime.", type = "Mechanic", id = "gui-S9CYUYPhNI" }
    }
  }
}
