DungeonGuide_Guides["dung-floodgate-tww-s3"] = {
  unitMapIDs = {2387, 2388},
  challengeMapID = {525},
  name = "Operation: Floodgate",
  id = "dung-floodgate-tww-s3",
  season = "TWW-S3",
  guideType = "M+",
  
  ["Operation: Floodgate"] = {
    id = "enc-floodgate-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "33-minute timer with open layout - first two bosses can be done in any order.", type = "Mechanic", id = "gui-5tXTa0OW2CE" }, -- S3 timer,
      { order = 2, role = "ALL", text = "Destroy all 5 Weapon Stockpiles to unlock n[Swampface] - some are off-path.", type = "Mechanic", id = "gui-LYcpw4wCkR0" },
      { order = 3, role = "ALL", text = "After n[Demolition Duo], use the rocket to shoot down the zeppelin over the river.", type = "Mechanic", id = "gui-egWs1lnyS5M" },
      { order = 4, role = "ALL", text = "Use gliders by the dam stockpile for shortcuts - let the tank jump first.", type = "Mechanic", id = "gui-J3X4W6XjliQ" },
      { order = 5, role = "ALL", text = "Interrupt priority: s[Surveying Beam], s[Trick Shot], s[Harpoon].", type = "Interrupt", id = "gui-k8SJM7hbUw" },
      { order = 6, role = "ALL", text = "Dispel priority: s[Overcharge] fast (stuns if left). Other bleeds/DoTs are mitigated/healed.", type = "Mechanic", id = "gui-S8tBp5tryRg" },
      { order = 7, role = "ALL", text = "n[Shreddinator 3000] s[Shreddation]: move instantly or stand on boxes/braziers (Z-axis avoids blades).", type = "Mechanic", id = "gui-OXuQR8Gwpw" },
      { order = 8, role = "ALL", text = "n[Darkfuse Jumpstarter]: focus to stop s[Battery Discharge] AoE; bait circles tight then rotate.", type = "Mechanic", id = "gui-Rypq48NOz6U" },
      { order = 9, role = "ALL", text = "n[Venture Co. Architect]: break Scaffolding (removes 90% DR); s[Nail Gun] roots/bleeds (Freedom/Lust helps).", type = "Mechanic", id = "gui-Lt2ORxPOC0" },
      { order = 10, role = "ALL", text = "Bubbles is removed in S3 - RP auto-kill before n[Swampface].", type = "Mechanic", id = "gui-MnZdiMYq6rc" },
      { order = 11, role = "TANK", text = "n[Shreddinator 3000] flamethrower frontal rotates - face away and mitigate ticks.", type = "Mechanic", id = "gui-KdzKKApeD0w" },
      { order = 12, role = "HEALER", text = "Prep CDs for s[Warp Blood] and s[Turbocharge] / heavy overlaps later.", type = "Mechanic", id = "gui-wHabJZpWEOE" },
      { order = 13, role = "DPS", text = "Prio kills: n[Bloodwarper], n[Surveyor], n[Electrician]. Use CC when kicks are tight.", type = "Mechanic", id = "gui-XewYwTar5A" }
    },
  },

  ["Route"] = {
    id = "enc-floodgate-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1,  role = "ALL", text = "We are starting with n[Shreddinator 3000], n[Darkfuse Soldier], n[Venture Co. Contractor], and n[Venture Co. Surveyor]. Bloodlust here and spread for s[Shreddation].", type = "Call", id = "gui-eHHJSVbP2A" },
      { order = 2,  role = "ALL", text = "Click the first Weapon Stockpile, then drop down and sweep the pool packs. Assign kicks to s[Surveying Beam]; stun n[Loaderbot] s[Wind-Up].", type = "Call", id = "gui-WDtmGndDMo0" },
      { order = 3,  role = "ALL", text = "CC and Kill n[Venture Co. Surveyor] to stop s[Surveying Beam] ticks and puddles.", target = "Venture Co. Surveyor", type = "Target", id = "gui-1k5mP1vQeB" },
      { order = 4,  role = "ALL", text = "Stun and Kill n[Loaderbot] when it fixates - stop s[Wind-Up].", target = "Loaderbot", type = "Target", id = "gui-0Qx2nKX8vR" },
      { order = 5,  role = "ALL", text = "Head LEFT toward n[Demolition Duo]. Pull n[Darkfuse Demolitionist], n[Mechadrone Sniper], and n[Darkfuse Inspector] on the stairs. Kick s[Trickshot]; watch swirls.", type = "Call", id = "gui-T3kOr0e3tc4" },
      { order = 6,  role = "ALL", text = "Priority kill n[Mechadrone Sniper] to reduce s[Trickshot] bounces.", target = "Mechadrone Sniper", type = "Target", id = "gui-7cNYyZr2vM" },
      { order = 7,  role = "ALL", text = "Grab the nearby Weapon Stockpile en route. Keep packs small if s[Surveying Beam] overlaps.", type = "Call", id = "gui-pQczUSbuFv4" },
      { order = 8,  role = "ALL", text = "Boss Fight: Demolition Duo", type = "Jump", target = "Demolition Duo", id = "gui-wrJGpG7o6ig" },
      { order = 9,  role = "ALL", text = "After I loot the rocket, use it to shoot down the zeppelin over the river. Click the Stockpile behind the bosses.", type = "Call", id = "gui-Xif0lSbwLo" },
      { order = 10, role = "ALL", text = "Route to n[Big M.O.M.M.A.]: chain n[Loaderbot]s into a n[Darkfuse Bloodwarper] pack if safe. Interrupt s[Blood Bolt]; stop s[Maximum Distortion] on adds.", type = "Call", id = "gui-Gh9Ickg1Uo0" },
      { order = 11, role = "ALL", text = "CC and Kill n[Darkfuse Bloodwarper] - kick s[Blood Bolt] and prep healing for channel overlap.", target = "Darkfuse Bloodwarper", type = "Target", id = "gui-2uRkq7GgJp" },
      { order = 12, role = "ALL", text = "Double n[Shreddinator 3000] into n[Venture Co. Contractor]s on the platform. Move instantly for s[Shreddation] or use Z-axis (boxes/braziers).", type = "Call", id = "gui-cvcIjEEv20I" },
      { order = 13, role = "ALL", text = "Focus n[Shreddinator 3000] to reduce s[Shreddation] overlap.", target = "Shreddinator 3000", type = "Target", id = "gui-Bg4x8wH3sL" },
      { order = 14, role = "ALL", text = "Short pull up the steps, stabilise kicks, then go in.", type = "Call", id = "gui-3ReS73LS2M" },
      { order = 15, role = "ALL", text = "Boss Fight: Big M.O.M.M.A.", type = "Jump", target = "Big M.O.M.M.A.", id = "gui-hwuUp7ff9o" },
      { order = 16, role = "ALL", text = "Click the nearby Weapon Stockpile. Use dam gliders for a shortcut to the swamp.", type = "Call", id = "gui-HsOQ5Bs423o" },
      { order = 17, role = "ALL", text = "Clear the shore: mass-CC n[Disturbed Kelp] to stop s[Jettison Kelp]; purge/interrupt s[Restorative Algae].", type = "Call", id = "gui-lc0PXyaCO0A" },
      { order = 18, role = "ALL", text = "Kill n[Disturbed Kelp] first to prevent overlapping s[Jettison Kelp] channels.", target = "Disturbed Kelp", type = "Target", id = "gui-6dVtqJp9YF" },
      { order = 19, role = "ALL", text = "Confirm 5/5 Weapon Stockpiles. If not, backfill the nearest crate before boss.", type = "Call", id = "gui-78KOzuTuWJM" },
      { order = 20, role = "ALL", text = "Boss Fight: Swampface", type = "Jump", target = "Swampface", id = "gui-CF0DyCb5ejY" },
      { order = 21, role = "ALL", text = "Through the tunnel to finale: pull n[Venture Co. Electrician]s and n[Darkfuse Jumpstarter]s carefully. Kick s[Lightning Bolt]; focus Jumpstarters to end s[Battery Discharge].", type = "Call", id = "gui-7AIuZG4dekc" },
      { order = 22, role = "ALL", text = "Kick and Kill n[Venture Co. Electrician] fast to reduce s[Lightning Bolt]/DoT pressure.", target = "Venture Co. Electrician", type = "Target", id = "gui-0mLr2Q8fXz" },
      { order = 23, role = "ALL", text = "Priority Kill n[Darkfuse Jumpstarter] to stop s[Battery Discharge] ground spam.", target = "Darkfuse Jumpstarter", type = "Target", id = "gui-qW3tN2b6Va" },
      { order = 24, role = "ALL", text = "Bait Jumpstarter circles tight in melee, then rotate as a group. Clean up n[Darkfuse Soldier] packs on the bridge if needed for count.", type = "Call", id = "gui-GKRLgFaaDPc" },
      { order = 25, role = "ALL", text = "Stabilise before boss - no extra trash with the pull. Use personals if s[Battery Discharge] overlaps.", type = "Call", id = "gui-4dFHhAMlA44" },
      { order = 26, role = "ALL", text = "Boss Fight: Geezle Gigazap", type = "Jump", target = "Geezle Gigazap", id = "gui-BDFLNxgTWhk" }
    }
  },
  
  ["Big M.O.M.M.A."] = {
    id = "enc-floodgate-big-momma",
    order = 3,
    header = "Boss: Big M.O.M.M.A.",
    entries = {
      { order = 1, role = "ALL", text = "Burn phase on s[Jumpstart] - boss takes +200% dmg, AoE every 1.5s. Save lust/CDs.", type = "Call", id = "gui-35sUnLH96Ic" },
      { order = 2, role = "ALL", text = "Interrupt s[Maximum Distortion] - pulsing AoE + pushback.", type = "Interrupt", id = "gui-l4TvZcncoc" },
      { order = 3, role = "ALL", text = "s[Sonic Boom] targets a player - aim away and dodge explosion to avoid silence.", type = "Call", id = "gui-5WO2bIjITUw" },
      { order = 4, role = "ALL", text = "If s[Jumpstart] begins with adds alive, s[Kill-o-Block Barrier] will shield boss - avoid this at all costs.", type = "Mechanic", id = "gui-KFzq3fRBws" },
      { order = 5, role = "TANK", text = "Use CD for s[Electrocrush] - nature hit + DoT. Nerfed in S3 but still dangerous.", type = "Mechanic", id = "gui-psmhGm624BI" },
      { order = 6, role = "TANK", text = "Keep boss near edge pre-burn for space. Avoid overlap with puddles.", type = "Position", id = "gui-0EXP6U3V0dg" },
      { order = 7, role = "TANK", text = "Pick up n[Darkfuse Mechadrone] adds fast - prevent healer stress.", type = "Mechanic", id = "gui-JkNIaUxdFe8" },
      { order = 8, role = "TANK", text = "Stack adds for cleave and interrupts. Interrupt s[Maximum Distortion].", type = "Position", id = "gui-xYykxkcS2Q" },
      { order = 9, role = "TANK", text = "Mark adds if kicks are missed. Rotate interrupts to avoid group wipe.", type = "Mechanic", id = "gui-hfJaBtvZJ0s" },
      { order = 10, role = "TANK", text = "Reposition boss early during burn to avoid puddle overlap.", type = "Mechanic", id = "gui-xusT5PbCnKc" },
      { order = 11, role = "TANK", text = "s[Electrocrush] DoT stacks with ambient pulses - mitigate or self-heal quickly.", type = "Mechanic", id = "gui-uzp5HSNWa4" },
      { order = 12, role = "TANK", text = "Keep gap behind boss to bait s[Doom Storm] safely.", type = "Position", id = "gui-ypEk5ulSm1Y" },
      { order = 13, role = "HEALER", text = "CDs for s[Jumpstart] burn phase - heavy AoE every 1.5s.", type = "Call", id = "gui-C6cL09VQFVw" },
      { order = 14, role = "HEALER", text = "Spot heal s[Electrocrush] DoT - overlaps with ambient damage.", type = "Mechanic", id = "gui-8TbnDkOwiSo" },
      { order = 15, role = "HEALER", text = "s[Sonic Boom] target may overlap with group - be ready to top off.", type = "Mechanic", id = "gui-lvnhdFLPKkc" },
      { order = 16, role = "DPS", text = "Kill adds quickly to avoid s[Kill-o-Block Barrier] cast.", type = "Mechanic", id = "gui-76syyvA7Ws" },
      { order = 17, role = "DPS", text = "Spread for s[Doom Storm] dash - don't overlap hits.", type = "Mechanic", id = "gui-5UtjnlybHL8" },
      { order = 18, role = "DPS", text = "Save cooldowns for s[Jumpstart] burn window.", type = "Call", id = "gui-tuM6AWfSNcg" }
    },
  },

  ["Demolition Duo"] = {
    id = "enc-floodgate-demolition-duo",
    order = 4,
    header = "Boss: Demolition Duo",
    entries = {
      { order = 1, role = "ALL", text = "Two s[Gel] debuffs per bomb wave - each dispel clears nearby bombs. Stack on bomb before dispel.", type = "Call", id = "gui-d6qSgEYVb8M" },
      { order = 2, role = "ALL", text = "n[Bront] charges three times: first two at random, third at tank. Aim charges through bombs to clear them.", type = "Call", id = "gui-NCUHCiKADKI" },
      { order = 3, role = "ALL", text = "Interrupt s[Quick Shot] or s[Trick Shot] from n[Keeza].", type = "Interrupt", id = "gui-yF5vcjgKOI" },
      { order = 4, role = "TANK", text = "Major CD for s[Wallop] - tank buster + 5yd cleave/knockup.", type = "Mechanic", id = "gui-SKpwHyQ11Fo" },
      { order = 5, role = "TANK", text = "Drag n[Bront] to n[Keeza] for cleave and efficient bomb clears.", type = "Position", id = "gui-DpFV6GddU" },
      { order = 6, role = "TANK", text = "Final s[Charge] targets you - position near last bomb to clear it.", type = "Mechanic", id = "gui-2AjRvJylIL4" },
      { order = 7, role = "TANK", text = "Swap targets as needed - both bosses must die together.", type = "Call", id = "gui-GrFjB5bSi8" },
      { order = 8, role = "TANK", text = "Save short CD if s[Wallop] overlaps s[BBBFG] or s[Quick Shot].", type = "Mechanic", id = "gui-K763hVhTjlo" },
      { order = 9, role = "TANK", text = "Face n[Bront] away from group to avoid cleaving them.", type = "Position", id = "gui-FaOgrax1mw" },
      { order = 10, role = "HEALER", text = "CDs if bombs fail - s[BBBFG] + bomb DoT overlaps will wipe group.", type = "Call", id = "gui-cVRj7VwJGw" },
      { order = 11, role = "HEALER", text = "Dispel s[Gel] when player stacks on bomb to clear it.", type = "Mechanic", id = "gui-OdIcP7S7YOI" },
      { order = 12, role = "HEALER", text = "Top group before s[BBBFG] + s[Quick Shot] overlaps.", type = "Mechanic", id = "gui-2E4SceWwuEA" },
      { order = 13, role = "DPS", text = "Help clear bombs early. Move for s[Gel], then dispel at bomb.", type = "Mechanic", id = "gui-pbgFYVrYfM" },
      { order = 14, role = "DPS", text = "Dodge s[BBBFG] lines from n[Keeza].", type = "Mechanic", id = "gui-gNzbxGrtBFg" },
      { order = 15, role = "DPS", text = "Balance boss HPs to prevent enrage.", type = "Mechanic", id = "gui-KBeGH43qI" }
    },
  },
  
  ["Swampface"] = {
    id = "enc-floodgate-swampface",
    order = 5,
    header = "Boss: Swampface",
    entries = {
      { order = 1, role = "ALL", text = "Move LEFT with your partner for s[Mudslide] - dodging also avoids tether snaps.", type = "Call", id = "gui-5i48rzCOUs" },
      { order = 2, role = "ALL", text = "s[Awaken the Swamp] - heavy group damage + waves. Pop defensives and dodge.", type = "Call", id = "gui-LovkMvdS6k" },
      { order = 3, role = "ALL", text = "Tethered by s[Razor Choke Vines] - stay <14yds from partner or be yanked/stunned.", type = "Mechanic", id = "gui-FHjfUiat98U" },
      { order = 4, role = "ALL", text = "Bubbles RP removed in S3 - boss is active immediately after trash.", type = "Mechanic", id = "gui-RKCPYt3Ew00" },
      { order = 5, role = "TANK", text = "Use CD for s[Sludge Claws] - big hit + absorb shield. Self-heal to break faster.", type = "Mechanic", id = "gui-KgtA3ZqVSKg" },
      { order = 6, role = "TANK", text = "Hold boss steady during wave casts - erratic movement breaks tethers.", type = "Position", id = "gui-PWW1UlbEBA" },
      { order = 7, role = "TANK", text = "If tethered, stay near group - avoid dragging partner into danger.", type = "Mechanic", id = "gui-GIj4FWn1xiE" },
      { order = 8, role = "TANK", text = "Dodge LEFT with group on s[Mudslide] for consistent positioning.", type = "Call", id = "gui-uw9tm0pJm3s" },
      { order = 9, role = "HEALER", text = "Major CDs for s[Awaken the Swamp] - sustained ramp damage.", type = "Call", id = "gui-kUIxUK32QqI" },
      { order = 10, role = "HEALER", text = "Heal s[Razor Choke Vines] pairs - DoT ramps for 30s.", type = "Mechanic", id = "gui-GmYaLi8FrE" },
      { order = 11, role = "HEALER", text = "Top group after s[Mudslide] before wave damage starts.", type = "Mechanic", id = "gui-puF4FHXcxGI" },
      { order = 12, role = "DPS", text = "Stay paired for tethers. Move LEFT for s[Mudslide] together.", type = "Mechanic", id = "gui-hI1bJTL2Fzc" },
      { order = 13, role = "DPS", text = "Use personals if s[Awaken the Swamp] overlaps tether or swirls.", type = "Call", id = "gui-WiwubIUnNS0" },
      { order = 14, role = "DPS", text = "Spread during tether phase to avoid overlapping swirlies.", type = "Position", id = "gui-JK4DrCzcUbM" }
    },
  },
  
  ["Geezle Gigazap"] = {
    id = "enc-floodgate-geezle-gigazap",
    order = 6,
    header = "Boss: Geezle Gigazap",
    entries = {
      { order = 1, role = "ALL", text = "s[Turbocharge] - heavy AoE every sec + swirlies. Pop defensives and keep moving.", type = "Call", id = "gui-MbpvAO2dQU" },
      { order = 2, role = "ALL", text = "Leaping Sparks fixate - drag them through water puddles to remove. One spark per puddle.", type = "Mechanic", id = "gui-079gsp2Yr1E" },
      { order = 3, role = "ALL", text = "Avoid cleaving s[Gigazap] DoT onto allies or puddles - it spreads damage.", type = "Mechanic", id = "gui-LqmmtqQ5Tco" },
      { order = 4, role = "ALL", text = "Puddles are harmless until used - manage locations to avoid Shock Water overlaps.", type = "Mechanic", id = "gui-ZDsvfvQxB6o" },
      { order = 5, role = "TANK", text = "Major CD for s[Thunder Punch] - phys + nature hit + knockback.", type = "Mechanic", id = "gui-lsh1qceIWHw" },
      { order = 6, role = "TANK", text = "Face boss toward console to avoid being knocked off platform.", type = "Position", id = "gui-t1yiEF4KcXM" },
      { order = 7, role = "TANK", text = "Shift boss slightly between casts to rotate safe puddles.", type = "Position", id = "gui-K11LW9x6Yo" },
      { order = 8, role = "TANK", text = "Avoid dragging boss or adds through puddles with s[Thunder Punch] DoT active.", type = "Mechanic", id = "gui-Vb9XjhUAA" },
      { order = 9, role = "HEALER", text = "Ramp healing during s[Turbocharge] while dodging swirlies and lines.", type = "Call", id = "gui-VJkzKm3rpSY" },
      { order = 10, role = "HEALER", text = "Top off s[Gigazap] targets before they move to puddles.", type = "Mechanic", id = "gui-sHE5TDQSyto" },
      { order = 11, role = "DPS", text = "Spread with s[Gigazap] DoT - avoid hitting group or puddles.", type = "Mechanic", id = "gui-sfHeJF7psfA" },
      { order = 12, role = "DPS", text = "Drag Leaping Sparks through water (one per puddle) to clear them quickly.", type = "Mechanic", id = "gui-vOLUFE2O6k" },
      { order = 13, role = "DPS", text = "During s[Turbocharge], keep moving to dodge and maintain uptime.", type = "Mechanic", id = "gui-ouZdOloeb6o" }
    }
  }
}
