DungeonGuide_Guides["dung-floodgate-tww-s3"] = {
  name = "Operation: Floodgate",
  id = "dung-floodgate-tww-s3",
  season = "TWW-S3",
  guideType = "M+",
  ["Operation: Floodgate"] = {
    id = "enc-floodgate-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "32-minute timer with open layout - first two bosses can be done in any order.", type = "Mechanic", id = "gui-ZmlBJ4A8z1M" },
      { order = 2, role = "ALL", text = "Destroy all 5 Weapon Stockpiles to unlock n[Swampface] - some are off-path.", type = "Mechanic", id = "gui-aT5LnI8Z3Ks" },
      { order = 3, role = "ALL", text = "Use gliders (by stockpile on dam) for shortcuts - let tank go first!", type = "Mechanic", id = "gui-QiouMOW9B9I" },
      { order = 4, role = "ALL", text = "Zeppelin drops swirlies until shot down with rocket after n[Demolition Duo].", type = "Mechanic", id = "gui-7BMbdYcnb0" },
      { order = 5, role = "ALL", text = "Interrupt priority: s[Surveying Beam], s[Blood Bolt], s[Trick Shot], s[Harpoon].", type = "Interrupt", id = "gui-rlBlp8LNSyM" },
      { order = 6, role = "ALL", text = "Magic dispels: s[Overcharge], s[Electro-Gel], s[Blood-Infused Strikes], s[Harpoon Bleed].", type = "Mechanic", id = "gui-zfsz5glz8Lw" },
      { order = 7, role = "ALL", text = "Avoid swirlies, bombs, saws, and CC-immune mob abilities throughout all wings.", type = "Mechanic", id = "gui-u1G0hgnAIY" },
      { order = 8, role = "TANK", text = "Face n[Shreddinator 3000] frontal away - it rotates. Use defensives for ticks.", type = "Mechanic", id = "gui-K2Tfb6unnqk" },
      { order = 9, role = "TANK", text = "n[Darkfuse Soldier] autos apply stacking magic DoT - rotate CDs, get dispelled.", type = "Mechanic", id = "gui-wa4UZ2CtVbQ" },
      { order = 10, role = "TANK", text = "Break scaffolding under n[Architects] to remove their 90% DR.", type = "Mechanic", id = "gui-oSimTaJ3pg4" },
      { order = 11, role = "HEALER", text = "Prepare healing CDs for s[Warp Blood] and s[Backwash] overlaps.", type = "Mechanic", id = "gui-ZTTzhHJ18cE" },
      { order = 12, role = "HEALER", text = "Dispel s[Overcharge] quickly - stun on expiration is lethal in AoE.", type = "Mechanic", id = "gui-2Z23h1mkxhg" },
      { order = 13, role = "DPS", text = "Prioritise n[Bloodwarper], n[Inspector], and n[Electrician]s - high group danger.", type = "Mechanic", id = "gui-mqv4HTGh79o" },
      { order = 14, role = "DPS", text = "Use CC on s[Wind-Up], s[Surveying Beam], s[Jettison Kelp] when kicks are tight.", type = "Mechanic", id = "gui-GWXpnvCxbg" }
    },
  },

  ["Route"] = {
    id = "enc-floodgate-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "We are pulling double n[Darkfuse Soldiers], n[Venture Co. Contractors], n[Surveyors], and n[Shreddinator 3000] to start. Use Bloodlust and cooldowns.", type = "Call", id = "gui-sw5BuNZs60" },
      { order = 2, role = "ALL", text = "After I blow the Weapon Stockpile, jump down and grab all trash around the pool.", type = "Call", id = "gui-nX9I0DLfaY" },
      { order = 3, role = "ALL", text = "Up stairs into n[Darkfuse Demolitionist], n[Mechadrone Sniper], and n[Inspector]. Watch interrupts!", type = "Call", id = "gui-8Rttlzx4jdE" },
      { order = 4, role = "ALL", text = "Heading up LEFT stairs to clear toward n[Big M.O.M.M.A.].", type = "Call", id = "gui-pu6U0c4kLGg" },
      { order = 5, role = "ALL", text = "Boss Fight: Big M.O.M.M.A.", type = "Jump", target = "Big M.O.M.M.A.", id = "gui-yuNd1ccpSqg" },
      { order = 6, role = "ALL", text = "Post-boss: Pull n[Darkfuse Soldiers] and n[Darkfuse Bloodwarper] near stairs. Prioritise interrupts and Bloodwarper focus.", type = "Call", id = "gui-Vz4rLeXR2dg" },
      { order = 7, role = "ALL", text = "Backtrack across floor. Chain in n[Loaderbots] with n[Bloodwarper] pack. Use Bloodlust again if cooldowns are ready.", type = "Call", id = "gui-zWLHaiMdzs0" },
      { order = 8, role = "ALL", text = "Use glider across gap. Pull left pack first, then rotate into right and push up stairs.", type = "Call", id = "gui-KnKShrgdnXM" },
      { order = 9, role = "ALL", text = "We are chaining double n[Shreddinator 3000s] into n[Contractors]. Watch rotating flamethrowers.", type = "Call", id = "gui-4al4Eql1SU8" },
      { order = 10, role = "ALL", text = "Short pull up the steps into boss: n[Contractors] and n[Surveyor].", type = "Call", id = "gui-LGiJenvktNg" },
      { order = 11, role = "ALL", text = "Boss Fight: Demolition Duo", type = "Jump", target = "Demolition Duo", id = "gui-DkpeF9pLJGs" },
      { order = 12, role = "ALL", text = "Interact with rocket to destroy zeppelin. Then AoE all n[Disturbed Kelp] near shore. Use CC to handle s[Jettison Kelp].", type = "Call", id = "gui-zIrwe6rp2g" },
      { order = 13, role = "ALL", text = "Boss Fight: Swampface", type = "Jump", target = "Swampface", id = "gui-36A5coktk4" },
      { order = 14, role = "ALL", text = "Across bridge: pull n[Contractors], n[Electricians], and n[Inspectors] carefully. Kick Electricians and dispel fast.", type = "Call", id = "gui-tVTwgXnzAE" },
      { order = 15, role = "ALL", text = "Chain in n[Jumpstarters] near finale. Stack for bait, rotate around them as ground effects spawn.", type = "Call", id = "gui-6LmiqTt9GqA" },
      { order = 16, role = "ALL", text = "Final trash: n[Darkfuse Soldiers], n[Contractors], n[Jumpstarters]. Burn safely into boss.", type = "Call", id = "gui-kuV5csIn7d8" },
      { order = 17, role = "ALL", text = "Boss Fight: Geezle Gigazap", type = "Jump", target = "Geezle Gigazap", id = "gui-Ho9wLnqT94" }
    },
  },
  
  ["Big M.O.M.M.A."] = {
    id = "enc-floodgate-big-momma",
    order = 3,
    header = "Boss: Big M.O.M.M.A.",
    entries = {
      { order = 1, role = "ALL", text = "Interrupt s[Maximum Distortion] - pulsing AoE + pushback.", type = "Interrupt", id = "gui-fDCzEWyeidM" },
      { order = 2, role = "ALL", text = "s[Jumpstart] begins burn phase - boss takes 200% damage, group-wide AoE every 1.5s.", type = "Call", id = "gui-7krk3Whw8Jo" },
      { order = 3, role = "ALL", text = "s[Sonic Boom] targets a player - aim away and dodge explosion to avoid silence.", type = "Call", id = "gui-yluMpZr6WQ" },
      { order = 4, role = "TANK", text = "Use CD for s[Electrocrush] - nature hit + DoT. Nerfed in S3 but still dangerous.", type = "Mechanic", id = "gui-vBWC6BytCnc" },
      { order = 5, role = "TANK", text = "Keep boss near edge pre-burn for space. Avoid overlap with puddles.", type = "Position", id = "gui-5FEhou71FI" },
      { order = 6, role = "TANK", text = "Pick up n[Mechadrone] adds fast - prevent healer stress.", type = "Mechanic", id = "gui-5Z7Yfpp2hdU" },
      { order = 7, role = "TANK", text = "Stack adds for cleave and interrupts. Interrupt s[Maximum Distortion].", type = "Position", id = "gui-JqPiNKnVWo" },
      { order = 8, role = "TANK", text = "Mark adds if kicks are missed. Rotate interrupts to avoid group wipe.", type = "Mechanic", id = "gui-qIQJ8NFQF4E" },
      { order = 9, role = "TANK", text = "Reposition boss early during burn to avoid puddle overlap.", type = "Mechanic", id = "gui-QIcrXH2PnmQ" },
      { order = 10, role = "TANK", text = "s[Electrocrush] DoT stacks with ambient pulses - mitigate or self-heal quickly.", type = "Mechanic", id = "gui-2CiXxH1egM" },
      { order = 11, role = "TANK", text = "Keep gap behind boss to bait s[Doom Storm] safely.", type = "Position", id = "gui-eIumqLlV0aw" },
      { order = 12, role = "HEALER", text = "CDs for s[Jumpstart] burn phase - heavy AoE every 1.5s.", type = "Call", id = "gui-W8slALV4I" },
      { order = 13, role = "HEALER", text = "Spot heal s[Electrocrush] DoT - overlaps with ambient damage.", type = "Mechanic", id = "gui-R34BbCRmcA" },
      { order = 14, role = "HEALER", text = "s[Sonic Boom] target may overlap with group - be ready to top off.", type = "Mechanic", id = "gui-FRVT3lCkT04" },
      { order = 15, role = "DPS", text = "Kill adds quickly to avoid s[Kill-o-Block Barrier] cast.", type = "Mechanic", id = "gui-5FifUAPwQXM" },
      { order = 16, role = "DPS", text = "Spread for s[Doom Storm] dash - don't overlap hits.", type = "Mechanic", id = "gui-u8x54HHGPR4" },
      { order = 17, role = "DPS", text = "Save cooldowns for s[Jumpstart] burn window.", type = "Call", id = "gui-FTOY1GI3yI" },
      { order = 18, role = "ALL", text = "If s[Jumpstart] begins and adds are alive, boss casts s[Kill-o-Block Barrier] - avoid this at all costs.", type = "Mechanic", id = "gui-3ZlbHwa5Z9E" }
    },
  },

  ["Demolition Duo"] = {
    id = "enc-floodgate-demolition-duo",
    order = 4,
    header = "Boss: Demolition Duo",
    entries = {
      { order = 1, role = "ALL", text = "s[Gel] on me - moving to bomb. Dispel once stacked.", type = "Call", id = "gui-i3YoXu8KDOk" },
      { order = 2, role = "ALL", text = "Charge incoming - line it through bombs to clear them.", type = "Call", id = "gui-SAhuZ1OZkUQ" },
      { order = 3, role = "ALL", text = "Interrupt s[Quick Shot] or s[Trick Shot] from n[Keeza].", type = "Interrupt", id = "gui-lmmfHBOfBL0" },
      { order = 4, role = "TANK", text = "Major for s[Wallop] - tank buster + 5yd cleave/knockup.", type = "Mechanic", id = "gui-yInfJSSjsT8" },
      { order = 5, role = "TANK", text = "Drag n[Bront] to n[Keeza] for cleave + bomb clear.", type = "Position", id = "gui-oVYvsHlxw8" },
      { order = 6, role = "TANK", text = "Final s[Charge] targets you - position near last bomb.", type = "Mechanic", id = "gui-6j0g44R4ZyY" },
      { order = 7, role = "TANK", text = "Swap targets. Both bosses must die together.", type = "Call", id = "gui-MZ42qffRN84" },
      { order = 8, role = "TANK", text = "Save short CD if s[Wallop] overlaps s[BBBFG] or s[Quick Shot].", type = "Mechanic", id = "gui-RCFQhcvcvE" },
      { order = 9, role = "TANK", text = "Use movement to reposition after charges.", type = "Mechanic", id = "gui-3PD4Wg6mKZE" },
      { order = 10, role = "TANK", text = "Face n[Bront] away - avoid cleaving group.", type = "Position", id = "gui-j1mOzHWY4Uc" },
      { order = 11, role = "TANK", text = "Hold final dispel until n[Bront's] charge finishes.", type = "Call", id = "gui-vfDO3NR8ovc" },
      { order = 12, role = "HEALER", text = "CDs if bombs fail - stacks heavy group DoT.", type = "Call", id = "gui-L5mpAXyoPUQ" },
      { order = 13, role = "HEALER", text = "Dispel s[Gel] when player stacks on bomb.", type = "Mechanic", id = "gui-dd9d8RnGhEc" },
      { order = 14, role = "HEALER", text = "Top group before s[BBBFG] + s[Quick Shot] overlaps.", type = "Mechanic", id = "gui-C39Jm7MUe3A" },
      { order = 15, role = "DPS", text = "Help clear bombs early. Move for s[Gel], then dispel.", type = "Mechanic", id = "gui-EG3y2XE9N8" },
      { order = 16, role = "DPS", text = "Dodge s[BBBFG] lines from n[Keeza].", type = "Mechanic", id = "gui-vikcTYs13M" },
      { order = 17, role = "DPS", text = "Balance boss HPs to prevent enrage.", type = "Mechanic", id = "gui-rRn5OeOuChw" },
      { order = 18, role = "ALL", text = "Two s[Gel] debuffs per bomb wave - each clears nearby bombs when dispelled.", type = "Mechanic", id = "gui-4816X3FxlY" },
      { order = 19, role = "ALL", text = "n[Bront] charges three times: first two at random, third at tank. Always dodge late.", type = "Mechanic", id = "gui-1npZPhDLf4A" }
    },
  },
  
  ["Swampface"] = {
    id = "enc-floodgate-swampface",
    order = 5,
    header = "Boss: Swampface",
    entries = {
      { order = 1, role = "ALL", text = "s[Mudslide] cast - dodge LEFT with your partner.", type = "Call", id = "gui-pC8iu3DM590" },
      { order = 2, role = "ALL", text = "s[Awaken the Swamp] - pop defensives + dodge waves. Heaviest group damage.", type = "Call", id = "gui-OoC28VNjO8" },
      { order = 3, role = "ALL", text = "Tethered by s[Razor Choke Vines] - stay <14yds or get yanked and stunned.", type = "Mechanic", id = "gui-RhND3fOSc" },
      { order = 4, role = "TANK", text = "Use CD for s[Sludge Claws] - big hit + absorb. Self-heal to break absorb faster.", type = "Mechanic", id = "gui-M09K4agigI0" },
      { order = 5, role = "TANK", text = "If tethered, stay close to group - avoid dragging players into AoE.", type = "Mechanic", id = "gui-861E8N2nMdo" },
      { order = 6, role = "TANK", text = "Hold boss steady during wave casts - erratic movement snaps tethers.", type = "Position", id = "gui-4kpauJEE" },
      { order = 7, role = "TANK", text = "Always dodge LEFT to sync with group.", type = "Call", id = "gui-ZUwqIDYjqtM" },
      { order = 8, role = "TANK", text = "Anchor mid-fight. Random movement causes tether chaos.", type = "Position", id = "gui-QrGuHwcqRk4" },
      { order = 9, role = "TANK", text = "s[Sludge Claws] hurt more if overlapping with wave pulses. Mitigate.", type = "Call", id = "gui-vCNZbvmujw" },
      { order = 10, role = "TANK", text = "Pre-dodge AoE before s[Mudslide] to avoid tether snaps mid-cast.", type = "Mechanic", id = "gui-qgeXhjqkZyU" },
      { order = 11, role = "HEALER", text = "Major healing CDs for s[Awaken the Swamp] - heavy ramp.", type = "Call", id = "gui-k0Y1dDCGPjA" },
      { order = 12, role = "HEALER", text = "Heal s[Razor Choke Vines] pairs - DoT ramps and lasts 30s.", type = "Mechanic", id = "gui-uxQXRGibqdo" },
      { order = 13, role = "HEALER", text = "Top off group after s[Mudslide] before wave starts.", type = "Mechanic", id = "gui-7APd64v2J4" },
      { order = 14, role = "DPS", text = "Stick with your partner. Move left for s[Mudslide] together.", type = "Mechanic", id = "gui-wOzLNTUM" },
      { order = 15, role = "DPS", text = "Use personals if s[Awaken] overlaps with tether or swirlies.", type = "Call", id = "gui-urtnJlXh24" },
      { order = 16, role = "DPS", text = "Avoid overlapping swirlies - spread out cleanly during tether phase.", type = "Position", id = "gui-RfEeFr0biJ8" },
      { order = 17, role = "ALL", text = "s[Bubbles] RP removed in S3 - fight begins immediately after trash.", type = "Mechanic", id = "gui-9k0q9LBTyBU" }
    },
  },
  
  ["Geezle Gigazap"] = {
    id = "enc-floodgate-geezle-gigazap",
    order = 6,
    header = "Boss: Geezle Gigazap",
    entries = {
      { order = 1, role = "ALL", text = "s[Turbocharge] phase - pop defensives + dodge random line attacks.", type = "Call", id = "gui-vXIxYsSk3Sc" },
      { order = 2, role = "ALL", text = "Leaping Sparks fixate players - drag them through water to neutralise.", type = "Mechanic", id = "gui-cvfLa80RP8s" },
      { order = 3, role = "ALL", text = "Each spark can only be removed with 1 water puddle. Use different ones!", type = "Mechanic", id = "gui-SWdrtTRHUk" },
      { order = 4, role = "ALL", text = "Don't cleave s[Gigazap] DoT onto others or water - it spreads damage.", type = "Mechanic", id = "gui-xb99uA8V83E" },
      { order = 5, role = "TANK", text = "Use major CD for s[Thunder Punch] - phys + nature hit + knockback.", type = "Mechanic", id = "gui-4ioa9sADYQ8" },
      { order = 6, role = "TANK", text = "Face boss toward console to avoid getting knocked off platform.", type = "Position", id = "gui-hQDDG2UwBPc" },
      { order = 7, role = "TANK", text = "Avoid charging through puddles with s[Thunder Punch] DoT active.", type = "Mechanic", id = "gui-LqvNImXfHHI" },
      { order = 8, role = "TANK", text = "Shift boss slightly between casts to rotate safe puddles.", type = "Position", id = "gui-0biFD7wfSE" },
      { order = 9, role = "TANK", text = "Mitigate spark + puddle overlaps - large combo damage.", type = "Mechanic", id = "gui-eebLVq6CNi4" },
      { order = 10, role = "HEALER", text = "s[Turbocharge] hits every second - ramp AoE healing + dodging required.", type = "Call", id = "gui-A5LOB9OOpOg" },
      { order = 11, role = "HEALER", text = "Top off s[Gigazap] targets before puddle movement.", type = "Mechanic", id = "gui-j4LNajr9c" },
      { order = 12, role = "DPS", text = "Spread out with s[Gigazap] DoT - don't hit group or puddles.", type = "Mechanic", id = "gui-gQbLD8OktvQ" },
      { order = 13, role = "DPS", text = "Drag sparks through water (1 per puddle) to clear them.", type = "Mechanic", id = "gui-JTnf2WaqXU" },
      { order = 14, role = "DPS", text = "Dodge swirlies and s[Thunder Punch] lines during Turbocharge.", type = "Mechanic", id = "gui-yBDoKbFTzZA" },
      { order = 15, role = "ALL", text = "Puddles are harmless until activated - use carefully to avoid Shock Water overlap.", type = "Mechanic", id = "gui-YJfIR8PpCyo" }
    }
  }
}