DungeonGuide_Guides["dung-halls-of-atonement-tww-s3"] = {
  name = "Halls of Atonement",
  id = "dung-halls-of-atonement-tww-s3",
  season = "TWW-S3",
  guideType = "M+",

  ["Intro"] = {
    id = "enc-halls-tww-s3-intro",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "Kill 3x Shard of Halkias to unlock first boss. Each casts Thrash - use defensives.", type = "Mechanic", id = "gui-42b6dab19576" },
      { order = 2, role = "HEALER", text = "Dispel Mark of Obliteration before detonation - explosion is skipped if dispelled.", type = "Mechanic", id = "gui-12d2dadc1cde" },
      { order = 3, role = "TANK", text = "Depraved Darkblades stack tank debuff. Use defensives and call for dispel if needed.", type = "Mechanic", id = "gui-436b2d8f63fb" },
      { order = 4, role = "ALL", text = "Interrupt Siphon Life (Collectors) and Wicked Bolt (Obliterators) as priority.", type = "Interrupt", id = "gui-a6d260cd1322" },
      { order = 5, role = "TANK", text = "Stoneborn Slashers: Face away from group for frontal; don't get knocked off by Stonefist.", type = "Position", id = "gui-d8023da80d8e" },
      { order = 6, role = "ALL", text = "Houndmasters must be interrupted - Loyal Beast enrages nearby mobs.", type = "Interrupt", id = "gui-96bdfe7bbb38" },
      { order = 7, role = "ALL", text = "Wait for Slashers to turn to stone to safely skip them.", type = "Mechanic", id = "gui-80602be11bfc" },
      { order = 8, role = "HEALER", text = "Prepare for group-wide damage from Disrupting Screech and overlapping AoE casts.", type = "Call", id = "gui-1e503145d06a" }
    },
  },

  ["Route"] = {
    id = "enc-halls-tww-s3-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "Start with Lust on Shard pull with additional trash. Prepare for heavy AoE from Thrash.", type = "Call", id = "gui-6757ea98c7c2" },
      { order = 2, role = "ALL", text = "Move clockwise killing the other 2 Shards. Use line-of-sight and CC to manage casters.", type = "Call", id = "gui-01ae1e2494f0" },
      { order = 3, role = "ALL", text = "Enter courtyard and fight Halkias. Watch circle boundary - stay inside to avoid fear.", type = "Jump", id = "gui-e9df77d947d8", target = "Halkias" },
      { order = 4, role = "ALL", text = "Head right up stairs toward Reavers and Ankle Biters. Watch out for skittish mobs.", type = "Call", id = "gui-d0bf98e89b94" },
      { order = 5, role = "ALL", text = "Use AoE CC on Ankle Biters. Tank cooldowns for Mortal Strike on Reavers.", type = "Call", id = "gui-914af067ba8d" },
      { order = 6, role = "ALL", text = "Reach cathedral, open doors to start Echelon encounter.", type = "Jump", id = "gui-7d5886d90e56", target = "Echelon" },
      { order = 7, role = "ALL", text = "Kill Reavers, clear right side after Echelon, then head into cathedral.", type = "Call", id = "gui-90afc87b5b40" },
      { order = 8, role = "ALL", text = "High Adjudicator Aleez is next. Spread for Unstable Anima. Dispel if safe.", type = "Jump", id = "gui-cc26bac0101c", target = "High Adjudicator Aleez" },
      { order = 9, role = "ALL", text = "Final trash is Inquisitor Sigar. Cleave souls with boss and soak Display of Power explosion.", type = "Call", id = "gui-af735c65af55" },
      { order = 10, role = "ALL", text = "Final boss: Lord Chamberlain. Intercept beams and manage statue toss mechanics.", type = "Jump", id = "gui-57ab9464e319", target = "Lord Chamberlain" }
    },
  },

  ["Halkias"] = {
    id = "enc-halls-tww-s3-halkias",
    order = 3,
    header = "Boss: Halkias",
    entries = {
      { order = 1, role = "ALL", text = "Stay inside red circle around n[Halkias] or suffer 8s fear. Circle moves with boss.", type = "Call", id = "gui-9deb3fe1260e" },
      { order = 2, role = "ALL", text = "s[Heave Debris] and s[Crumbling Slam] drop puddles and cause group damage. Stack puddles neatly near edges.", type = "Call", id = "gui-2b73d749a8c7" },
      { order = 3, role = "TANK", text = "Use defensives for s[Crumbling Slam]. It deals heavy single-target and party-wide damage.", type = "Mechanic", id = "gui-3ae651b47d72" },
      { order = 4, role = "ALL", text = "At 100 energy, n[Halkias] casts s[Refracted Sinlight] - 4 rotating beams. Dodge and avoid puddles.", type = "Mechanic", id = "gui-ef65c6325a00" },
      { order = 5, role = "TANK", text = "Reposition boss at 90-95 energy to a clear area before s[Refracted Sinlight] to open dodge space.", type = "Position", id = "gui-8ee6004bcc40" },
      { order = 6, role = "HEALER", text = "Ramp healing for combos: s[Crumbling Slam] + s[Heave Debris] + puddle overlaps.", type = "Call", id = "gui-111702925f8c" },
      { order = 7, role = "ALL", text = "s[Heave Debris] targets a random player - bait near previous puddles to conserve space.", type = "Mechanic", id = "gui-4c8f0b1d3e2a" },
      { order = 8, role = "ALL", text = "Beams from s[Refracted Sinlight] may reverse direction. Stay alert and call it out.", type = "Mechanic", id = "gui-5b3c8f0d1e2b" },
      { order = 9, role = "ALL", text = "Avoid baiting puddles in the beam path — communicate movement.", type = "Call", id = "gui-7c8f0b1d3e2a" },
      { order = 10, role = "TANK", text = "Stack s[Crumbling Slam] puddles if safe using personal cooldowns. Avoid cornering yourself.", type = "Mechanic", id = "gui-8f0b1d3e2a4c" },
      { order = 11, role = "TANK", text = "Control boss facing to avoid baiting puddles into group space.", type = "Position", id = "gui-9b1d3e2a4c8f" },
      { order = 12, role = "TANK", text = "Beware knockbacks or movement effects during s[Refracted Sinlight] prep. Stay centred.", type = "Mechanic", id = "gui-a1d3e2a4c8f0" },
      { order = 13, role = "HEALER", text = "Consider external cooldowns for tanks hit by s[Crumbling Slam] + puddle overlap.", type = "Call", id = "gui-b1d3e2a4c8f0" },
      { order = 14, role = "HEALER", text = "Watch for panic movement during s[Refracted Sinlight]. Spot heal players caught off-guard.", type = "Mechanic", id = "gui-c1d3e2a4c8f0" },
      { order = 15, role = "HEALER", text = "Dispel fear debuff if players step outside the red circle by mistake.", type = "Mechanic", id = "gui-d1d3e2a4c8f0" },
      { order = 16, role = "DPS", text = "Maintain uptime by pre-positioning during s[Refracted Sinlight] prep.", type = "Position", id = "gui-e1d3e2a4c8f0" },
      { order = 17, role = "DPS", text = "Help bait s[Heave Debris] puddles into tight clusters — don't randomly spread them.", type = "Call", id = "gui-f1d3e2a4c8f0" },
      { order = 18, role = "DPS", text = "Avoid standing near the edge of the arena — risk of fear from stepping out.", type = "Mechanic", id = "gui-01d3e2a4c8f0" }
    }
  },

  ["Echelon"] = {
    id = "enc-halls-tww-s3-echelon",
    order = 4,
    header = "Boss: Echelon",
    entries = {
      { order = 1, role = "ALL", text = "Bait s[Blood Torrent] puddles to the edge of the room to conserve space.", type = "Call", id = "gui-e6e2df22d2d2" },
      { order = 2, role = "ALL", text = "n[Stone Fiends] turn to stone at low HP. Don't kill until boss is ready to leap.", type = "Mechanic", id = "gui-81c04e7bb5b0" },
      { order = 3, role = "ALL", text = "s[Flesh to Stone] targets a random player. That player must guide leap onto stoned adds.", type = "Mechanic", id = "gui-6f0fb93a9cae" },
      { order = 4, role = "ALL", text = "Be ready for high group damage when s[Stone Shattering Leap] hits.", type = "Call", id = "gui-cd2317e8fe2d" },
      { order = 5, role = "ALL", text = "Avoid standing in s[Blood Torrent] puddles — they last 2.5 minutes.", type = "Mechanic", id = "gui-0576ea9b6f8f" },
      { order = 6, role = "TANK", text = "Gather n[Stone Fiends] under boss at low HP so leap destroys all.", type = "Mechanic", id = "gui-c8e9a3f69f21" },
      { order = 7, role = "TANK", text = "Interrupt s[Villainous Bolt] casts from n[Stone Fiends] or you'll get deleted by overlaps.", type = "Interrupt", id = "gui-b6f8c6453a9f" },
      { order = 8, role = "TANK", text = "Keep n[Echelon] near centre of room to allow flexible leap targets.", type = "Position", id = "gui-1d2b3e9c4422" },
      { order = 9, role = "TANK", text = "Call leap timing to prep DPS AoE burst or healing CDs.", type = "Call", id = "gui-5b99fabb5211" },
      { order = 10, role = "TANK", text = "Be mindful of puddle placement when repositioning boss.", type = "Mechanic", id = "gui-a0a0ebde207a" },
      { order = 11, role = "HEALER", text = "Use CDs when s[Stone Shattering Leap] hits - s[Nature DoT] can be lethal.", type = "Call", id = "gui-8827a115debb" },
      { order = 12, role = "HEALER", text = "Spot heal leap target + those near n[Stone Fiends] - AoE + DoT combo is deadly.", type = "Mechanic", id = "gui-7e23a2dbdf76" },
      { order = 13, role = "HEALER", text = "Be ready to triage during add phase - multiple s[Villainous Bolt] casts may land.", type = "Mechanic", id = "gui-1374d3b7b7f2" },
      { order = 14, role = "HEALER", text = "s[Blood Torrent] placement issues can trap melee - keep them topped if repositioning.", type = "Call", id = "gui-df305b71aeed" },
      { order = 15, role = "HEALER", text = "Group-wide burst damage is highest after leap + puddle overlap. Precast AoE heals.", type = "Call", id = "gui-7555a0a413cb" },
      { order = 16, role = "DPS", text = "Cleave n[Stone Fiends] evenly to bring them all low at once.", type = "Mechanic", id = "gui-6d768c8f2c58" },
      { order = 17, role = "DPS", text = "Hold CDs until all n[Stone Fiends] are stacked and stoned.", type = "Call", id = "gui-3ac2bafce134" },
      { order = 18, role = "DPS", text = "Help interrupt s[Villainous Bolt] if tank is overwhelmed.", type = "Interrupt", id = "gui-e6ff8e3a0f84" },
      { order = 19, role = "DPS", text = "Avoid placing s[Blood Torrent] puddles in boss travel path or leap zones.", type = "Position", id = "gui-5fe82bc82b62" },
      { order = 20, role = "DPS", text = "Reposition near adds during s[Flesh to Stone] to help guide leap placement.", type = "Position", id = "gui-93b5f4c95603" }
    }
  },

  ["High Adjudicator Aleez"] = {
    id = "enc-halls-tww-s3-aleez",
    order = 5,
    header = "Boss: High Adjudicator Aleez",
    entries = {
      { order = 1, role = "ALL", text = "s[Unstable Anima] applies a DoT to 2 players — spread 5 yards to avoid overlap and stagger dispels.", type = "Mechanic", id = "gui-1e58b25558b5" },
      { order = 2, role = "ALL", text = "s[Ghostly Partitioner] fixates a random player. Kite into n[Anima Lanterns] to destroy it.", type = "Mechanic", id = "gui-b4e11ca3afe1" },
      { order = 3, role = "ALL", text = "Watch out for swirls from s[Anima Fountain] — avoid or risk death.", type = "Mechanic", id = "gui-2d42d198caf2" },
      { order = 4, role = "ALL", text = "Each fixate causes s[Pulse from Beyond], which ramps in damage — move quickly.", type = "Call", id = "gui-a6de63b37713" },
      { order = 5, role = "ALL", text = "Save movement or gap closers to help bait the Partitioner toward lanterns.", type = "Call", id = "gui-588e15dc6270" },
      { order = 6, role = "TANK", text = "Interrupt s[Anima Bolt] casts to reduce incoming spike damage. Prioritise over DPS.", type = "Interrupt", id = "gui-4e429074b688" },
      { order = 7, role = "TANK", text = "Keep boss away from lanterns to prevent accidental trigger zones.", type = "Position", id = "gui-e7594210a70f" },
      { order = 8, role = "TANK", text = "Face boss away from the group when repositioning after fixate phases.", type = "Position", id = "gui-d90d8b22a9e9" },
      { order = 9, role = "TANK", text = "Use mitigation during spike overlap: s[Anima Bolt] + s[Pulse from Beyond].", type = "Mechanic", id = "gui-367bfe5f3c33" },
      { order = 10, role = "TANK", text = "Help guide fixate adds if kiting target is struggling to reach a lantern.", type = "Call", id = "gui-aac4ccf7865a" },
      { order = 11, role = "HEALER", text = "Track s[Unstable Anima] — heal both targets and stagger dispels to avoid double hit.", type = "Call", id = "gui-a1a96914a2f5" },
      { order = 12, role = "HEALER", text = "Use cooldowns during s[Pulse from Beyond] ramp — especially if multiple fixates overlap.", type = "Call", id = "gui-7b045f10d781" },
      { order = 13, role = "HEALER", text = "Pre-HoT players if multiple s[Unstable Anima] debuffs are up.", type = "Mechanic", id = "gui-d4c2d115f86c" },
      { order = 14, role = "HEALER", text = "Spot heal players kiting n[Ghostly Partitioner] — especially if lantern is far.", type = "Call", id = "gui-0e3f96e9f4de" },
      { order = 15, role = "HEALER", text = "Dispel only when safe — a poorly timed double dispel can wipe the party.", type = "Mechanic", id = "gui-5c6d8b2f098f" },
      { order = 16, role = "DPS", text = "Pop defensives if fixated by n[Ghostly Partitioner] and healers are pressured.", type = "Mechanic", id = "gui-0a5cc24d171d" },
      { order = 17, role = "DPS", text = "Plan movement ahead — don't kite the fixate in circles. Go for a clear lantern.", type = "Call", id = "gui-5e94cde9a4a7" },
      { order = 18, role = "DPS", text = "Focus on not cleaving lanterns accidentally during AoE.", type = "Mechanic", id = "gui-b870b84ed09b" },
      { order = 19, role = "DPS", text = "Interrupt s[Anima Bolt] if the tank is crowd-controlled or fixated.", type = "Interrupt", id = "gui-19ebf8934b43" },
      { order = 20, role = "DPS", text = "Use mobility cooldowns to help fixate bait quickly — saves healer pressure.", type = "Call", id = "gui-febf31655f95" }
    },
  },

  ["Inquisitor Sigar"] = {
    id = "enc-halls-tww-s3-sigar",
    order = 6,
    header = "Mini-Boss: Inquisitor Sigar",
    entries = {
      { order = 1, role = "ALL", text = "Interrupt s[Wicked Bolt]. If left unchecked, n[Inquisitor Sigar] will heal via s[Dark Communion].", type = "Interrupt", id = "gui-efb62cce7993" },
      { order = 2, role = "ALL", text = "s[Display of Power] grants +30% damage/healing but causes explosions after 15s.", type = "Mechanic", id = "gui-dd330e9bfb47" },
      { order = 3, role = "ALL", text = "Spread before s[Display of Power] expires to avoid overlapping AoE detonations.", type = "Call", id = "gui-1e5bd5755ead" },
      { order = 4, role = "ALL", text = "Avoid standing in s[Disperse Sin] puddles left behind by empowered adds.", type = "Mechanic", id = "gui-a2a2cb1266ff" },
      { order = 5, role = "ALL", text = "Watch out for fixates from n[Manifestations of Envy] — they will chase randomly.", type = "Mechanic", id = "gui-9f01958bcac1" },
      { order = 6, role = "TANK", text = "Tank n[Manifestations of Envy] near n[Sigar] so DPS can cleave efficiently.", type = "Position", id = "gui-b145508e80c5" },
      { order = 7, role = "TANK", text = "Use cooldowns when s[Dark Communion] starts if adds are still alive.", type = "Call", id = "gui-62dbaf72be12" },
      { order = 8, role = "TANK", text = "Avoid moving adds too far — boss will lose healing targets and gain full cast value.", type = "Mechanic", id = "gui-4b9ff6c12c65" },
      { order = 9, role = "TANK", text = "Reposition slightly after each s[Disperse Sin] cast to reduce ground clutter.", type = "Position", id = "gui-c486321e84b2" },
      { order = 10, role = "TANK", text = "Communicate positioning before s[Display of Power] so melee don't overlap explosions.", type = "Call", id = "gui-0ed54274ef15" },
      { order = 11, role = "HEALER", text = "Pre-top group during s[Dark Communion] to buffer s[Manifestation] fixate hits.", type = "Call", id = "gui-1a7fc82e7e52" },
      { order = 12, role = "HEALER", text = "Use AoE healing cooldowns before s[Display of Power] ends if players are low.", type = "Call", id = "gui-108aa598e3c9" },
      { order = 13, role = "HEALER", text = "Watch for s[Wicked Bolt] + fixate overlaps — spike damage can be fatal.", type = "Mechanic", id = "gui-4a25f2ff127b" },
      { order = 14, role = "HEALER", text = "Stay spread but in range during s[Display of Power] — avoid multiple hits.", type = "Position", id = "gui-f71fbc92cf4c" },
      { order = 15, role = "HEALER", text = "Dispel slow or root effects if fixate target is unable to kite safely.", type = "Mechanic", id = "gui-9ea7294acff6" },
      { order = 16, role = "DPS", text = "Burn n[Tormented Souls] before s[Dark Communion] finishes to prevent boss heal.", type = "Call", id = "gui-30e6308a1901" },
      { order = 17, role = "DPS", text = "Cleave n[Manifestations of Envy] quickly — they fixate players and deal splash damage.", type = "Mechanic", id = "gui-e36ea2859053" },
      { order = 18, role = "DPS", text = "Use AoE cooldowns when adds spawn to help push boss and adds together.", type = "Call", id = "gui-6e18400bb733" },
      { order = 19, role = "DPS", text = "Avoid standing in s[Disperse Sin] puddles — they tick for heavy shadow damage.", type = "Mechanic", id = "gui-1910938890fa" },
      { order = 20, role = "DPS", text = "Spread during s[Display of Power] duration and be ready to pop a defensive if low.", type = "Call", id = "gui-3837ee05ce63" }
    },
  },

  ["Lord Chamberlain"] = {
    id = "enc-halls-tww-s3-chamberlain",
    order = 7,
    header = "Boss: Lord Chamberlain",
    entries = {
      { order = 1, role = "ALL", text = "Avoid s[Telekinetic Toss] statue line (red arrow) — it will one-shot and deal heavy group damage.", type = "Mechanic", id = "gui-fd5dc7827d0a" },
      { order = 2, role = "ALL", text = "s[Unleashed Suffering] is a frontal cone — stay behind the boss unless you're the tank.", type = "Mechanic", id = "gui-b80270c345c7" },
      { order = 3, role = "ALL", text = "At 70% and 40%, boss enters s[Chamberlain's Chorus] phase — avoid statue knockbacks and centre pull.", type = "Mechanic", id = "gui-df37b8d5179f" },
      { order = 4, role = "ALL", text = "During s[Ritual of Woe], soak statue beams — 2 players can handle all 4 if positioned well.", type = "Mechanic", id = "gui-d0ab6c93cb90" },
      { order = 5, role = "ALL", text = "s[Erupting Torment] zones spawn from boss and statues — move immediately or risk death.", type = "Mechanic", id = "gui-4178420418d1" },
      { order = 6, role = "ALL", text = "Stand close to n[Lord Chamberlain] between statues during soak to safely intercept beams.", type = "Position", id = "gui-7daf0651e86a" },
      { order = 7, role = "TANK", text = "s[Stigma of Pride] DoT stacks ramp quickly — mitigate final ticks or pair with healing externals.", type = "Mechanic", id = "gui-b9c3ba556f06" },
      { order = 8, role = "TANK", text = "Rotate boss to keep s[Unleashed Suffering] frontal pointed away from group and beam soak path.", type = "Position", id = "gui-6a3b8414d1ef" },
      { order = 9, role = "TANK", text = "Time defensives when statue toss overlaps with high s[Stigma of Pride] stacks.", type = "Call", id = "gui-d812f88d1752" },
      { order = 10, role = "TANK", text = "During s[Chamberlain's Chorus], avoid centre pull and reposition boss quickly after phase ends.", type = "Mechanic", id = "gui-a28c45b97b64" },
      { order = 11, role = "TANK", text = "Maintain threat on boss while beams are being soaked — ranged DPS may pull aggro during movement.", type = "Call", id = "gui-64c56f255ea5" },
      { order = 12, role = "HEALER", text = "Use healing CDs during s[Ritual of Woe] — beam ticks ramp and hit soaking players hard.", type = "Call", id = "gui-3ddb7b962556" },
      { order = 13, role = "HEALER", text = "Keep tank topped during s[Stigma of Pride] — final ticks hit 30% harder.", type = "Mechanic", id = "gui-bf4c3a0b6215" },
      { order = 14, role = "HEALER", text = "Use externals when tank has 3+ s[Stigma] stacks and is dodging statues.", type = "Call", id = "gui-9d19638c1c44" },
      { order = 15, role = "HEALER", text = "Pre-cast AoE heals before s[Erupting Torment] as party often spreads to dodge.", type = "Call", id = "gui-40292b19c9d1" },
      { order = 16, role = "HEALER", text = "Spot-heal beam soakers and be ready to top melee who may get clipped by toss or torment zones.", type = "Mechanic", id = "gui-a295c4a34ef6" },
      { order = 17, role = "DPS", text = "Help soak beams during s[Ritual of Woe] — use defensives if soaking multiple.", type = "Mechanic", id = "gui-d52ddc2d8d11" },
      { order = 18, role = "DPS", text = "Stay mobile and be ready to dodge statue toss + erupt zones in quick succession.", type = "Call", id = "gui-2a2fc173e937" },
      { order = 19, role = "DPS", text = "Pop defensive if soaking beam solo or overlapping with s[Erupting Torment].", type = "Call", id = "gui-c406e0c1375d" },
      { order = 20, role = "DPS", text = "Help interrupt healer casts if group healer is mid-channel during beam soaks.", type = "Mechanic", id = "gui-f6d125ba233b" },
      { order = 21, role = "DPS", text = "Watch arrow markers under statues — move early to avoid panic repositioning.", type = "Call", id = "gui-a1f00ea55d45" }
    },
  }
}