DungeonGuide_Guides["dung-darkflame-tww-s2"] = {
  unitMapIDs = { 2214, 2303 },
  challengeMapID = {504},
  name = "Darkflame Cleft",
  id = "dung-darkflame-tww-s2",
  season = "TWW-S2",
  guideType = "M+",
  
  ["Darkflame Cleft"] = {
    id = "enc-darkflame-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "33-minute timer with linear progression - 4 boss encounters.", type = "Mechanic", id = "gui-4MoFXwO3lLQ" },
      { order = 2, role = "ALL", text = "Candlelight mechanics define multiple boss phases and escort event.", type = "Mechanic", id = "gui-gjeE1OV18" },
      { order = 3, role = "ALL", text = "Stay in Candlelight during escort and final boss - avoid s[Smothering Shadows] debuff.", type = "Mechanic", id = "gui-JFTgcon8EI" },
      { order = 4, role = "ALL", text = "Interrupt priority: s[Drain Light], s[Boiling Flames], s[Honey Volley], s[Paranoid Mind].", type = "Interrupt", id = "gui-Ul2tcQc7E0" },
      { order = 5, role = "ALL", text = "Magic debuffs are frequent - dispel s[Flashpoint], s[Burning Fermentation], s[Bee Venom].", type = "Mechanic", id = "gui-rcLUejwnDR8" },
      { order = 6, role = "ALL", text = "Avoid swirlies and s[Wild Wallop] knockbacks - especially near ledges or extra packs.", type = "Mechanic", id = "gui-yUubWq89yMI" },
      { order = 7, role = "ALL", text = "Watch for candle DoT overlaps - e.g. s[Incite Flames] and s[Enkindling Inferno] combo.", type = "Mechanic", id = "gui-mRbxywXLwEE" },
      { order = 8, role = "TANK", text = "Open with safe pull - n[Rank Overseer] knock mobs wide, causing accidental chain pulls.", type = "Mechanic", id = "gui-j78ahqkUoA" },
      { order = 9, role = "TANK", text = "Position minecart adds (n[Menial Laborers]) on tracks for cleave and minecart kills.", type = "Mechanic", id = "gui-61lFcGgsULs" },
      { order = 10, role = "TANK", text = "n[Corridor Creepers] gain power from corpses - kite if stacks grow too high.", type = "Mechanic", id = "gui-fjtet2SsnS8" },
      { order = 11, role = "TANK", text = "During escort, stick close to cart - pull carefully, only what's needed.", type = "Mechanic", id = "gui-Mdf4410THZY" },
      { order = 12, role = "HEALER", text = "Be ready for burst healing during s[Volatile Keg], s[Eternal Darkness], candle DoT overlaps.", type = "Mechanic", id = "gui-W0PLhPO25A" },
      { order = 13, role = "HEALER", text = "Candle heat drops during s[Eternal Darkness] - DPS or tank should refill wax mid-cast.", type = "Mechanic", id = "gui-MrRftDvzTAg" },
      { order = 14, role = "DPS", text = "Use CC on n[Menial Laborers] during escort - they can be stunned or rooted.", type = "Mechanic", id = "gui-cgSzYXceUrQ" },
      { order = 15, role = "DPS", text = "Kill adds fast during boss phases - especially during s[Eternal Darkness].", type = "Mechanic", id = "gui-UWkf7X3UTxI" },
      { order = 16, role = "DPS", text = "Use CC on n[Corridor Creepers] to prevent them from gaining stacks.", type = "Mechanic", id = "gui-SXLN1BoeV4" }
    },
  },

  ["Route"] = {
    id = "enc-darkflame-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "Pulling full first area. Respect bleed stacks from n[Menial Laborers].", type = "Call", id = "gui-Z1Pl8W0MGQ0" },
      { order = 2, role = "ALL", text = "Focus n[Royal Wicklighter] fast in second pull to avoid bolt overlaps.", type = "Call", id = "gui-nld4Ztd8Gzs" },
      { order = 3, role = "ALL", text = "Chain pull n[Rank Overseer] and new n[Laborers] carefully into each other.", type = "Call", id = "gui-8MVr5zV4CY" },
      { order = 4, role = "ALL", text = "Tag n[Lowly Mole Herder] from range and LOS if possible.", type = "Call", id = "gui-k7Wavn2gBPY" },
      { order = 5, role = "ALL", text = "Aim for ~28-30% count before first boss.", type = "Mechanic", id = "gui-tuVZaIDC3FM" },
      { order = 6, role = "ALL", text = "Boss Fight: Ol' Waxbeard", type = "Jump", target="Ol' Waxbeard" , id = "gui-iiLw2KjAyHU" },
      { order = 7, role = "ALL", text = "After first boss, jump down and pull n[Wandering Candle] + n[Task Workers].", type = "Call", id = "gui-vZKFPD9tI74" },
      { order = 8, role = "ALL", text = "LOS n[Wandering Candle] AOE under Minecart rail pillar.", type = "Position", id = "gui-Y4E4q9WebCc" },
      { order = 9, role = "ALL", text = "Second Candle pull: Combine it with next pack for efficiency.", type = "Call", id = "gui-dlPJZ63unzE" },
      { order = 10, role = "ALL", text = "In boss room: can either slow pull or YOLO all mobs together.", type = "Mechanic", id = "gui-IFjchPHvTUk" },
      { order = 11, role = "ALL", text = "LOS properly to reduce fire stacks from n[Blazing Fiends].", type = "Mechanic", id = "gui-kVFmLIMmTNk" },
      { order = 12, role = "ALL", text = "Boss Fight: Blazikon", type = "Jump", target="Blazikon" , id = "gui-08jxWjD4jU" },
      { order = 13, role = "ALL", text = "After n[Blazikon], pull n[Wandering Candle] in new room first.", type = "Call", id = "gui-ggIJh3gjNQ" },
      { order = 14, role = "ALL", text = "Run far end to stack n[Flame Bolters] via LOS if confident.", type = "Call", id = "gui-BLAqR3ie1cI" },
      { order = 15, role = "ALL", text = "n[Snoot Stout] and n[Torch Snarl] pull next. Tank face headlock safely.", type = "Mechanic", id = "gui-JBz11yiqpZQ" },
      { order = 16, role = "ALL", text = "Boss Fight: The Candle King", type = "Jump", target="The Candle King" , id = "gui-pu4i7mEtNvc" },
      { order = 17, role = "ALL", text = "After n[The Candle King], proceed straight into Minecart event.", type = "Call", id = "gui-o9VyTrg8wVA" },
      { order = 18, role = "ALL", text = "Pull 1-2 packs at a time in Minecart to avoid n[Corridor Creepers] scaling.", type = "Call", id = "gui-VeZsHKbyVo" },
      { order = 19, role = "ALL", text = "Cart goes left-right-left - clear as we move.", type = "Call", id = "gui-FDT45rhQ0ig" },
      { order = 20, role = "ALL", text = "At final boss, expect to still be slightly under count.", type = "Mechanic", id = "gui-VPs5KQToWAw" },
      { order = 21, role = "ALL", text = "Boss Fight: The Darkness", type = "Jump", target="The Darkness" , id = "gui-BGiWpKcmmlQ" },
      { order = 22, role = "ALL", text = "Backpull into earlier cleared mobs if needed to reach 100%.", type = "Call", id = "gui-0RQK4NZKZJ0" }
    },
  },

  ["Ol' Waxbeard"] = {
    id = "enc-darkflame-ol-waxbeard",
    order = 3,
    header = "Boss: Ol' Waxbeard",
    entries = {
      { order = 1, role = "ALL", text = "Interrupt s[Underhanded Track-tics] cart or group wipe.", type = "Interrupt", id = "gui-l0XSGWsoys" },
      { order = 2, role = "TANK", text = "Pick up n[Menial Laborers] quickly. Defensives if high bleed stacks.", type = "Mechanic", id = "gui-29IaZU1OiX8" },
      { order = 3, role = "TANK", text = "If fixated by s[Candleflame], kite adds + use movement/CDs.", type = "Mechanic", id = "gui-hIhti7suzTw" },
      { order = 4, role = "TANK", text = "Defensive on s[Rock Buster] - 25% phys dmg amp.", type = "Mechanic", id = "gui-OccfAdeNNI" },
      { order = 5, role = "TANK", text = "Position boss near track for minecart cleave.", type = "Position", id = "gui-4tFdZect0jE" },
      { order = 6, role = "TANK", text = "s[Reckless Charge] incoming - bait near track to clear adds.", type = "Call", id = "gui-XdFcEwH4Mjw" },
      { order = 7, role = "TANK", text = "Cart up - dragging boss for cleave.", type = "Call", id = "gui-26PpTMkIEpo" },
      { order = 8, role = "TANK", text = "Avoid s[Cave-In]. Position group to dodge post-charge swirls.", type = "Mechanic", id = "gui-raMvRB7J28" },
      { order = 9, role = "TANK", text = "Pull at edge to avoid aggro from patrol n[Menial Laborers].", type = "Mechanic", id = "gui-0g2d80oU9s" },
      { order = 10, role = "HEALER", text = "Top s[Candleflame] target under fixate pressure.", type = "Mechanic", id = "gui-9MXrsj9QI" },
      { order = 11, role = "HEALER", text = "Prep for DoT if s[Underhanded Track-tics] fails.", type = "Call", id = "gui-z6oGiZSXdHw" },
      { order = 12, role = "DPS", text = "Kite fixated adds to track. CC/slow them.", type = "Mechanic", id = "gui-yvG4PjACxio" },
      { order = 13, role = "DPS", text = "Dodge s[Cave-In] swirls after s[Reckless Charge].", type = "Mechanic", id = "gui-sBNDn9jJYw" }
    },
  },

  ["Blazikon"] = {
    id = "enc-darkflame-blazikon",
    order = 4,
    header = "Boss: Blazikon",
    entries = {
      { order = 1, role = "ALL", text = "Light candles during s[Candle Barrage]. Spread swirlies carefully.", type = "Call", id = "gui-jsLtAM2CvDI" },
      { order = 2, role = "ALL", text = "Extinguish 1-2 candles with s[Gust] to create safe zones.", type = "Call", id = "gui-Rq6btWfXA" },
      { order = 3, role = "TANK", text = "Stay in melee - boss cleaves if no target nearby.", type = "Position", id = "gui-UDxurMIgSMU" },
      { order = 4, role = "TANK", text = "Re-enter melee fast after s[Gust] to avoid wipe from s[Blazing Storms].", type = "Mechanic", id = "gui-aQTf4WbnaI" },
      { order = 5, role = "TANK", text = "Coordinate safe zones during Gust phases.", type = "Mechanic", id = "gui-gQsAOkK0JfE" },
      { order = 6, role = "TANK", text = "Reposition after Gust to extinguished candles.", type = "Position", id = "gui-x3T1EK5DLXg" },
      { order = 7, role = "TANK", text = "Use CD for s[Dousing Breath] if high s[Enkindling] stacks.", type = "Mechanic", id = "gui-YEdXpbw7SY" },
      { order = 8, role = "TANK", text = "DPS light candles. I'm staying on boss.", type = "Call", id = "gui-oeOJXNZoiY4" },
      { order = 9, role = "HEALER", text = "Prep CDs for s[Dousing Breath] and fire phases.", type = "Call", id = "gui-SDpJG2wNG5U" },
      { order = 10, role = "HEALER", text = "Top group during s[Incite Flames] puddle phase.", type = "Mechanic", id = "gui-HKDX2g12UmY" },
      { order = 11, role = "DPS", text = "Spread Barrage to light candles fast.", type = "Mechanic", id = "gui-bbwYS0paoIY" },
      { order = 12, role = "DPS", text = "Avoid s[Gust] tornadoes and s[Incite Flames].", type = "Mechanic", id = "gui-oqiLgK7CgHA" }
    },
  },

  ["The Candle King"] = {
    id = "enc-darkflame-the-candle-king",
    order = 5,
    header = "Boss: The Candle King",
    entries = {
      { order = 1, role = "ALL", text = "Interrupt s[Paranoid Mind] or party gets feared.", type = "Interrupt", id = "gui-b05hjWAUE" },
      { order = 2, role = "ALL", text = "Aim s[Pickaxe] at statues.", type = "Call", id = "gui-P3emdwTc8G0" },
      { order = 3, role = "ALL", text = "Use s[Darkflame] (5y circle) to destroy multiple statues.", type = "Call", id = "gui-w8kJTStFdJ0" },
      { order = 4, role = "TANK", text = "Stay clear of statues to avoid stun.", type = "Call", id = "gui-E4RMPNtwZvo" },
      { order = 5, role = "TANK", text = "Rotate boss to new spawn points after s[Darkflame].", type = "Mechanic", id = "gui-js4IEsR7u3Q" },
      { order = 6, role = "TANK", text = "Play relatively close together to cluster the wax statues, we are rotating counter-clockwise.", type = "Call", id = "gui-c0YrN4VlkB8" },
      { order = 7, role = "HEALER", text = "Prep CDs if many statues up before s[Darkflame] phase.", type = "Call", id = "gui-UmLTV9oXemU" },
      { order = 8, role = "HEALER", text = "Top group during s[Eerie Molds].", type = "Mechanic", id = "gui-QVTAoQ4ISTM" },
      { order = 9, role = "DPS", text = "Use s[Darkflame] circle to hit statues.", type = "Mechanic", id = "gui-LziPKSFJ0U" },
      { order = 10, role = "DPS", text = "Follow tank to group statues together.", type = "Mechanic", id = "gui-Li3537Oiho" }
    },
  },
  
  ["The Darkness"] = {
    id = "enc-darkflame-the-darkness",
    order = 6,
    header = "Boss: The Darkness",
    entries = {
      { order = 1, role = "ALL", text = "Interrupt s[Call Darkspawn] fast. I'll AoE adds.", type = "Call", id = "gui-00QonrnpsLI" },
      { order = 2, role = "ALL", text = "If s[Umbral Slash] targets your candle, reposition immediately.", type = "Mechanic", id = "gui-afJO1UCJ4Q" },
      { order = 3, role = "ALL", text = "s[Shadowblast] on me - moving out from candle to explode.", type = "Call", id = "gui-OI8PnpUd8d0" },
      { order = 4, role = "ALL", text = "Grabbing wax to refill candle.", type = "Call", id = "gui-zDIqalfYUA8" },
      { order = 5, role = "ALL", text = "Interrupt s[Drain Light] from adds - saves candle heat.", type = "Interrupt", id = "gui-32cyGcRmY" },
      { order = 6, role = "TANK", text = "Refuel candle during s[Eternal Darkness] or s[Rising Gloom].", type = "Mechanic", id = "gui-cgZB0bwt7vs" },
      { order = 7, role = "TANK", text = "Tank starting mid-room for wax rotation.", type = "Position", id = "gui-Ec0PGS86fag" },
      { order = 8, role = "TANK", text = "Rotate boss toward wax spawns along track lines.", type = "Position", id = "gui-9iigN6lM1k" },
      { order = 9, role = "TANK", text = "Group adds for cleave. Stun wrigglers.", type = "Mechanic", id = "gui-KzM2M8rAB0" },
      { order = 10, role = "HEALER", text = "Use CDs for s[Eternal Darkness] massive AoE.", type = "Call", id = "gui-s308Kksgbw" },
      { order = 11, role = "HEALER", text = "Top group during s[Rising Gloom] phases.", type = "Mechanic", id = "gui-dq4XWJVbJTY" },
      { order = 12, role = "DPS", text = "Kill n[Darkspawn] quickly. Interrupt s[Drain Light].", type = "Mechanic", id = "gui-sWiy3eBVTg" },
      { order = 13, role = "DPS", text = "Return wax to candle if heat is low.", type = "Mechanic", id = "gui-hmJUBjxB70Q" }
    },
  }
}
