DungeonGuide_Guides["dung-theater-tww-s2"] = {
  unitMapIDs = { 1683, 1684, 1685, 1686, 1687 },
  challengeMapID = {382},
  name = "Theater of Pain",
  id = "dung-theater-tww-s2",
  season = "TWW-S2",
  guideType = "M+",
  
  ["Theater of Pain"] = {
    id = "enc-theater-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "Platform edges knock - stay clear during fights.", type = "Mechanic", id = "gui-rTn7Sfkc99s" },
      { order = 2, role = "ALL", text = "High-priority kicks: Necrotic Bolt, Bone Spear, Discharge, Shout.", type = "Interrupt", id = "gui-ihU6zmS8LEA" },
      { order = 3, role = "ALL", text = "Purge/Soothe: Death Wish, Tantrum, Swift Strikes, Shadow Vulnerability, Bone Shield.", type = "Mechanic", id = "gui-tzXMD0iiDws" },
      { order = 4, role = "ALL", text = "LoS Blade throws near stairs or pillars.", type = "Mechanic", id = "gui-9OqWIZFNlg" },
      { order = 5, role = "ALL", text = "Trash duels before Xav change weekly - learn and assign kicks.", type = "Mechanic", id = "gui-CtfzrkaeTPo" },
      { order = 6, role = "ALL", text = "Stacking bleeds/DoTs require layered dispels and defensives.", type = "Mechanic", id = "gui-YKmDIpxg2g0" },
      { order = 7, role = "ALL", text = "Mordretha: interrupt Death Bolts, dodge charge lines + carnage swirls.", type = "Mechanic", id = "gui-yPGg4cvtzeo" },
      { order = 8, role = "TANK", text = "Big hits: Mortal Strike, Scythe, Unbalancing Blow, Hateful Strike, Smash.", type = "Mechanic", id = "gui-ASF3OniRGw" },
      { order = 9, role = "TANK", text = "Face all frontals away: Bone Storm, Smash, Death Winds, Eruption.", type = "Position", id = "gui-yRko2ew1oIg" },
      { order = 10, role = "HEALER", text = "Heavy AoE: Mighty Smash, Soulstorm, Death Spiral, Manifest Death.", type = "Mechanic", id = "gui-NYuYAZZFvFI" },
      { order = 11, role = "HEALER", text = "Dispel priority: Withering Touch, Necrotic Blight, Curse/Poison, Manifest stacks.", type = "Mechanic", id = "gui-1U6oqkzfUtU" },
      { order = 12, role = "DPS", text = "CD timings: Monstrosity burn, Xav combos, Mordretha p2, Draw Soul adds.", type = "Call", id = "gui-O9g4sZjs6NA" },
      { order = 13, role = "DPS", text = "Kill banners (Xav), cleave adds (Gorechop), and LoS blades.", type = "Mechanic", id = "gui-88rLua7ZIbE" }
    },
  },
  
  ["Route"] = {
    id = "enc-theater-route",    
    order = 2,    
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "Can skip first trash pack. Stay tight on LEFT and follow me.", type = "Call", id = "gui-1YPffLjdwU0" },
      { order = 2, role = "ALL", text = "Pulling first trash into Bloodhorn for cleave.", type = "Call", id = "gui-zxxVDL29AcU" },
      { order = 3, role = "ALL", text = "Boss Fight: An Affront of Challengers", type = "Jump", target="An Affront of Challengers", id = "gui-FweOhs8UMOA" },
      { order = 4, role = "ALL", text = "Going to Xav's wing first after An Affront of Challengers.", type = "Call", id = "gui-LiNzIidodLQ" },
      { order = 5, role = "ALL", text = "Respect Arbalists bleed. Use personals if targeted.", type = "Call", id = "gui-bPN0lhEoUj4" },
      { order = 6, role = "ALL", text = "Nekthara mini first. Watch for Whirlwinds and interrupting roars.", type = "Call", id = "gui-Pa82uN8XDO4" },
      { order = 7, role = "ALL", text = "Harugia next. LOS on stairs if targeted by Ricocheting Blade.", type = "Call", id = "gui-WhI0Ooc511Q" },
      { order = 8, role = "ALL", text = "Focus Captain fast. Pull mobs out of aura if needed.", type = "Call", id = "gui-LwNlZMVqXlc" },
      { order = 9, role = "ALL", text = "Skipping Advent mini if we can, Warlock Gate if up.", type = "Call", id = "gui-YtwnpacEY" },
      { order = 10, role = "ALL", text = "Pulling Advent to stairs for LOS.", type = "Call", id = "gui-UPeRsAgLadA" },
      { order = 11, role = "ALL", text = "Boss Fight: Xav the Unfallen", type = "Jump", target="Xav the Unfallen", id = "gui-ixGnCNaweNI" },
      { order = 12, role = "ALL", text = "After Xav, heading Gorechop side next.", type = "Call", id = "gui-M7Exb8rielY" },
      { order = 13, role = "ALL", text = "Big pull with Sludge Spewers first. Kick Withering Discharge.", type = "Call", id = "gui-0BH2qgRqJIg" },
      { order = 14, role = "ALL", text = "Avoid Gasbag patrol by hugging left wall at top platform.", type = "Call", id = "gui-2IsS3mG6mmc" },
      { order = 15, role = "ALL", text = "Pulling hallway mobs into Gorechop for cleave.", type = "Call", id = "gui-pf2l70YWcXI" },
      { order = 16, role = "ALL", text = "Boss Fight: Gorechop", type = "Jump", target="Gorechop", id = "gui-w1NrFjxWNNA" },
      { order = 17, role = "ALL", text = "After Gorechop, moving into Ossuary wing (Kul'tharok).", type = "Call", id = "gui-RNAxVh5qT4" },
      { order = 18, role = "ALL", text = "Grouping souls with LOS up to 1st Guardian. Let me agro.", type = "Call", id = "gui-6osMfh9Jl8k" },
      { order = 19, role = "ALL", text = "Taking right-left-right portals.", type = "Call", id = "gui-avACROFhTyA" },
      { order = 20, role = "ALL", text = "Focus Bone Magi shields with Purge or heavy single-target.", type = "Call", id = "gui-F4gThntmqkg" },
      { order = 21, role = "ALL", text = "Avoid pulling Dark Speakers unless we need for count.", type = "Call", id = "gui-KrjQlEiAPYU" },
      { order = 22, role = "ALL", text = "Boss Fight: Kul'tharok", type = "Jump", target="Kul'tharok", id = "gui-WiYIaXjhb8" },
      { order = 23, role = "ALL", text = "Kill extra trash near final portal if short on count.", type = "Call", id = "gui-KdvW1vtTDB4" },
      { order = 24, role = "ALL", text = "Boss Fight: Mordretha, the Endless Empress", type = "Jump", target="Mordretha, the Endless Empress", id = "gui-VOk3PtBefGw" }
    },
  },

  ["An Affront of Challengers"] = {
    id = "enc-theater-an-affront-of-challengers",
    order = 3,
    header = "Boss: An Affront of Challengers",
    entries = {
      { order = 1, role = "ALL", text = "Loosely spread before Searing Death - use defensive if also hit by AoE.", type = "Call", id = "gui-ASDbNxH2ztA" },
      { order = 2, role = "ALL", text = "Bait and rotate during Noxious Spores - drop puddles safely.", type = "Mechanic", id = "gui-YFDB5dNcFYg" },
      { order = 3, role = "ALL", text = "Interrupt Necromantic Bolt - reduces tank pressure.", type = "Interrupt", id = "gui-LgE3qBqQSw" },
      { order = 4, role = "ALL", text = "Keep boss HPs even - Final Will stacks on survivors.", type = "Mechanic", id = "gui-6VQ6pUbhex0" },
      { order = 5, role = "ALL", text = "Avoid arena edges - outside combatants will knock you back.", type = "Mechanic", id = "gui-EPzp100mTIc" },
      { order = 6, role = "TANK", text = "Use defensive on Mortal Strike - heavy hit + 50% healing debuff.", type = "Mechanic", id = "gui-JDkZOhw3Pag" },
      { order = 7, role = "TANK", text = "Will pull bosses near entrance. Rotating clockwise as group after Spores.", type = "Call", id = "gui-zZm3e3Huyxo" },
      { order = 8, role = "TANK", text = "Face Paceran away - random frontal breath can be lethal.", type = "Position", id = "gui-t4zdueRrEWM" },
      { order = 9, role = "HEALER", text = "Dispel Withering Touch ASAP. Two players affected at once.", type = "Mechanic", id = "gui-H1xsgaZ63kA" },
      { order = 10, role = "HEALER", text = "Prep CDs for Searing Death + Mighty Smash overlap.", type = "Call", id = "gui-dpYMZBK2SgY" },
      { order = 11, role = "DPS", text = "Focus Sathel early to reduce magic pressure.", type = "Mechanic", id = "gui-0metjn3tAI0" },
      { order = 12, role = "DPS", text = "Dodge Decaying Breath frontal from Paceran.", type = "Mechanic", id = "gui-AvQ7DMhw4Ys" }
    },
  },
  
  ["Xav the Unfallen"] = {
    id = "enc-theater-xav-the-unfallen",
    order = 4,
    header = "Boss: Xav the Unfallen",
    entries = {
      { order = 1, role = "ALL", text = "Oppressive Banner up - drag boss to cleave ASAP.", type = "Call", id = "gui-jhlTWv9BrG0" },
      { order = 2, role = "ALL", text = "Avoid combo: Cleave (frontal), Slam (line), Crash (AoE silence).", type = "Mechanic", id = "gui-AGwg554U" },
      { order = 3, role = "ALL", text = "Blood and Glory - duel in pit. End fast for buff.", type = "Call", id = "gui-vvMVJ7zZrKI" },
      { order = 4, role = "ALL", text = "Interrupt Demoralizing Shout from Captains (trash).", type = "Interrupt", id = "gui-UA0Osmltb3w" },
      { order = 5, role = "TANK", text = "CD for Brutal Combo - heavy phys channel.", type = "Mechanic", id = "gui-N0GW5Uptq50" },
      { order = 6, role = "TANK", text = "Pre-position boss near banner spawn and away from group.", type = "Position", id = "gui-dCoGJu0M1nI" },
      { order = 7, role = "TANK", text = "Rotate boss between phases to avoid clipping party.", type = "Mechanic", id = "gui-E6jvjq8hug" },
      { order = 8, role = "HEALER", text = "CDs for Might of Maldraxxus combo (3 overlapping hits).", type = "Call", id = "gui-NlvLX2zJeMI" },
      { order = 9, role = "HEALER", text = "Top duel players after return - they re-enter with damage taken.", type = "Mechanic", id = "gui-NPr9nc09HC4" },
      { order = 10, role = "DPS", text = "Kill Banner fast - slow makes combo phase lethal.", type = "Mechanic", id = "gui-jsRX9ZEWsdE" },
      { order = 11, role = "DPS", text = "Win duel fast - Glorified buff = big damage.", type = "Call", id = "gui-RsIf2SZZFFY" },
      { order = 12, role = "DPS", text = "Avoid all 3 combo casts - spread + move early.", type = "Mechanic", id = "gui-Rk6fn8EVOjs" }
    },
  },
  
  ["Kul'tharok"] = {
    id = "enc-theater-kultharok",
    order = 5,
    header = "Boss: Kul'tharok",
    entries = {
      { order = 1, role = "ALL", text = "Draw Soul: Stack at edge to drop adds, then AoE + CC fast.", type = "Call", id = "gui-Xz5fWns9d0Y" },
      { order = 2, role = "ALL", text = "Well of Darkness on you - spread 4yds, use personal.", type = "Call", id = "gui-xpu2903zLsQ" },
      { order = 3, role = "ALL", text = "Avoid Death Spiral - orbs rotate arena, heavy damage.", type = "Mechanic", id = "gui-ou8BxdzJJyg" },
      { order = 4, role = "ALL", text = "Interrupt Necrotic Bolt casts throughout fight.", type = "Interrupt", id = "gui-7FdFImQtw4U" },
      { order = 5, role = "TANK", text = "Face boss away. Avoid standing in central puddle - high shadow dmg.", type = "Mechanic", id = "gui-Zu1aIVWit5I" },
      { order = 6, role = "TANK", text = "Pull slightly off-center to give melee orb room.", type = "Position", id = "gui-Qvu8RcCRK4" },
      { order = 7, role = "TANK", text = "No tank buster - save CDs for Draw Soul if needed.", type = "Call", id = "gui-Dr4oicTHgfQ" },
      { order = 8, role = "HEALER", text = "Prep CDs for Draw Soul - 8s ticking + post-add pressure.", type = "Call", id = "gui-jfITevLI0xM" },
      { order = 9, role = "HEALER", text = "Dispel Shadow Vulnerability from Well of Darkness.", type = "Mechanic", id = "gui-l5lbArtCcBk" },
      { order = 10, role = "DPS", text = "Burn adds from Draw Soul fast - don't let them reach boss.", type = "Mechanic", id = "gui-92gH9eMQEP0" },
      { order = 11, role = "DPS", text = "Stay loose - don't overlap Well DoTs or orbs.", type = "Mechanic", id = "gui-Lz2c0xY6qW8" }
    },
  },

  ["Gorechop"] = {
    id = "enc-theater-gorechop",
    order = 6,
    header = "Boss: Gorechop",
    entries = {
      { order = 1, role = "ALL", text = "Meat Hooks: Find the gap - dodge both waves cleanly.", type = "Call", id = "gui-oLnC6vc2Kf8" },
      { order = 2, role = "ALL", text = "Tenderizing Smash: Run out when pulled - avoid frontal slam.", type = "Call", id = "gui-3Uay5K1v4Os" },
      { order = 3, role = "ALL", text = "Kill adds near same location to control puddle sprawl.", type = "Mechanic", id = "gui-2zEBYumHQGU" },
      { order = 4, role = "ALL", text = "Interrupt Withering Discharge from Sludge-spewers.", type = "Interrupt", id = "gui-6p76xeAywg" },
      { order = 5, role = "TANK", text = "Use defensive on Hateful Strike - massive phys hit.", type = "Mechanic", id = "gui-Nz3WkkFiJXw" },
      { order = 6, role = "TANK", text = "Pull boss near wall or cleared area before Smash.", type = "Position", id = "gui-utSmf7GeRDg" },
      { order = 7, role = "TANK", text = "Drag adds to boss for cleave. Control puddle zones.", type = "Mechanic", id = "gui-Thvx3mUVHr4" },
      { order = 8, role = "TANK", text = "Face boss away after Smash - avoid cleaving group.", type = "Position", id = "gui-hLftPstS8uA" },
      { order = 9, role = "HEALER", text = "Top group before Smash + Hooks combo - heavy burst.", type = "Call", id = "gui-VcMhm3NXp54" },
      { order = 10, role = "HEALER", text = "Dispel Withering Touch and Filth from party.", type = "Mechanic", id = "gui-mqAqgTEliDo" },
      { order = 11, role = "DPS", text = "Spread for Leaping Thrash from adds.", type = "Mechanic", id = "gui-1pRhXuAxjG0" },
      { order = 12, role = "DPS", text = "Burn Leftovers fast - kill near edge to conserve space.", type = "Mechanic", id = "gui-MZ6Io76So4" }
    },
  },
  
  ["Mordretha, the Endless Empress"] = {
    id = "enc-theater-mordretha",
    order = 7,
    header = "Boss: Mordretha, the Endless Empress",
    entries = {
      { order = 1, role = "ALL", text = "Manifest Death: Spread out. Kick your Deathwalker, cleave them up.", type = "Call", id = "gui-XgE7g0qQQw8" },
      { order = 2, role = "ALL", text = "Echoes of Carnage: Dodge charge lines and swirlies.", type = "Call", id = "gui-kFz60wpzX0o" },
      { order = 3, role = "ALL", text = "Grasping Rift: Move out fast - avoid curse + stun pull.", type = "Mechanic", id = "gui-HbdNOOcZYDM" },
      { order = 4, role = "ALL", text = "Avoid Dark Devastation - frontal sweeps during cast.", type = "Mechanic", id = "gui-a5HEYRbg5FU" },
      { order = 5, role = "ALL", text = "Don't hug arena edge - knockback risk from surrounding mobs.", type = "Mechanic", id = "gui-NQVz719lJ7s" },
      { order = 6, role = "TANK", text = "CD for every Reaping Scythe - huge Shadow + physical hit.", type = "Mechanic", id = "gui-QbTTTAcsWVY" },
      { order = 7, role = "TANK", text = "Pulling boss to side - gives room to avoid Rift/Devastation.", type = "Call", id = "gui-sGklOwRLpJE" },
      { order = 8, role = "TANK", text = "Drag Deathwalkers into cleave. Group them fast.", type = "Call", id = "gui-flmG3qRjM" },
      { order = 9, role = "HEALER", text = "CDs for Manifest Death + Deathwalker add phase.", type = "Call", id = "gui-nQl5SBxHPXY" },
      { order = 10, role = "HEALER", text = "Dispel Death Grasp curse if player is pulled by Rift.", type = "Mechanic", id = "gui-THYQp54aAtk" },
      { order = 11, role = "DPS", text = "Interrupt your Deathwalker fast. Group them under boss.", type = "Mechanic", id = "gui-6UTFukRxkI" },
      { order = 12, role = "DPS", text = "Save CDs for grouped adds and Echoes overlap.", type = "Call", id = "gui-AdS2XL2iYI" }
    },
  }
}
