DungeonGuide_Guides["Operation: Floodgate"] = {
  id = "dung-floodgate",
  ["Operation: Floodgate"] = {
    id = "enc-floodgate-guide",
    order = 1,
    header = "Intro",
    entries = {
      { role = "ALL", text = "32-minute timer with open layout — first two bosses can be done in any order.", type = "Mechanic", id = "gui-i6hdbRa4yjs" },
      { role = "ALL", text = "Collect all 5 Weapon Stockpiles to unlock n:Swampface: — some are off-path.", type = "Mechanic", id = "gui-zOtwsukZ5Bg" },
      { role = "ALL", text = "Use gliders (by stockpile on dam) for shortcuts — let tank go first!", type = "Mechanic", id = "gui-wCkEGlbzSS0" },
      { role = "ALL", text = "Zeppelin patrol fires missiles — use rocket after n:Demolition Duo: to shoot it down.", type = "Mechanic", id = "gui-DGyNVzY62w" },
      { role = "ALL", text = "Interrupt priority: s:Maximum Distortion:, s:Warp Blood:, s:Trick Shot:, s:Surveying Beam:.", type = "Interrupt", id = "gui-mzbIZmcLio" },
      { role = "ALL", text = "Magic dispels needed for s:Overcharge:, s:Electro-Gel:, s:Blood-Infused Strikes:.", type = "Mechanic", id = "gui-VO39kXzlsLQ" },
      { role = "ALL", text = "Avoid swirlies, bombs, saws, and CC-immune mob abilities throughout all wings.", type = "Mechanic", id = "gui-isLxSCTPOKk" },
      { role = "TANK", text = "n:Venture Co. Architect:s gain DR on scaffolding — break it ASAP.", type = "Mechanic", id = "gui-DkHJOa3v2BE" },
      { role = "TANK", text = "n:Loaderbot:s, n:Shreddinator 3000:, and n:Divers: have disruptive fixates or random bleeds.", type = "Mechanic", id = "gui-Gej86gG0TVw" },
      { role = "TANK", text = "Pull n:Bombshell Crabs: carefully — s:Crabsplosion: stacks on death.", type = "Mechanic", id = "gui-VosZOR2lcOc" },
      { role = "HEALER", text = "Prepare healing CDs for s:Warp Blood:, s:Backwash:, and s:Bubble Burp: overlaps.", type = "Mechanic", id = "gui-rW2jj1srXWo" },
      { role = "HEALER", text = "Dispel s:Overcharge: quickly — stun on expiration is lethal in AoE overlap.", type = "Mechanic", id = "gui-De0vQFgiIYM" },
      { role = "DPS", text = "Prioritise n:Darkfuse Bloodwarper:s and n:Darkfuse Inspector:s — dangerous group hits and teleports.", type = "Mechanic", id = "gui-tyZcTsi7W8E" },
      { role = "DPS", text = "Use CC to stop s:Wind-Up:, s:Surveying Beam:, and s:Jetison Kelp: when kicks are tight.", type = "Mechanic", id = "gui-dSnqczjIxrU" }
    },
  },

  ["Route"] = {
    id = "enc-floodgate-route",
    order = 2,
    header = "Route",
    entries = {
      { role = "ALL", text = "Pulling double n:Darkfuse Soldiers:, n:Venture Co. Contractors:, n:Surveyors:, and n:Shreddinator 3000: first. Bloodlust and burn cooldowns.", type = "Call", id = "gui-NCFjtHrwLQg" },
      { role = "ALL", text = "Next pull: Jump down after Weapon Stock blows. All trash around pool.", type = "Call", id = "gui-rp8MtULJKnw" },
      { role = "ALL", text = "Up stairs into n:Darkfuse Demolitionist: + n:Mechadrone Sniper: + n:Darkfuse Inspectors:.", type = "Call", id = "gui-EzscQNsopm4" },
      { role = "ALL", text = "Up LEFT stairs before n:Big M.O.M.M.A.:.", type = "Call", id = "gui-oBwAZxR9P4E" },
      { role = "ALL", text = "Boss pull: n:Big M.O.M.M.A.: next.", type = "Call", id = "gui-ks1xLdlsCDY" },
      { role = "ALL", text = "Post-boss: Pull n:Darkfuse Soldiers: and n:Darkfuse Bloodwarper:. Focus n:Bloodwarper:.", type = "Call", id = "gui-mI2Uwu6J2uU" },
      { role = "ALL", text = "Back across floor. Chain in n:Loaderbots:. Bloodlust when clearing n:Bloodwarper: pack.", type = "Call", id = "gui-A627BGVwkio" },
      { role = "ALL", text = "Glider across. Pull left into right then up stairs.", type = "Call", id = "gui-rs8I4V0RX5o" },
      { role = "ALL", text = "Chain double n:Shreddinator 3000s: into Contractors.", type = "Call", id = "gui-m9EffM96yw" },
      { role = "ALL", text = "Short pull to boss: n:Contractors: and n:Surveyor:.", type = "Call", id = "gui-SY2xpuzDdU" },
      { role = "ALL", text = "Boss pull: n:Demolition Duo:.", type = "Call", id = "gui-WxdVC3DGtdU" },
      { role = "ALL", text = "Post-boss: Pull all n:Disturbed Kelp:s together and AoE.", type = "Call", id = "gui-BjG2NaGSusk" },
      { role = "ALL", text = "Boss pull: n:Swampface:.", type = "Call", id = "gui-i6ykxT0uZeo" },
      { role = "ALL", text = "Pull n:Bubbles: solo at bridge. Keep him controlled.", type = "Call", id = "gui-9TBw8a49oKw" },
      { role = "ALL", text = "Pull n:Contractors:, n:Electricians:, n:Inspectors: carefully. Kick n:Electricians:.", type = "Call", id = "gui-yDrBWJbQ0RU" },
      { role = "ALL", text = "Final pulls: n:Darkfuse Soldiers:, n:Contractors:, n:Jumpstarters: into final boss.", type = "Call", id = "gui-OBTG7XsQ34" }
    },
  },
  
  ["Big M.O.M.M.A."] = {
    id = "enc-floodgate-big-momma",
    order = 3,
    header = "Boss: Big M.O.M.M.A.",
    entries = {
      { role = "ALL", text = "Interrupt s:Maximum Distortion: — pulsing AoE + pushback.", type = "Interrupt", id = "gui-RMekVpcGEQ" },
      { role = "ALL", text = "s:Jumpstart: phase — pop cooldowns and burn boss.", type = "Call", id = "gui-lU3SaCHKdfY" },
      { role = "ALL", text = "s:Sonic Boom: on you — aim away and dodge to avoid silence/explosion.", type = "Call", id = "gui-L5fVNDwH1To" },
      { role = "TANK", text = "Major CD for s:Electrocrush: — big nature hit + 10s DoT.", type = "Mechanic", id = "gui-Ey6UOVac5jQ" },
      { role = "TANK", text = "Keep boss near edge pre-burn for space.", type = "Position", id = "gui-JjwoRNBCFcU" },
      { role = "TANK", text = "Pick up n:Mechadrone: adds fast — prevent healer stress.", type = "Mechanic", id = "gui-3Rh7EfhUjc" },
      { role = "TANK", text = "Stack adds for cleave + interrupts.", type = "Position", id = "gui-P34WhM7ImZg" },
      { role = "TANK", text = "Mark adds if interrupts are missed. Rotate kicks.", type = "Mechanic", id = "gui-ryBzfUATEI" },
      { role = "TANK", text = "Reposition boss early during burn to avoid puddle overlap.", type = "Mechanic", id = "gui-ZbWkGzDeEP4" },
      { role = "TANK", text = "s:Electrocrush: DoT stacks with ambient pulses — mitigate.", type = "Mechanic", id = "gui-ZGIkW1At5qA" },
      { role = "TANK", text = "Keep gap behind boss to bait s:Doom Storm: safely.", type = "Position", id = "gui-aOnQQUs0HeI" },
      { role = "HEALER", text = "CDs for s:Jumpstart: — group-wide pulses every 1.5s.", type = "Call", id = "gui-Tu1DPpbiE8s" },
      { role = "HEALER", text = "Watch s:Sonic Boom: target — high overlap risk.", type = "Mechanic", id = "gui-HIEdE8rv60" },
      { role = "HEALER", text = "Spot heal tank during s:Electrocrush: DoT.", type = "Mechanic", id = "gui-TLcz6RYyKE" },
      { role = "DPS", text = "Kill adds fast — avoid s:Kill-o-Block Barrier: wipe.", type = "Mechanic", id = "gui-Mm41xyA4R4Q" },
      { role = "DPS", text = "Spread for s:Doom Storm: from n:Mechadrone: dashes.", type = "Mechanic", id = "gui-wA9JXGG9YKs" },
      { role = "DPS", text = "Save cooldowns for s:Jumpstart: burn phase.", type = "Call", id = "gui-2yHjxKDCWo" }
    },
  },

  ["Demolition Duo"] = {
    id = "enc-floodgate-demolition-duo",
    order = 4,
    header = "Boss: Demolition Duo",
    entries = {
      { role = "ALL", text = "s:Gel: on me — moving to bomb. Dispel once stacked.", type = "Call", id = "gui-inVRZcNumpM" },
      { role = "ALL", text = "Charge incoming — line it through bombs.", type = "Call", id = "gui-YsehYQJFCh0" },
      { role = "ALL", text = "Interrupt s:Quick Shot: or s:Trick Shot: from n:Keeza:.", type = "Interrupt", id = "gui-D77Rs6GJ12c" },
      { role = "TANK", text = "Major for s:Wallop: — tank buster + 5yd cleave/knockup.", type = "Mechanic", id = "gui-W30GbqBfyvs" },
      { role = "TANK", text = "Drag n:Bront: to n:Keeza: for cleave + bomb clear.", type = "Position", id = "gui-gJ2FzOthk7U" },
      { role = "TANK", text = "Final s:Charge: targets you — position near last bomb.", type = "Mechanic", id = "gui-kddQc2lesyc" },
      { role = "TANK", text = "Swap targets. Both bosses must die together.", type = "Call", id = "gui-borAFTb6Apw" },
      { role = "TANK", text = "Save short CD if s:Wallop: overlaps s:BBBFG: or s:Quick Shot:.", type = "Mechanic", id = "gui-0yhV3PT9sI" },
      { role = "TANK", text = "Use movement to reposition after charges.", type = "Mechanic", id = "gui-FCD75VysAhw" },
      { role = "TANK", text = "Face n:Bront: away — avoid cleaving group.", type = "Position", id = "gui-8KgLlSMDi8g" },
      { role = "TANK", text = "Hold final dispel until n:Bront’s: charge finishes.", type = "Call", id = "gui-G1sFDKxHN8" },
      { role = "HEALER", text = "CDs if bomb fails — heavy group DoT.", type = "Call", id = "gui-mdMnN2Pjrk4" },
      { role = "HEALER", text = "Dispel s:Gel: when player stacks on bomb.", type = "Mechanic", id = "gui-VV7pljXpjI" },
      { role = "HEALER", text = "Top group before s:BBBFG: + s:Quick Shot: overlaps.", type = "Mechanic", id = "gui-am3ssZC79uE" },
      { role = "DPS", text = "Help clear bombs early. Dispel/charge quickly.", type = "Mechanic", id = "gui-RraolEJQLQs" },
      { role = "DPS", text = "Dodge s:BBBFG: lines from n:Keeza:.", type = "Mechanic", id = "gui-SPL57G647Y0" },
      { role = "DPS", text = "Balance boss HPs to prevent enrage.", type = "Mechanic", id = "gui-edsQK7063gs" }
    },
  },
  
  ["Swampface"] = {
    id = "enc-floodgate-swampface",
    order = 5,
    header = "Boss: Swampface",
    entries = {
      { role = "ALL", text = "s:Mudslide cast: — dodge LEFT with partner.", type = "Call", id = "gui-OxX4Y5n5Z2I" },
      { role = "ALL", text = "s:Awaken the Swamp: — pop defensives + dodge waves.", type = "Call", id = "gui-F1podl676nQ" },
      { role = "ALL", text = "Stay near your partner — 14yds breaks tether and pulls.", type = "Mechanic", id = "gui-bmolTOQSayw" },
      { role = "TANK", text = "Major CD for s:Sludge Claws: — phys + nature hit + absorb.", type = "Mechanic", id = "gui-xizpmOPgs" },
      { role = "TANK", text = "If tethered, stay close to group — avoid dragging.", type = "Mechanic", id = "gui-tde8FoXhw0" },
      { role = "TANK", text = "Keep boss steady during waves — no erratic movement.", type = "Position", id = "gui-X30kArTJx0" },
      { role = "TANK", text = "Always dodge LEFT.", type = "Call", id = "gui-4Yv99gDOc8" },
      { role = "TANK", text = "Anchor group mid-fight. Moving randomly drags others.", type = "Position", id = "gui-3RIVDB8aW4Q" },
      { role = "TANK", text = "s:Sludge Claws: hurts — spot healing needed.", type = "Call", id = "gui-55lsSaqdp0I" },
      { role = "TANK", text = "Dodge early to avoid snapping tethers through AoE.", type = "Mechanic", id = "gui-YMqd6XLTS2s" },
      { role = "HEALER", text = "CDs for s:Awaken: — heavy ramp damage.", type = "Call", id = "gui-G3U2aBhgIA" },
      { role = "HEALER", text = "Heal tether partners — heavy ticking DoT.", type = "Mechanic", id = "gui-PUcNaPQZqr0" },
      { role = "HEALER", text = "Top group post-Mudslide for wave phase.", type = "Mechanic", id = "gui-zEBbBdKylGo" },
      { role = "DPS", text = "Stick with partner. Dodge left together.", type = "Mechanic", id = "gui-MwtJRkwJx2s" },
      { role = "DPS", text = "Use personals during s:Awaken: + Vine combo.", type = "Call", id = "gui-tGBZW5VE6Y" },
      { role = "DPS", text = "Avoid overlapping swirlies — spread out.", type = "Position", id = "gui-FbTVFrlDpk" }
    },
  },
  
  ["Geezle Gigazap"] = {
    id = "enc-floodgate-geezle-gigazap",
    order = 6,
    header = "Boss: Geezle Gigazap",
    entries = {
      { role = "ALL", text = "s:Turbocharge:soon — use defensive + dodge lines.", type = "Call", id = "gui-7jVXvLC6oXs" },
      { role = "ALL", text = "Spark fixating me — kiting to a clean puddle.", type = "Call", id = "gui-Mar0Mvj5NKM" },
      { role = "TANK", text = "Major CD for s:Thunder Punch: — phys + nature DoT + knockback.", type = "Mechanic", id = "gui-whqGTSg5W0" },
      { role = "TANK", text = "Keep back to console — avoid knockback into water.", type = "Position", id = "gui-8cMVQ9puyg" },
      { role = "TANK", text = "Avoid puddles while debuffed — don’t electrify them.", type = "Mechanic", id = "gui-yrWUTqqpBoA" },
      { role = "TANK", text = "Shift boss slightly between casts to rotate safe puddles.", type = "Position", id = "gui-xz597X8wfKk" },
      { role = "TANK", text = "Don’t charge through puddles with s:Thunder Punch: DoT.", type = "Mechanic", id = "gui-ReW09UMWhw" },
      { role = "TANK", text = "Use mitigation for spark + puddle overlaps — big damage.", type = "Mechanic", id = "gui-cSu1qIKeE0" },
      { role = "HEALER", text = "CDs for s:Turbocharge: — AoE every 1s + random lines.", type = "Call", id = "gui-flcsY0ll1Og" },
      { role = "HEALER", text = "Top off n:Gigazap: targets before puddle movement.", type = "Mechanic", id = "gui-9Jx8Y8lZ9OE" },
      { role = "DPS", text = "Spread n:Gigazap: away from puddles and group.", type = "Mechanic", id = "gui-fFtmNQBi4lo" },
      { role = "DPS", text = "Use water to soak Sparks — avoid electrified ones.", type = "Mechanic", id = "gui-u9BKZXK4v1Q" },
      { role = "DPS", text = "Dodge swirlies + s:Thunder Punch: lines mid-phase.", type = "Mechanic", id = "gui-ZKrjTMw8LSA" }
    },
  }
}
