DungeonGuide_Guides["Liberation of Undermine"] = {
  id = "dung-liberation",
  ["Liberation of Undermine"] = {
      id = "enc-liberation-guide",
      order = 1,
      header = "Guide: Liberation of Undermine",
      ALL = {
        { text = "To Be Added", type = "Mechanic", id = "gui-BCgkjzycxiY" }
      },
      TANK = {
        { text = "To Be Added", type = "Call", id = "gui-u0rcqX0LjLs" }
      },
      HEALER = {
        { text = "To Be Added", type = "Position", id = "gui-1kPbeGbrBSU" }
      },
      DPS = {
        { text = "To Be Added", type = "Interrupt", id = "gui-UL0HRP5Z2s8" }
      },
    },
  
    ["Vexie and the Geargrinders"] = {
      id = "enc-liberation-vexie-and-the-geargrinders",
      order = 2,
      header = "Boss: Vexie and the Geargrinders",
      ALL = {
        { text = "TANK: Swap on each Tank Buster, move boss to avoid puddles & bikes.", type = "Call", id = "gui-HW0YbdRGs" },
        { text = "DPS: Kill bikers, fuel & crash into boss before 100 energy. Kill Pit Mechanics during intermission.", type = "Call", id = "gui-AurNc58P1X8" },
        { text = "HEALER: Heal through Bomb Voyage! & Intermission, watch Fire debuffs.", type = "Call", id = "gui-kDwRjmqTytQ" },
        { text = "Boss must be tanked near wall to cleave bikers safely.", type = "Position", id = "gui-OM5dtD1mstM" },
        { text = "Tank will move Boss after Buster. For Oil far middle to drop safely.", type = "Mechanic", id = "gui-yvWYRpuGVE" },
        { text = "Spread loosely to avoid splash from Incendiary Fire.", type = "Position", id = "gui-9gCLy1Q2tM" },
        { text = "Kill bikers before they charge again.", type = "Call", id = "gui-PTznva58M3M" },
        { text = "Crash bikes into boss to remove 1 stack of plating each.", type = "Call", id = "gui-tHHVhiEbNNQ" },
        { text = "Do not ride through oil puddles—stuns and wastes bike.", type = "Call", id = "gui-7XYzA7nuGQU" },
        { text = "Use Bloodlust during Intermission (100% boss damage taken).", type = "Call", id = "gui-R8nJJaRoZqQ" },
        { text = "Interrupt Pit Mechanics or boss will heal rapidly.", type = "Call", id = "gui-gbBqFtP3H60" },
        { text = "Dodge shrapnel during Mechanical Breakdown.", type = "Mechanic", id = "gui-ZGaKrGyNWHw" },
        { text = "Fight restarting — resume biker cycle.", type = "Call", id = "gui-E0mB8byQsaA" },
        { text = "[M] Catch Oil Canisters from dead bikers—each missed one spawns a puddle.", type = "Mechanic", id = "gui-dNh7Jx3ihks" },
        { text = "[M] Refuel bikes using 2 Oil Canisters before use—assign a left-to-right refuel order.", type = "Call", id = "gui-m9rkSMPvpsY" },
        { text = "[M] Players who catch Canisters take +500% damage from next Canister for 1 min—rotate duties.", type = "Mechanic", id = "gui-Uxk8zqdlw" },
        { text = "[M] Aim to remove at least 3 stacks of plating by 50 energy to stay on pace.", type = "Call", id = "gui-7ghIP5iI0ko" },
        { text = "[M] CC the Support Rig during Intermission or Pit Mechanics become immune to interrupts.", type = "Interrupt", id = "gui-pYafl6kYAM" },
        { text = "[M] Support Rig despawns after Intermission—don't waste time trying to kill it.", type = "Call", id = "gui-RPkaW3wTGys" }
      },
      TANK = {
        { text = "Swap on every Tank Buster (DoT + knockback).", type = "Mechanic", id = "gui-S3YYlGb0Kfs" },
        { text = "Move boss each Buster to avoid oil zones in cleave area.", type = "Position", id = "gui-ISKvwNj2KU" },
        { text = "Avoid dropping Oil where bikes will path through.", type = "Mechanic", id = "gui-RtcPKtIYMo8" },
        { text = "Keep boss near wall to group biker spawn for cleave.", type = "Position", id = "gui-RSnaoH7lWXQ" },
        { text = "[M] Be mindful of Support Rig position—grips or knockbacks help keep it from boss.", type = "Call", id = "gui-OkaCgjtU9nw" }
      },
      HEALER = {
        { text = "Prep for raid-wide damage: Bomb Voyage! and Intermission.", type = "Mechanic", id = "gui-JFgSYlg0teQ" },
        { text = "Watch players hit by Incendiary Fire and Bikers.", type = "Mechanic", id = "gui-7T5WB2yF6DM" },
        { text = "Heavy damage during Mechanical Breakdown (Backfire), personal defensives.", type = "Call", id = "gui-GsPjvL5mlJA" },
        { text = "Dispel slows from Oil if needed.", type = "Mechanic", id = "gui-PmcveI7X8PI" },
        { text = "[M] Extra healing needed if Canisters missed—oil puddles may limit space and cause splash damage.", type = "Mechanic", id = "gui-eCuPmYQl09k" }
      },
      DPS = {
        { text = "Kill bikers quickly to enable plating removal.", type = "Mechanic", id = "gui-OBu59f8rI" },
        { text = "Use Fire debuff to burn Oil puddles away.", type = "Mechanic", id = "gui-OjYPgTOwSKo" },
        { text = "Interrupt Pit Mechanics during Intermission.", type = "Interrupt", id = "gui-kIim3joCaUI" },
        { text = "Maximise cleave on boss + biker overlap.", type = "Position", id = "gui-nKOLpYoj8" },
        { text = "[M] Assign DPS to catch and refuel bikes—rotate Canister soakers to avoid debuff overlap.", type = "Mechanic", id = "gui-5pSWndUpY4" },
        { text = "[M] Use CC on Support Rig during Intermission—grips, stuns, vortexes, etc.", type = "Interrupt", id = "gui-1p0Wdn9DnDc" }
      }
    },

    ["Cauldron of Carnage"] = {
        id = "enc-liberation-cauldron-of-carnage",
        order = 3,
        header = "Boss: Cauldron of Carnage",
        ALL = {
          { text = "TANK: Keep bosses apart, swap sides (Taunt) after intermission, dodge Clash AoE.", type = "Call", id = "gui-sf7WC77Zbs" },
          { text = "DPS: Kill Voltaic Images fast, spread for Phlegm & Salvos. Intermission: focus boss with more HP.", type = "Call", id = "gui-dq0iyyFFCIc" },
          { text = "HEALER: Use CDs for Scrapbomb + Phlegm & Intermission damage.", type = "Call", id = "gui-xPP3ZOO6gQ" },
          { text = "Split raid into 2 groups: Flamendo (mostly ranged), Torq (mostly melee).", type = "Position", id = "gui-b1soimFahE" },
          { text = "Soak Scrapbomb with 4+ players or raid takes massive damage.", type = "Mechanic", id = "gui-2hMNbW5bd7c" },
          { text = "Spread out quickly for Molten Phlegm after each Scrapbomb.", type = "Mechanic", id = "gui-y53MFP8nnlo" },
          { text = "Avoid laser fixate from Flamendo—turn away from raid and other group.", type = "Call", id = "gui-72QmLgM8ow" },
          { text = "Stay mostly still on Torq side to avoid filling Static Charge.", type = "Mechanic", id = "gui-YFsYNbk31MY" },
          { text = "Dodge Thunderdrum Salvo circles—move only if your Static Charge is low.", type = "Mechanic", id = "gui-tsuqTMWepb4" },
          { text = "Kill Voltaic Images quickly—don’t let them reach players.", type = "Mechanic", id = "gui-sep5ae74xbM" },
          { text = "During Intermission, focus boss with more HP to balance kills.", type = "Call", id = "gui-SVvHeZj2ww" },
          { text = "Dodge Zapbolts and Fiery Waves during Colossal Clash.", type = "Mechanic", id = "gui-k6FeGo89nMY" },
          { text = "If one boss dies, swap quickly and prepare for increased damage.", type = "Call", id = "gui-7Kk05AjZOfQ" },
          { text = "[M] Each side gets 3 'Tiny Tussle' toys—crash 2 at a time to avoid raid-wide DoT stacking.", type = "Mechanic", id = "gui-7kbtQXowAY" },
          { text = "[M] All remaining toys auto-crash during intermission—clear them before then.", type = "Call", id = "gui-SlfBKlWH3k" },
          { text = "[M] Flamendo side should control crash timing—knock toys between bomb soaks.", type = "Mechanic", id = "gui-2SKRmJTM4" },
          { text = "[M] Torq side knock all toys at pull—can’t move freely later due to debuff.", type = "Call", id = "gui-Ujo6jHED6gQ" },
          { text = "[M] Send 1–2 extra players to Flamendo for safer bomb soaks—balance boss HP later.", type = "Position", id = "gui-V2HLEJPzG0k" },
        },
        TANK = {
          { text = "Flarendo: Watch for Eruption Stomp—knockup + fiery wave combo.", type = "Mechanic", id = "gui-Kc9V1macRI" },
          { text = "Torq: Lightning Bash scales with unmitigated damage—use cooldowns.", type = "Mechanic", id = "gui-23i40HnbWk8" },
          { text = "Do NOT tank bosses near each other—Raised Guard triggers 99% DR.", type = "Position", id = "gui-Tca3KtZM8WQ" },
          { text = "Swap sides after Intermission to avoid stacking DoTs.", type = "Mechanic", id = "gui-CN6DLirETE" },
        },
        HEALER = {
          { text = "Expect high group damage after Scrapbomb and Molten Phlegm combo.", type = "Call", id = "gui-NHrl3oll7ik" },
          { text = "Top players quickly if hit by laser or Voltaic Image explosion.", type = "Mechanic", id = "gui-T06sp4jX3nU" },
          { text = "Heavy healing during Colossal Clash—20s unavoidable AoE.", type = "Call", id = "gui-tcOjWkk6rGg" },
          { text = "Silence pools from Voltaic Images can lock out healers—watch placement.", type = "Mechanic", id = "gui-RIYzHQ5CJo" },
          { text = "[M] Pre-plan healing CDs if toys crash during intermission—stacks with Zapbolt damage.", type = "Call", id = "gui-zrf1xqLps0" },
        },
        DPS = {
          { text = "Flarendo side: spread around bomb soak to avoid Phlegm overlap.", type = "Position", id = "gui-K9kYhmHd1o" },
          { text = "Torq side: move as little as possible—Static Charge stuns at full.", type = "Mechanic", id = "gui-Lkj90fHmQ" },
          { text = "Kill Voltaic Images fast to prevent fixate explosions.", type = "Mechanic", id = "gui-hZwz6bE1NJU" },
          { text = "Use intermission to burn the higher HP boss to even health.", type = "Call", id = "gui-TyFy41DsTkg" },
          { text = "[M] Flamendo beam fixate now shoots 3 lasers—dodging requires mobility.", type = "Mechanic", id = "gui-Av6w4zL0L4c" },
          { text = "[M] Make sure Flamendo's beam isn’t pointed at Torq group—3 lasers cover wide area.", type = "Call", id = "gui-2VueiRlUCQ4" },
          { text = "[M] On Torq side, Voltaic Images now drop puddles even if they expire—kill them fast.", type = "Mechanic", id = "gui-6YMI5yDH4" },
        }
      },
      
      ["Rik Reverb"] = {
        id = "enc-liberation-rik-reverb",
        order = 4,
        header = "Boss: Rik Reverb",
        ALL = {
          { text = "TANK: Swap at 4+ Sonic stacks, move Rik after each amp drop.", type = "Call", id = "gui-qpqPSl6PX4" },
          { text = "DPS: Kill adds (barrels) FAST, soak amps if assigned, dodge Echoes.", type = "Call", id = "gui-IleHrtTNic" },
          { text = "HEALER: Heal amp soakers & Intermission, clear Voltage debuffs.", type = "Call", id = "gui-Cm00MnfOkRo" },
          { text = "Move Rik away from Amplifiers to slow their energy gain.", type = "Position", id = "gui-eiN1kZj8p6Y" },
          { text = "Soak Amplifiers at 50+ energy to avoid Haywire.", type = "Call", id = "gui-7uat9doJSSY" },
          { text = "Rotate soakers—taking stacks too fast causes Lingering Voltage damage.", type = "Mechanic", id = "gui-0L52SSqKa2c" },
          { text = "Avoid Sonic circles and Echoes—getting hit twice charms you!", type = "Mechanic", id = "gui-ZTLr7E31Lxc" },
          { text = "Destroy barrels ASAP—more than 1 exploding is deadly.", type = "Call", id = "gui-1AXxTOmN4XU" },
          { text = "Faulty Zap: don’t overlap blue circles—causes raid-wide damage.", type = "Mechanic", id = "gui-6EZZYL86Ssg" },
          { text = "During Echoing Chant, all Amplifiers pulse—extra dodging needed.", type = "Call", id = "gui-NWEQpT7jJvU" },
          { text = "Intermission: stand in glowing blue Amplifier to get launched over the wave.", type = "Mechanic", id = "gui-m0jaTKTMfg" },
          { text = "Move to next Amplifier each knock—use speed boosts as needed.", type = "Call", id = "gui-mvuskAQ1Z2o" },
          { text = "Kill boss before 3rd Intermission or you wipe to Hype Fever.", type = "Call", id = "gui-DBr99ArdoBk" },
          { text = "[M] Amplifiers start shielded—2 Faulty Zap players must collide near them to remove it.", type = "Mechanic", id = "gui-FRlwO1GqOl8" },
          { text = "[M] Shields must be broken ASAP—delay leads to near-100 energy panic soaks.", type = "Call", id = "gui-gdfbZgXlj6E" },
          { text = "[M] Getting hit by 2 Echoes in 6s causes Entranced—nuke charmed player to break effect.", type = "Mechanic", id = "gui-1TmT2636C7k" },
        },
        TANK = {
          { text = "Face Rik away from raid—Sonic Blast is a frontal.", type = "Position", id = "gui-6ij3qsNKeyw" },
          { text = "Tank swap every Sonic Blast—debuff increases damage taken.", type = "Call", id = "gui-pgJgEE2tpA" },
          { text = "After 3rd Amplifier set, move boss far across room to prep intermission space.", type = "Position", id = "gui-RWe7ipDIO9Y" },
          { text = "After intermission, start new phase near leftover Amplifier.", type = "Position", id = "gui-NqNqRqAZvko" },
          { text = "[M] Start baiting Faulty Zap on skull to help line up shield breaks.", type = "Position", id = "gui-EmpsJlIiE" },
        },
        HEALER = {
          { text = "Heavy healing on soakers—especially high-stack or late drains.", type = "Mechanic", id = "gui-vpkliMhK0NY" },
          { text = "Lingering Voltage at 4+ stacks deals heavy ticking damage.", type = "Mechanic", id = "gui-yfiSNeWVN3E" },
          { text = "Raid damage spikes from Haywire and Echoing Chant.", type = "Mechanic", id = "gui-Szl8fLreGwU" },
          { text = "Prep cooldowns for intermission transitions and Sparkblast Ignition.", type = "Call", id = "gui-EdvzehcdTI" },
          { text = "[M] Watch for AoE when Faulty Zap shield breaks—everyone takes damage.", type = "Call", id = "gui-Lx5LS9ouE7g" },
        },
        DPS = {
          { text = "Kill barrels ASAP—don’t let more than 1 explode.", type = "Mechanic", id = "gui-qVnfdhx3CU" },
          { text = "Avoid Sound Cannon and don’t overlap Faulty Zap blue circles.", type = "Mechanic", id = "gui-5TdVYTyuLgg" },
          { text = "Help soak Amplifiers when assigned—use defensives if soaking at high energy.", type = "Call", id = "gui-Po4wrTGd4I" },
          { text = "Stay alert during Echoing Chant—Echoes fire in all directions.", type = "Mechanic", id = "gui-1mQY2qMo2Tc" },
          { text = "[M] Help with Faulty Zap shield breaks—collide near Amplifier to remove.", type = "Call", id = "gui-YcQK3Yyylg" },
          { text = "[M] Stand in Sound Cannon beam to split damage—falling below 75% = Entranced.", type = "Mechanic", id = "gui-X2op8CAQuPc" },
        }
    },

    ["Stix Bunkjunker"] = {
        id = "enc-liberation-stix-bunkjunker",
        order = 5,
        header = "Boss: Stix Bunkjunker",
        ALL = {
          { text = "TANK: Swap on Demolish, use major CD for Meltdown.", type = "Call", id = "gui-oIvtkksjkvc" },
          { text = "DPS: Use ball to collect trash, kill adds, destroy bombs.", type = "Call", id = "gui-d8n3L8b2ew" },
          { text = "HEALER: Heal mine pops, ball drivers & Overdrive AoE.", type = "Call", id = "gui-4spbAx1wwM" },
          { text = "Explosives must be destroyed with Large balls before detonation or it's a wipe.", type = "Call", id = "gui-OaSSmsJ7wqg" },
          { text = "Kill Bombshells fast—do not let them explode or get run over by a ball.", type = "Mechanic", id = "gui-gbBGOZPOVRI" },
          { text = "Spread for Incineration—don’t ignite Garbage Piles.", type = "Position", id = "gui-EjYRvLCvAqg" },
          { text = "Avoid overlapping with large fire circles and Hot Garbage pools.", type = "Mechanic", id = "gui-NlnB2cjDCc" },
          { text = "Dodge all Overdrive blue circles—final slam hits wide area.", type = "Mechanic", id = "gui-TBvhoeBbaI" },
          { text = "During ball phase, pick up adds and garbage—grow the ball before crashing.", type = "Mechanic", id = "gui-qLmKyTtg8Qk" },
          { text = "Assign ball players to fixed markers for optimal garbage pickup routes.", type = "Mechanic", id = "gui-Ei9TlZ6Jdg" },
          { text = "Crash Large balls into Explosives or boss only if safe.", type = "Call", id = "gui-5xHhmPI5muY" },
          { text = "Use CC on Bombshells after 75% HP to group them before killing.", type = "Call", id = "gui-a7rDxRKNnoI" },
          { text = "Stacked Short Fuse debuffs will wipe the raid—do not fail bomb timings.", type = "Call", id = "gui-YtHSvOhliAA" },
          { text = "[M] Balls deal 2% boss damage when max size—clean execution = 30% HP chunk.", type = "Call", id = "gui-7PiPJliSofg" },
          { text = "[M] Do NOT crash into boss sides—only approach from rear to avoid Bombshells.", type = "Mechanic", id = "gui-vPz7GuUWWN4" },
          { text = "[M] If 2 bombs spawn close, both nearby players go—failover strategy for safety.", type = "Call", id = "gui-uJqEcH7q0Cs" },
          { text = "[M] If boss <10%, grow and crash into boss—ignore other mechanics for kill push.", type = "Call", id = "gui-CAAAR4GeW0" },
        },
        TANK = {
          { text = "Swap on Demolish—applies 100% increased damage taken debuff.", type = "Call", id = "gui-YL3wPog4yNA" },
          { text = "Use strong defensives for Meltdown—burst tank damage.", type = "Mechanic", id = "gui-eDJKrMIXng8" },
          { text = "Pick up Bombshells once they reach 75% HP and become mobile.", type = "Call", id = "gui-0tCDKA2JZ88" },
          { text = "Position boss near Bombshell spawn—facilitates cleave and grouping.", type = "Position", id = "gui-6yhogtkpx8w" },
          { text = "[M] Tanks always take same ball marker to start their pickup route.", type = "Call", id = "gui-NSj3REurMw" },
          { text = "[M] Group Bombshells tightly in front of boss—avoid side hits from ball players.", type = "Position", id = "gui-t1Qc9IqRs68" },
        },
        HEALER = {
          { text = "Spot heal Incineration targets—fire splash and Hot Garbage ramp damage fast.", type = "Mechanic", id = "gui-ktK14hQ7LTs" },
          { text = "Prepare raid cooldowns for Overdrive crash impact.", type = "Call", id = "gui-vIk3jdyAFQ" },
          { text = "Watch for Short Fuse stacks if Bombshells explode.", type = "Mechanic", id = "gui-rDLrXUZl43c" },
          { text = "Be ready for spike damage if garbage piles ignite during ball phase.", type = "Call", id = "gui-R2lCvza8zLw" },
          { text = "[M] Players targeted by Prototype Powercoil take ramping damage—watch stack count.", type = "Call", id = "gui-kJnXSds6Rs" },
          { text = "[M] Ball hits near Powercoil beam will knock ball away—warn assigned players.", type = "Mechanic", id = "gui-WHYDWxcy30s" },
        },
        DPS = {
          { text = "Always target Bombshells first—boss damage is secondary.", type = "Mechanic", id = "gui-0Mfinr1AWlM" },
          { text = "Interrupt Scrapmasters to prevent raid-wide damage.", type = "Interrupt", id = "gui-NPTAvwHs3pM" },
          { text = "Avoid igniting Garbage Piles with Incineration—fire puddles cause Toxic Fumes.", type = "Mechanic", id = "gui-ASifHeTnK7Y" },
          { text = "Ball players: collect adds and garbage, avoid crashing into Bombshells.", type = "Call", id = "gui-9VnHLVmChU" },
          { text = "Only crash into boss if no Explosives are active and it’s safe.", type = "Call", id = "gui-1Nxvk8fv7RU" },
          { text = "[M] Grab Hyenas first—they boost ball size fast for early Scrapmaster pickup.", type = "Call", id = "gui-rhHU4VAcj5g" },
          { text = "[M] Use Medium ball to pick up Scrapmaster before 'Recycler' cast finishes.", type = "Interrupt", id = "gui-a20m0u8TeE" },
          { text = "[M] Ball players must crash from behind boss—sides are too risky.", type = "Mechanic", id = "gui-vEXNRafx9s" },
        }
    },

    ["Sprocketmonger Lockenstock"] = {
        id = "enc-liberation-sprocketmonger-lockenstock",
        order = 6,
        header = "Boss: Sprocketmonger Lockenstock",
        ALL = {
          { text = "TANK: Soak 1 mine/set, swap on Gravi-Gunk, run Pyro Pack to end.", type = "Call", id = "gui-e2o5JPMRNcM" },
          { text = "DPS: Interrupt inventions, dodge beam + magnet traps.", type = "Call", id = "gui-SVciFKF06r4" },
          { text = "HEALER: Heal Voidsplosion absorb & intermission swirl overlaps.", type = "Call", id = "gui-lGUfJ6SfFNo" },
          { text = "Soak mines one at a time—never pop two within 2s or it’s a wipe.", type = "Call", id = "gui-15Ofw1GkezM" },
          { text = "Mine soakers must wait 2 mins before soaking again—use assignments.", type = "Mechanic", id = "gui-5m3dyVaLAfg" },
          { text = "Use Warlock Gate for Wire Transfer floor swap after each mine set.", type = "Call", id = "gui-iuX6qiCa89A" },
          { text = "Dodge Rocket Barrage and Void Barrage—they hit hard and splash nearby players.", type = "Mechanic", id = "gui-t0OfbtEBQM" },
          { text = "Avoid Blazing Beam and Jumbo Void Beam—insta-kill if hit.", type = "Mechanic", id = "gui-jm2JSXZxBw" },
          { text = "Move away from Magnets to avoid being stunned and pulled in.", type = "Mechanic", id = "gui-Nn5Z3X7cJEc" },
          { text = "Intermission: get knocked, heal through absorb, dodge swirls, regroup on boss.", type = "Mechanic", id = "gui-0cjDAmCcgw" },
          { text = "Empowered phase: dodge multiple inventions at once—Rockets + Beam.", type = "Mechanic", id = "gui-mW0y3jW8w" },
          { text = "Use speed boosts or gates to help melee avoid death during intermission end.", type = "Call", id = "gui-RAbrufiYdis" },
          { text = "[M] Players receive Positive (blue) or Negative (red) polarity—avoid touching opposite colours.", type = "Mechanic", id = "gui-AR26ez4GQXI" },
          { text = "[M] Touching opposite polarity knocks you and applies lethal DoT—maintain positioning.", type = "Call", id = "gui-X1rAe4JUroc" },
          { text = "[M] Mines also have colours—only pop mines matching your polarity.", type = "Mechanic", id = "gui-SO5HyQuARcM" },
          { text = "[M] If invention hits a mine, it explodes instantly—pop mines quickly.", type = "Call", id = "gui-lmw17SwRQ0" },
          { text = "[M] During knock phases, stand in exact position based on polarity or get knocked off.", type = "Mechanic", id = "gui-JpP6idiCsEo" },
          { text = "[M] Red team: stand behind boss and spam gate on knock. Blue: get knocked to belt lanes.", type = "Position", id = "gui-wswQlXr7Hw" },
          { text = "[M] Final knock swaps colours—assign teams in advance for second intermission.", type = "Mechanic", id = "gui-Y8jzOIW1oL0" },
        },
        TANK = {
          { text = "Swap on Gravi-Gunk—stacks increase damage taken and slow movement.", type = "Mechanic", id = "gui-xQ8FF5ktPmU" },
          { text = "Run Pyro Party Pack to edge—explosion is distance-based.", type = "Mechanic", id = "gui-yEHtM6YL2yI" },
          { text = "Avoid standing in mine zones when dropping Party Pack or dealing with Drill.", type = "Position", id = "gui-Bj4WPUXccsg" },
          { text = "Start mines closest to wall—clear safe zones for ranged next.", type = "Call", id = "gui-RUJjBWmfILo" },
          { text = "[M] Tanks must be prepared to reposition quickly if they don't match colour swap.", type = "Call", id = "gui-DRRRXjwQcA8" },
          { text = "[M] Allow space for colour-correct tanks to move boss safely during swap.", type = "Position", id = "gui-IuNMNvMhozU" },
        },
        HEALER = {
          { text = "Heavy healing on Sonic Ba-Boom—10s raid-wide pulse damage.", type = "Mechanic", id = "gui-ufdB4X5kxg" },
          { text = "Top players after Magnet stuns and Drill hits—they apply bleeds.", type = "Mechanic", id = "gui-i0zMcuvaNAg" },
          { text = "During intermission, focus healing through raid-wide absorb from Voidsplosion.", type = "Mechanic", id = "gui-6wmAhG10As" },
          { text = "Prep cooldowns after 2nd intermission—Void Rockets and Jumbo Beam overlap.", type = "Call", id = "gui-juoeJgd8BBA" },
          { text = "[M] Assign mobile healers to pop far mines based on polarity match.", type = "Mechanic", id = "gui-8ZdkBFV9UbE" },
          { text = "[M] Coordinate barrier and healing CDs during polarity knock & colour swap overlaps.", type = "Call", id = "gui-iknTLIfUJIY" },
        },
        DPS = {
          { text = "Dodge Screw Up drill lines—stun + bleed if hit.", type = "Mechanic", id = "gui-24IUqWCr7ZE" },
          { text = "Stay out of Blisterizer traps—slow, knockup, and DoT effect.", type = "Mechanic", id = "gui-eLtOlhFa4uI" },
          { text = "Use personal movement cooldowns during floor electrification swaps.", type = "Call", id = "gui-Xk93M3r3wDc" },
          { text = "If assigned to soak mines, wait for debuff to expire before popping yours.", type = "Mechanic", id = "gui-efZiF42lik" },
          { text = "Focus boss after 2nd intermission—burn phase begins.", type = "Call", id = "gui-bsIHU5GlZgA" },
          { text = "[M] Ranged: bait drills and pop far mines with correct colour.", type = "Call", id = "gui-y2lnLTgsz8I" },
          { text = "[M] Players with immunities should intercept Void Rockets in tight overlaps.", type = "Mechanic", id = "gui-VsQXfCDMKIA" },
          { text = "[M] All DPS stop damage and focus dodging during final empowered inventions.", type = "Call", id = "gui-157faJ3WsE" },
        }
    },

    ["The One-Armed Bandit"] = {
        id = "enc-liberation-the-one-armed-bandit",
        order = 7,
        header = "Boss: The One-Armed Bandit",
        ALL = {
          { text = "TANK: Swap on Big Hit, use Coil to clear puddles, position carefully.", type = "Call", id = "gui-XON5LtGwi0" },
          { text = "DPS: Kill correct Reel Assistants & insert coins within 30s.", type = "Call", id = "gui-fZYP6N0XTM" },
          { text = "HEALER: Dispel Flames, heal absorbs fast, prep for combo AoE.", type = "Call", id = "gui-SG0RUFz3Ivs" },
          { text = "Kill 2 specific Reel Assistants, insert their coins within 30s to avoid wipe.", type = "Call", id = "gui-GxRV08z0wZQ" },
          { text = "Reel Assistants cast Overload!—interrupt all 3 or raid takes heavy damage.", type = "Interrupt", id = "gui-qvp1KkW5SIk" },
          { text = "Stand near Pay-Line for a DPS/healing buff, but don’t get hit by the coin.", type = "Position", id = "gui-z5SKkFMcBQo" },
          { text = "Players can click Pay-Line coins on the ground to launch and remove boss damage buff.", type = "Mechanic", id = "gui-nY63Fn2c35Y" },
          { text = "Avoid repeating coin combos—activates Fraud Detection and wipes raid.", type = "Call", id = "gui-iXxOO3HGTs" },
          { text = "Fire swirls, laser beams, and coin paths must be dodged throughout.", type = "Mechanic", id = "gui-PvtQKSp9070" },
          { text = "Prepare to swap to Phase 2 at 30% boss HP or after all combos used.", type = "Call", id = "gui-cXtFdNw6Zxg" },
          { text = "Phase 2: Avoid knockbacks, dodge boss-tethered beam, and burn hard to beat bomb enrage.", type = "Mechanic", id = "gui-zv5xr7vFYaY" },
          { text = "Phase 2 Combo Order: Shock > Fire > Coin > Bomb (Wipe).", type = "Call", id = "gui-uPZjpjvt50" },
        },
        TANK = {
          { text = "Big Hit leaves puddle and applies 350% damage debuff—tank swap required.", type = "Call", id = "gui-GLUxQwUNBA" },
          { text = "Drop puddles near edges—keep center clear for movement.", type = "Position", id = "gui-PAHy8SabJak" },
          { text = "Use Coil to clear 2 nearby puddles when 3+ are active—watch for fire when triggering.", type = "Mechanic", id = "gui-RXnRrSQ6Mw" },
          { text = "In Phase 2, avoid moving boss through tether beam during Shock Combo.", type = "Mechanic", id = "gui-hR4W4U587Gg" },
        },
        HEALER = {
          { text = "Dispel Withering Flames—targeted player takes damage and must move away first.", type = "Mechanic", id = "gui-kU83ZCwf9A" },
          { text = "Foul Exhaust applies absorb + ticking DoT on all players—topping everyone quickly.", type = "Call", id = "gui-l459fuDYa4" },
          { text = "Scattered Payout during Coin Combo = massive AoE, defensives needed.", type = "Call", id = "gui-HxUkWAoCOHM" },
          { text = "Prepare CDs for pulsing raid-wide damage in Phase 2.", type = "Call", id = "gui-MtKGRomCxMY" },
        },
        DPS = {
          { text = "Kill 2 marked Reel Assistants fast—ignore the third or cleave lightly.", type = "Mechanic", id = "gui-hsx2xgvIM3E" },
          { text = "Kite and kill bomb adds before they reach raid members.", type = "Mechanic", id = "gui-9NQBCsoLyFA" },
          { text = "Pick up dropped coins immediately and use extra action button to insert.", type = "Call", id = "gui-dMeFdH090" },
          { text = "Interact with ground coins to remove boss damage buff stack (Up the Ante).", type = "Mechanic", id = "gui-Ch8OBIyUqU" },
          { text = "In Phase 2, dodge targeted fire laser (Hot Hot Heat) and stay clear of others.", type = "Mechanic", id = "gui-BJ6PEG3t3C8" },
        }
    },
    
    ["Mug'Zee, Heads of Security"] = {
        id = "enc-liberation-mugzee-heads-of-security",
        order = 8,
        header = "Boss: Mug'Zee, Heads of Security",
        ALL = {
          { text = "TANK: Soak Whammy Shot, clear Gold stacks, avoid frontal overlaps.", type = "Call", id = "gui-S9TooT8CG8" },
          { text = "DPS: Pop mines 1-by-1, kill Goons & soak Rocket without debuff.", type = "Call", id = "gui-YpNvZNKLmSE" },
          { text = "HEALER: Heal mine pops & prisons, rotate CDs in final phase.", type = "Call", id = "gui-M6fbBrJjcKM" },
          { text = "Swap sides before 100 energy to reset Moxie stacks and avoid enrage.", type = "Call", id = "gui-2uqeCBmP5E" },
          { text = "Split raid for Earthshaker Gaol prisons and soak both circles.", type = "Mechanic", id = "gui-KDef13Vr5U" },
          { text = "Stand behind stone wall if targeted by Frostshatter Boots to avoid freeze.", type = "Call", id = "gui-ZIwgtudFRIE" },
          { text = "Players fixated by Stormfury Finger Gun must stand alone and soak it.", type = "Call", id = "gui-ykcbb3t0gvI" },
          { text = "Assigned mine soakers must pop one mine at a time and soak 2 circles.", type = "Mechanic", id = "gui-5fMRUfyvUTM" },
          { text = "Don’t step on mines or pop unassigned—leads to raid wipe via absorb overload.", type = "Call", id = "gui-LyXQdo8jyrQ" },
          { text = "Soak Goblin-guided Rocket with 5 assigned players, avoid debuffed players.", type = "Call", id = "gui-5Jj441ho28" },
          { text = "Volunteer Rocketeer must be killed quickly after Rocket soak.", type = "Mechanic", id = "gui-Bc8FrFcp4C4" },
          { text = "Avoid Spray and Pray frontal cone—move away if targeted.", type = "Mechanic", id = "gui-ClOWgPfXGzg" },
          { text = "Avoid Disintegration Beam and static charge cones during intermission.", type = "Mechanic", id = "gui-2opjZlExE" },
          { text = "In Phase 2, all Phase 1 abilities are active—play each correctly by position.", type = "Call", id = "gui-xVDbDzaMUGc" },
          { text = "Use CC on mines in final phase—do not pop them.", type = "Call", id = "gui-abD3QJhkqZg" },
          { text = "Kill before boss reaches 100 energy in Phase 2.", type = "Call", id = "gui-ILMOBTCFLw" },
        },
        TANK = {
          { text = "Swap on Molten Gold Knuckles—remove stacks by moving and dropping puddles.", type = "Mechanic", id = "gui-lp8TV9D1liM" },
          { text = "Intercept Double Whammy Shot to reduce damage on targeted player.", type = "Interrupt", id = "gui-VMvLoOcij8" },
          { text = "Face boss away from raid to prevent frontal overlaps with prisons and fixates.", type = "Position", id = "gui-kn6bCbLPIOM" },
          { text = "In Phase 2, intercept beam and position boss near Skull then Cross markers.", type = "Position", id = "gui-jo74uGv16Y" },
        },
        HEALER = {
          { text = "Assign 1 healer to stay outside prison to keep tanks alive.", type = "Mechanic", id = "gui-Xpon3J0tTb0" },
          { text = "Heavy healing after mine pops—raid-wide absorb must be cleared before next.", type = "Mechanic", id = "gui-ZGkABhtwOlA" },
          { text = "Prepare cooldowns for Rocket soaks and final prison phase overlaps.", type = "Call", id = "gui-hwO70lrNjuo" },
          { text = "Heal Frostshatter Boots players and be ready for Disintegration Beam ramps.", type = "Mechanic", id = "gui-ADQ0o6RrufI" },
        },
        DPS = {
          { text = "Kill Goon adds in prisons quickly to break allies free.", type = "Mechanic", id = "gui-sNmmi5ADBlo" },
          { text = "Burn MK2 Electro Shocker when stunned at 80% HP—take advantage of damage amp.", type = "Mechanic", id = "gui-sV2Zt6PiOPA" },
          { text = "Drop Rocket soaks at assigned markers (Skull/Red) and soak with correct group.", type = "Call", id = "gui-htM2hLpPndc" },
          { text = "Avoid cleaving mines, keep fixated players alive, and don't cross unsoaked mines.", type = "Mechanic", id = "gui-Cn0CvLQWk" },
          { text = "During Intermission, avoid getting knocked into walls or mines.", type = "Mechanic", id = "gui-hpq4XrPqX8c" },
        }
    },
    
    ["Chrome King Gallywix"] = {
        id = "enc-liberation-chrome-king-gallywix",
        order = 9,
        header = "Boss: Chrome King Gallywix",
        ALL = {
          { text = "TANK: Rotate Scatterblasts, disarm Duds, use CD for Bomb Blast.", type = "Call", id = "gui-ulST7KmpRo" },
          { text = "DPS: Interrupt Techs, deliver bomb to Coil fast, soak Tick-Tocks.", type = "Call", id = "gui-oQwjPdCMbjM" },
          { text = "HEALER: Heal absorb soaks fast, burn shield, prep for Finale Blast.", type = "Call", id = "gui-GoV55Kjx6Fw" },
          { text = "Split raid into 2 groups to rotate Scatterblast Canister soaks.", type = "Call", id = "gui-2YoDsOBytEw" },
          { text = "Healers must top players with absorb before 15s or they explode.", type = "Mechanic", id = "gui-TS8sMqlnY" },
          { text = "Dodge swirls, satchels, fireworks, and beams constantly.", type = "Mechanic", id = "gui-oAZuNEQXBQ8" },
          { text = "Big Bad Buncha Bombs = bait away, then move fast to avoid detonation.", type = "Call", id = "gui-laJrD21AemY" },
          { text = "At 100 energy: kill Technicians, pick up bombs, and interrupt Coil.", type = "Call", id = "gui-ZYoBrg0wn8" },
          { text = "Throw leftover bombs into hole or off platform to prevent wipe.", type = "Mechanic", id = "gui-l3EzQt6MQ" },
          { text = "During intermission, kite adds, interrupt Juice It!, and dodge laser beam (rotate right).", type = "Call", id = "gui-OUFoyesddzs" },
          { text = "Soak Tick-Tock Canisters in groups of 4 to prevent absorb on entire raid.", type = "Mechanic", id = "gui-1331cFfBQE" },
          { text = "Use same groups to soak Fused Canisters throughout Phase 2.", type = "Call", id = "gui-k4K1HD4JVwQ" },
          { text = "Phase 3: Interrupt TOTAL DESTRUCTION!!! once shield is broken.", type = "Call", id = "gui-rCJmmW1QT88" },
          { text = "Avoid rotating electric beams in P3—stun + lethal damage if hit.", type = "Mechanic", id = "gui-Eh0ElPcCsM" },
          { text = "Stand far away during Gallybux Finale Blast—damage falloff reduces risk.", type = "Mechanic", id = "gui-ZLtmpZSy5E" },
          { text = "Avoid Overloaded Rockets lines—spread safely away from raid.", type = "Mechanic", id = "gui-N5uAMF2cFQc" },
        },
        TANK = {
          { text = "Face Scatterblast away from raid—split hit with assigned soakers.", type = "Position", id = "gui-mnSpUrXLyEk" },
          { text = "Disarm 1500-Pound Duds (big bombs)—knockback + raid hit after DoT ends.", type = "Mechanic", id = "gui-UAcR9DzaWVc" },
          { text = "Avoid Trick Shots stacks—tank swap to drop stacks regularly.", type = "Mechanic", id = "gui-difwtoqRCl4" },
          { text = "During Giga Coil phase, stand near boss for Gatling Cannon to reduce damage.", type = "Position", id = "gui-wVHWsFkI7c" },
          { text = "During Bigger Badder Bomb Blast, run out with frontal and pop strong defensive.", type = "Mechanic", id = "gui-kPL3mzdIVY" },
        },
        HEALER = {
          { text = "Rotate CDs for each Scatterblast soak—6 total (3 per group).", type = "Call", id = "gui-iKwaHkKw4d0" },
          { text = "Healers must remove all absorbs before 15s—explosion scales with leftover absorb.", type = "Mechanic", id = "gui-QHqdbDGQjO4" },
          { text = "Top group after Fused Canister soaks—massive AoE absorb.", type = "Mechanic", id = "gui-dXm5eXI1I0" },
          { text = "Prepare burst healing during Juice It! and P2 intermission coil delay.", type = "Mechanic", id = "gui-EM3mXlbdd7g" },
          { text = "Heavy healing needed during TOTAL DESTRUCTION!!! cast—interrupted after shield.", type = "Mechanic", id = "gui-N54tmbCTlAQ" },
        },
        DPS = {
          { text = "Kill Technicians during intermissions fast—interrupt Juice It!", type = "Mechanic", id = "gui-0258erL4rrA" },
          { text = "Pick up Charged Giga Bombs and deliver to active Coil ASAP.", type = "Call", id = "gui-UVkGhLjuqFs" },
          { text = "Avoid detonating bombs with Giga Blast—clear platform carefully.", type = "Mechanic", id = "gui-NUjpkE24ZZE" },
          { text = "Soak Tick-Tock Canisters and Fused Canisters as assigned.", type = "Call", id = "gui-jenCewkxLF0" },
          { text = "During Overloaded Rockets, stand still in safe direction and avoid hitting others.", type = "Mechanic", id = "gui-Grej4aLM3eo" },
          { text = "Burn shield quickly at 50% HP—interrupt before TOTAL DESTRUCTION!!! completes.", type = "Mechanic", id = "gui-YsFwLP4aEN4" },
        }
    }      
}