DungeonGuide_Guides["Operation: Mechagon"] = {
  id = "dung-mechagon",
  ["Operation: Mechagon"] = {
    id = "enc-mechagon-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "Interrupts: Detonate (Bomb Tonk), Mega Drill, Giga-Wallop, Tune Up, Short Out.", type = "Interrupt", id = "gui-XX9qYToKY7k" },
      { order = 2, role = "ALL", text = "Dodge beams, mines, and swirls constantly - movement awareness is key.", type = "Mechanic", id = "gui-IyiSc424rZ0" },
      { order = 3, role = "ALL", text = "Use Hammer Pads only to break Platinum Plating - not for damage.", type = "Mechanic", id = "gui-amnC0kSEvE" },
      { order = 4, role = "ALL", text = "Junk Cubes (K.U.-J.0) = Venting Flames safety. Avoid glowing cubes.", type = "Mechanic", id = "gui-t9O30HvZTUc" },
      { order = 5, role = "ALL", text = "Post-2nd boss trash = burst AoE + healing absorbs. Coordinate CDs + kicks.", type = "Mechanic", id = "gui-jcf30VcH2AA" },
      { order = 6, role = "ALL", text = "Maze before Sparkflux is stealth only - use vents to reset. No CC.", type = "Mechanic", id = "gui-RkAFQ3fua70" },
      { order = 7, role = "ALL", text = "Shield Generators reduce damage by 75%. Pull mobs out or stand inside for safety.", type = "Mechanic", id = "gui-Eea2N18HbxM" },
      { order = 8, role = "ALL", text = "Avoid saw blades and piston hammers in first room.", type = "Mechanic", id = "gui-vA2o7qBCrBc" },
      { order = 9, role = "ALL", text = "Trash danger: Mega Drill (Waste Unit), Corrosive Gunk, Short Out (Bot Mk III).", type = "Mechanic", id = "gui-YAJ8NxCsKIA" },
      { order = 10, role = "ALL", text = "Stand behind crate during Venting Flames (K.U.-J.0) - glowing = lethal.", type = "Mechanic", id = "gui-MBJI1X9l65I" },
      { order = 11, role = "TANK", text = "Many mobs are CC-immune. Kite with positioning if bleeds/DoTs stack.", type = "Mechanic", id = "gui-h1Dog86gM" },
      { order = 12, role = "TANK", text = "Stay in melee on King Mechagon or trigger Protocol: 99 (wipe).", type = "Mechanic", id = "gui-0hwJDE6OQ4" },
      { order = 13, role = "TANK", text = "Avoid pulling trash through hammers or saw blades in Tussle room.", type = "Mechanic", id = "gui-C8M1tfqfaNA" },
      { order = 14, role = "TANK", text = "Pull trash mobs out of Shield Generator fields unless party benefits.", type = "Mechanic", id = "gui-22f7v3VAnms" },
      { order = 15, role = "TANK", text = "Interrupt or position Giga-Wallop (Tinkerer) + Metallic Jaws mobs safely.", type = "Mechanic", id = "gui-ZTu9wvZtGY" },
      { order = 16, role = "HEALER", text = "Big healing: Ground Pound, Mega Drill, Venting Flames, Magneto Arm.", type = "Mechanic", id = "gui-wQsuVmJ6zM" },
      { order = 17, role = "HEALER", text = "Dispel: Blazing Chomp (Tank), Fiery Jaws (Random), Arcing Zap (Trash). Delay Chomp if group is low.", type = "Mechanic", id = "gui-ogvlxWuwtoI" },
      { order = 18, role = "DPS", text = "Plan CDs for burn windows: Sparkflux plants + Mechagon phase change.", type = "Mechanic", id = "gui-NAbPndFfSq8" },
      { order = 19, role = "DPS", text = "Stun Sparkflux adds till tank picks them up. Kick heals, avoid empower.", type = "Mechanic", id = "gui-u3OohaRktg" }
    },
  },

  ["Route"] = {
    id = "enc-mechagon-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "Start pulling right side in first boss room. Safer Bomb Tonk control.", type = "Mechanic", id = "gui-q191ICSTRC4" },
      { order = 2, role = "ALL", text = "Left side second. Then south side of room. Clear full room for boss.", type = "Mechanic", id = "gui-cesGuK4aqKo" },
      { order = 3, role = "ALL", text = "Keep pulls under 3 Bomb Tonks per pull on higher keys.", type = "Mechanic", id = "gui-nlYP4kUqs4" },
      { order = 4, role = "ALL", text = "Watch Rocket Tonk swirlies and Strider Tonk leaps.", type = "Mechanic", id = "gui-rm6kaGZBDA8" },
      { order = 5, role = "ALL", text = "Boss Fight: Tussle Tonks", type = "Jump", target="Tussle Tonks", id = "gui-LWEv1i0CMw" },
      { order = 6, role = "ALL", text = "After Tussle Tonks, pull single Waste Processing Unit solo.", type = "Call", id = "gui-dPYQyrU89IQ" },
      { order = 7, role = "ALL", text = "LOS Metal Gunk healing absorbs when possible.", type = "Mechanic", id = "gui-j6i3yBoUgwU" },
      { order = 8, role = "ALL", text = "Chain Metal Gunks into each other carefully. Watch stacking absorbs.", type = "Call", id = "gui-fIzYVJUNi58" },
      { order = 9, role = "ALL", text = "Skip patrolling Waste Processing Unit if safe near pool.", type = "Call", id = "gui-7tyPuXxDFIg" },
      { order = 10, role = "ALL", text = "Clear Junkyard Dogs carefully. Their DoT is brutal without dispels.", type = "Mechanic", id = "gui-j96UyFJqzGE" },
      { order = 11, role = "ALL", text = "Pull Junkyard Dogs solo or small for K.U.-J.O. boss space.", type = "Call", id = "gui-Cdc2FXUUDxA" },
      { order = 12, role = "ALL", text = "Boss Fight: K.U.-J.0", type = "Jump", target="K.U.-J.0", id = "gui-Y895gtqrVk" },
      { order = 13, role = "ALL", text = "After K.U.-J.O., walk conveyor belt. Warlock Gate saves time if available.", type = "Mechanic", id = "gui-HPqKrr7xhI" },
      { order = 14, role = "ALL", text = "Next pull: 2x Mechagon Tinkerers + 2x Guard Dogs.", type = "Call", id = "gui-25FlsRJ2ICQ" },
      { order = 15, role = "ALL", text = "Next Defense Spot pulls: 2x Mark I + 1x Mark II units.", type = "Call", id = "gui-m9YeNCqJs" },
      { order = 16, role = "ALL", text = "Focus Mark I units first to relieve healer pressure.", type = "Mechanic", id = "gui-abfcQWJIXrE" },
      { order = 17, role = "ALL", text = "Fight Blastron X80 stationary. Dodge all telegraphed attacks.", type = "Mechanic", id = "gui-MimSpFWtdk" },
      { order = 18, role = "ALL", text = "Pull Mechanics + Defenders next. Focus Defense Spot interrupts.", type = "Call", id = "gui-DTbEy87vOc" },
      { order = 19, role = "ALL", text = "Defender Barriers are safe zones. Use them for Squirrel explosions.", type = "Mechanic", id = "gui-qPxEAJzs0c" },
      { order = 20, role = "ALL", text = "Boss Fight: Head Machinist Sparkflux", type = "Jump", target="Head Machinist Sparkflux", id = "gui-yYWGd3NC82c" },
      { order = 21, role = "ALL", text = "After Sparkflux, fight Spider Tanks. Single pull unless healer strong.", type = "Call", id = "gui-0YgJOdtt9xg" },
      { order = 22, role = "ALL", text = "Focus top Spider Tank first - it spawns Taxi to next section.", type = "Call", id = "gui-tXs23sS8T4U" },
      { order = 23, role = "ALL", text = "Pull Defenders + Tinkerers into final Defense Spots. Use Barrier.", type = "Call", id = "gui-4aBu1vxomh4" },
      { order = 24, role = "ALL", text = "Expect slight overcount (103-109%) by end. No big deal.", type = "Mechanic", id = "gui-uyJh99ZM" },
      { order = 25, role = "ALL", text = "Boss Fight: King Mechagon", type = "Jump", target="King Mechagon", id = "gui-8DGOk3z0jH8" }
    },
  },  

  ["Tussle Tonks"] = {
    id = "enc-mechagon-tussle-tonks",
    order = 3,
    header = "Boss: Tussle Tonks",
    entries = {
      { order = 1, role = "ALL", text = "Keep bosses close in HP - Electrical Storm if 1 dies early.", type = "Mechanic", id = "gui-PNoNbpCJXGM" },
      { order = 2, role = "ALL", text = "Battle Mines active - stack and rotate zones cleanly.", type = "Call", id = "gui-Io2ceilWzSo" },
      { order = 3, role = "ALL", text = "Faux Flipper incoming - dodge knock into mines.", type = "Call", id = "gui-LMESHFjAj4" },
      { order = 4, role = "TANK", text = "Face Pummeler away - cleave hits in 6yd cone.", type = "Position", id = "gui-FMiROJVUtI" },
      { order = 5, role = "TANK", text = "Drag boss into Hammer at 100 energy to remove Plating.", type = "Mechanic", id = "gui-EnuMscTu8fg" },
      { order = 6, role = "TANK", text = "Rotate to next Hammer - each goes on 90s cooldown.", type = "Mechanic", id = "gui-RbtdlM9AVM" },
      { order = 7, role = "TANK", text = "Bait Maximum Thrust into wall for cleave uptime.", type = "Mechanic", id = "gui-NJsJ9wxlecc" },
      { order = 8, role = "TANK", text = "Don't move during Pummel cast - keep positioning clean.", type = "Mechanic", id = "gui-V1W6DbdVbsc" },
      { order = 9, role = "TANK", text = "Keep both bosses close - enables cleave and hammer use.", type = "Position", id = "gui-v4nTwJJsmro" },
      { order = 10, role = "TANK", text = "Balance boss HP - must die together to avoid wipe.", type = "Call", id = "gui-DBPoxYBRiA" },
      { order = 11, role = "HEALER", text = "CDs for Ground Pound - 4s group-wide AoE.", type = "Call", id = "gui-tprZjqX4OvE" },
      { order = 12, role = "HEALER", text = "Top up Faux Flipper targets quickly.", type = "Mechanic", id = "gui-vNH7Zrzn7YQ" },
      { order = 13, role = "DPS", text = "Even cleave both bosses - split deaths = wipe.", type = "Mechanic", id = "gui-H69rSJJ9YIM" },
      { order = 14, role = "DPS", text = "Stack mines safely. Rotate placement zones.", type = "Mechanic", id = "gui-3WJzmPeRL6s" }
    },
  },
  
  ["K.U.-J.0"] = {
    id = "enc-mechagon-kuj0",
    order = 4,
    header = "Boss: K.U.-J.0",
    entries = {
      { order = 1, role = "ALL", text = "Avoid glowing Junk Cubes - 2nd hit = lethal explosion.", type = "Mechanic", id = "gui-xP91j9Eyuf8" },
      { order = 2, role = "ALL", text = "Explosive Leap - spread and avoid cubes.", type = "Call", id = "gui-Tu9s8VvlAY" },
      { order = 3, role = "ALL", text = "Venting Flames - hide behind safe cube.", type = "Call", id = "gui-mBimUdXam2g" },
      { order = 4, role = "TANK", text = "Use defensive for Blazing Chomp - heavy ticking Magic DoT.", type = "Mechanic", id = "gui-mAg8b70a2pI" },
      { order = 5, role = "TANK", text = "Hold near cube before Venting Flames - ensure LoS spot.", type = "Position", id = "gui-lSUzkVsgzZs" },
      { order = 6, role = "TANK", text = "Avoid standing near cubes during Explosive Leap.", type = "Mechanic", id = "gui-Y4XxYtAFt70" },
      { order = 7, role = "TANK", text = "Tiptoe boss near crate to allow DPS to stay in range.", type = "Position", id = "gui-umJMfcTw3Y4" },
      { order = 8, role = "HEALER", text = "Dispel Blazing Chomp (TANK) after topping group.", type = "Mechanic", id = "gui-cxJgq1CkpI" },
      { order = 9, role = "HEALER", text = "Heal through Leap + DoT overlap.", type = "Mechanic", id = "gui-hdUQQivmWFA" },
      { order = 10, role = "DPS", text = "Spread wide on Leap cast. Don't heat cubes early.", type = "Mechanic", id = "gui-my77wStWKXg" },
      { order = 11, role = "DPS", text = "Save cubes for future LoS - they don't respawn fast.", type = "Mechanic", id = "gui-cBD1qVvxdw" },
      { order = 12, role = "DPS", text = "Use vanish/shadowmeld to cancel Leap if targeted.", type = "Mechanic", id = "gui-EiICTDm2goQ" }
    },
  },
  
  ["Head Machinist Sparkflux"] = {
    id = "enc-mechagon-sparkflux",
    order = 5,
    header = "Boss: Head Machinist Sparkflux",
    entries = {
      { order = 1, role = "ALL", text = "Avoid Self-Trimming Hedge blades - bounce randomly.", type = "Mechanic", id = "gui-sqTSMXtKmyM" },
      { order = 2, role = "ALL", text = "Hidden Flame Cannon - rotate with group.", type = "Call", id = "gui-K0w4t6KSQI" },
      { order = 3, role = "ALL", text = "Discombobulator on me - moving out of AoE.", type = "Call", id = "gui-k5RQtGXMwYU" },
      { order = 4, role = "ALL", text = "Plant spawned - burn Inconspicuous Plant fast.", type = "Call", id = "gui-AjWSQ48kkA" },
      { order = 5, role = "TANK", text = "Tank boss near plant spawn for cleave.", type = "Position", id = "gui-rLMpmUMpej4" },
      { order = 6, role = "TANK", text = "Drag boss off Platinum Plating quickly.", type = "Mechanic", id = "gui-4Sxselqlrg" },
      { order = 7, role = "TANK", text = "Dodge blade bounces from Self-Trimming Hedge.", type = "Mechanic", id = "gui-KOOdYCAtIYk" },
      { order = 8, role = "TANK", text = "Discombobulator fixate on you - move boss early.", type = "Mechanic", id = "gui-aqQSVDtkTOs" },
      { order = 9, role = "HEALER", text = "CDs if Cannon + Blossom Blast overlap.", type = "Call", id = "gui-BAKjZYo6FUw" },
      { order = 10, role = "HEALER", text = "Dispel Arcing Zap magic DoTs quickly.", type = "Mechanic", id = "gui-8tNAVRHyxHQ" },
      { order = 11, role = "DPS", text = "Kill Plant fast - avoid ramp-up.", type = "Mechanic", id = "gui-lm5TVZxcx0g" },
      { order = 12, role = "DPS", text = "Dodge blades and oil swirls after plant dies.", type = "Mechanic", id = "gui-h3l8Q5UHQ0" }
    },
  },

  ["The Maze"] = {
    id = "enc-mechagon-maze",
    order = 6,
    header = "Maze: Stealth Section",
    entries = {
      { order = 1, role = "ALL", text = "Do not use CC or offensive spells - will break stealth instantly.", type = "Mechanic", id = "gui-kt9Wc9obDE" },
      { order = 2, role = "ALL", text = "Hug left wall on first patrol, wait for it to pass before moving.", type = "Mechanic", id = "gui-Az80c8TsL0c" },
      { order = 3, role = "ALL", text = "Vents can reset patrol aggro. Use to save stealth fails.", type = "Mechanic", id = "gui-0VJOgrzQSTg" },
      { order = 4, role = "ALL", text = "Second room: Wait for patrol near console to turn away, then move.", type = "Mechanic", id = "gui-leHTjsP4new" },
      { order = 5, role = "ALL", text = "Final stretch has overlapping patrols. Time your cross with both out of view.", type = "Mechanic", id = "gui-MoKDQXdeeL0" }
    },
  },
 
  ["King Mechagon"] = {
    id = "enc-mechagon-king-mechagon",
    order = 7,
    header = "Boss: King Mechagon",
    entries = {
      { order = 1, role = "ALL", text = "Recalibrate orbs - dodge across safely.", type = "Call", id = "gui-JS4slfiI7bc" },
      { order = 2, role = "ALL", text = "Mega Zap on me - standing still and using CD.", type = "Call", id = "gui-9gPNRQtVLDU" },
      { order = 3, role = "TANK", text = "Stay in melee - triggers Protocol: 99 if too far.", type = "Mechanic", id = "gui-2nGXq64Jgz8" },
      { order = 4, role = "TANK", text = "Back to wall if using movement abilities (The Hunt etc.).", type = "Position", id = "gui-edQb8hRcQMM" },
      { order = 5, role = "TANK", text = "Start at left pylon. Coordinate safe pathing early.", type = "Call", id = "gui-507f7VR4258" },
      { order = 6, role = "TANK", text = "CD if Giga-Wallop hits while bots are active.", type = "Mechanic", id = "gui-p8p9czMWHI" },
      { order = 7, role = "TANK", text = "Move boss to edge after Shockwave clears.", type = "Position", id = "gui-fBfwF9qWGas" },
      { order = 8, role = "TANK", text = "Interrupt Tune Up / Giga-Wallop if mechanic survives.", type = "Interrupt", id = "gui-71XSd2CByzM" },
      { order = 9, role = "TANK", text = "Avoid Shockwave + bot overlap - adjust position.", type = "Mechanic", id = "gui-cEknKjkWBs" },
      { order = 10, role = "HEALER", text = "Prep CDs for Cutting Beam or Magneto Arm.", type = "Call", id = "gui-92wchx6cxGA" },
      { order = 11, role = "HEALER", text = "Dispel Arc Zap + Overclock buffs in Phase 1.", type = "Mechanic", id = "gui-Pq1aDox9foU" },
      { order = 12, role = "DPS", text = "Dodge Mega Zap + Plasma Orbs - 3x zap in Phase 2.", type = "Mechanic", id = "gui-J1Papqg12Ks" },
      { order = 13, role = "DPS", text = "Run out hard during Magneto Arm pull.", type = "Mechanic", id = "gui-rgUaUAnDwA" }
    },
  }
}
