DungeonGuide_Guides["The MOTHERLODE!!"] = {
  id = "dung-motherlode",
  ["The MOTHERLODE!!"] = {
    id = "enc-motherlode-guide",
    order = 1,
    header = "Intro",
    entries = {
      { role = "ALL", text = "39-min timer. Route favours skipping early trash with Peacekeepers.", type = "Mechanic", id = "gui-cbJeACJ9Scw" },
      { role = "ALL", text = "Kick: Toxic Blades, Rock Lance, Goo, Withering Discharge, Rapid Extraction.", type = "Interrupt", id = "gui-a1DXQWQcAQM" },
      { role = "ALL", text = "Stop Mech Jockeys reaching suits — Peacekeepers are deadly.", type = "Mechanic", id = "gui-Efeeb5v916c" },
      { role = "ALL", text = "Peacekeeper Charged Shield: move boss, pop group CDs.", type = "Mechanic", id = "gui-m3Z1dgxn6Bs" },
      { role = "ALL", text = "Empowered Earthragers = priority kill. Swap fast.", type = "Mechanic", id = "gui-BU6BAzmYa8" },
      { role = "ALL", text = "Mines fixate — kite or stun. Huge AoE if touched.", type = "Mechanic", id = "gui-l5t2lTmqKQ" },
      { role = "ALL", text = "Boom Bots = missile warnings. Move to safe zone.", type = "Mechanic", id = "gui-90ogiZHdbA" },
      { role = "ALL", text = "Big AoE: Rapid Extraction, Charged Shot, Static Pulse, Quake, Drill Smash, adds.", type = "Mechanic", id = "gui-0SqogoQgbA" },
      { role = "TANK", text = "Stacking bleeds: Heavy Slash, Jagged Cut, Puncture. Kite or CD.", type = "Mechanic", id = "gui-BOCBaeyi1d8" },
      { role = "TANK", text = "Rixxa/Razdunk don’t auto-attack — use magic mitigation.", type = "Mechanic", id = "gui-RFTH848Yz1A" },
      { role = "HEALER", text = "Big damage: Static Pulse, Knives + Gas, Rapid Extraction, Charged Shot, Drill Smash.", type = "Mechanic", id = "gui-t5uBDpjzhDw" },
      { role = "HEALER", text = "Dispel: Poison (Toxic Blades), Magic (Goo, Compound), Bleeds if possible.", type = "Mechanic", id = "gui-xEma86l9DE0" },
      { role = "DPS", text = "Kick/purge priority trash. Save CDs for Earthrager, Drill Smash, Pummeler burn.", type = "Mechanic", id = "gui-SNzuRe1ZgNA" },
      { role = "DPS", text = "Avoid Peacekeeper pulls — high risk, low count.", type = "Mechanic", id = "gui-UNJWcCLDWE" }
    },
  },
  
  ["Route"] = {
    id = "enc-motherlode-route",
    order = 2,
    header = "Route",
    entries = {
      { role = "ALL", text = "Up to first Mechanized Peacekeeper. Stay RIGHT. Kill Mech Jockeys + Assassins first.", type = "Call", id = "gui-Ii4u2uv2GaY" },
      { role = "ALL", text = "Single pull: Mechanized Peacekeeper next. Watch Tear Gas.", type = "Call", id = "gui-CvVZK591kY" },
      { role = "ALL", text = "After Peacekeeper, going left WITHOUT skips.", type = "Call", id = "gui-DYlRjNBnhA" },
      { role = "ALL", text = "Addled Thug + Mech Jockey + Vendor + Mechanized Peacekeeper. Stop Mech Jockey from mounting.", type = "Call", id = "gui-zB9mGYdBTzw" },
      { role = "ALL", text = "Next pull: Heading straight into Addled Thug + Assassin + Mech Jockey then right into Mech Jockey + Vendor.", type = "Call", id = "gui-2nwTwo0NHE" },
      { role = "ALL", text = "Peacekeeper + Addled Thug + Mech Jockey before Boss.", type = "Call", id = "gui-DDPidI8S86w" },
      { role = "ALL", text = "Heading into Coin-Operated Crowd Pummeler boss room next.", type = "Call", id = "gui-LMiWYPutZ5A" },
      { role = "ALL", text = "Post-Pummeler pull Extractor + Sapper + Rats back here. Then hug right side", type = "Call", id = "gui-kbwLNhyRPgg" },
      { role = "ALL", text = "Big pull: Extractor + Earthshaper + Rats into Earthshaper + Sapper + Rats. *Stay right*.", type = "Call", id = "gui-q2dh129jyng" },
      { role = "ALL", text = "Move up hill. Extractor + 2x Earthshaper + 2x Earthshaper. Go down hill to avoid swirlies", type = "Call", id = "gui-lkc9c3KttvE" },
      { role = "ALL", text = "After these pull 2x Stonefuries + Shale Biters together.", type = "Call", id = "gui-rb5UKLlpfUs" },
      { role = "ALL", text = "Target Taskmaster Askari then pull trash into boss.", type = "Call", id = "gui-PFJtwwzERPI" },
      { role = "ALL", text = "Pulling trash into Azerokk boss.", type = "Call", id = "gui-cde6Zb8OeA" },
      { role = "ALL", text = "After Azerokk, go centre. Be carful - lots around. Alchemist + Mastermind + Test Subject", type = "Call", id = "gui-q1mJFneocPs" },
      { role = "ALL", text = "3x Alchemists. Stay tight, lots around.", type = "Call", id = "gui-A2U3fjJbC8" },
      { role = "ALL", text = "Alchemist + 2x Mastermind + Tester before Rixxa Fluxflame.", type = "Call", id = "gui-qARMtVkCdk" },
      { role = "ALL", text = "Post-Rixxa, Left side War Machine + 2x Specialist pull back to provide space.", type = "Call", id = "gui-tsQBSvA4Tpg" },
      { role = "ALL", text = "Head uphill tight right. War Machine + Specialist. Avoid other War Machine.", type = "Call", id = "gui-uDlrjFbSfn8" },
      { role = "ALL", text = "Stay right to pull Two War Machines then finish to Razdunk.", type = "Call", id = "gui-Wj4XGOYh3RA" }
    },
  },

  ["Coin-Operated Crowd Pummeler"] = {
    id = "enc-motherlode-pummeler",
    order = 3,
    header = "Boss: Coin-Operated Crowd Pummeler",
    entries = {
      { role = "ALL", text = "Foot Bombs Need Clearing — Click and kick toward boss!", type = "Call", id = "gui-SotkAXNd54" },
      { role = "ALL", text = "Interrupt s|Iced Spritzer| and s|Toxic Blades| in trash before pull.", type = "Interrupt", id = "gui-FxR5wuJpb9U" },
      { role = "ALL", text = "Dodge s|Shocking Claw| — random player frontal.", type = "Mechanic", id = "gui-988ENAJF2k" },
      { role = "ALL", text = "Move out of s|Electroshock| Zones after stomp.", type = "Mechanic", id = "gui-HBpl3h83xFc" },
      { role = "TANK", text = "Face boss near wall, rotate slowly as coins spawn.", type = "Position", id = "gui-6qVbN3kakTY" },
      { role = "TANK", text = "During s|Coin Magnet|, pull boss away from gold piles.", type = "Mechanic", id = "gui-fykW0Nd79s" },
      { role = "TANK", text = "Keep boss near center to control stomp zones and bomb kicks.", type = "Position", id = "gui-ZYdiyWYSDA" },
      { role = "TANK", text = "Use CD on Static Pulse — heavy nature hit + DoT.", type = "Mechanic", id = "gui-9JCTCiWyjM8" },
      { role = "TANK", text = "Reposition after each Overcharge to avoid knockbacks into danger.", type = "Mechanic", id = "gui-XB2TFTKCFa4" },
      { role = "TANK", text = "Line up CDs for big damage after first Overcharge cast.", type = "Call", id = "gui-wEUQT1V5fg" },
      { role = "TANK", text = "Use defensive on Pummel if it overlaps with AoE or Overcharge.", type = "Mechanic", id = "gui-c2sqpAYnuw" },
      { role = "HEALER", text = "CDs for Static Pulse — high AoE + knockback.", type = "Call", id = "gui-BxHi8lyThbQ" },
      { role = "HEALER", text = "Spot heal Foot Bomb soakers after detonation.", type = "Mechanic", id = "gui-OkZCZh832Lc" },
      { role = "DPS", text = "Click Foot Bombs and kick toward boss quickly.", type = "Mechanic", id = "gui-fqe1r8ZwWvs" }
    },
  },  

  ["Azerokk"] = {
    id = "enc-motherlode-azerokk",
    order = 4,
    header = "Boss: Azerokk",
    entries = {
      { role = "ALL", text = "Burn empowered n|Earthrager| before Resonant Quake or wipe to Aftershock.", type = "Call", id = "gui-CEMElIBVTms" },
      { role = "ALL", text = "Unempowered n|Earthragers| fixate — slow, knock, CC to delay them.", type = "Mechanic", id = "gui-OjnIPgfu4JQ" },
      { role = "ALL", text = "Frontal: Sidestep Tectonic Smash.", type = "Call", id = "gui-sRouWrM288" },
      { role = "ALL", text = "Interrupt Rock Lance, Furious Quake, and n|Earthrager| barriers.", type = "Interrupt", id = "gui-tGyUybwWQt8" },
      { role = "ALL", text = "Use Fracking Totems to CC an n|Earthrager| for 60s — pull boss away from it.", type = "Mechanic", id = "gui-4DYErXvra8M" },
      { role = "TANK", text = "Pick up empowered n|Earthrager| immediately — tankable and high dmg.", type = "Mechanic", id = "gui-OAb2NhR0PeM" },
      { role = "TANK", text = "Kite boss to edge before Resonant Quake — drop safe zones.", type = "Position", id = "gui-EfYl4IYzwyw" },
      { role = "TANK", text = "Pull adds near boss for cleave. Interrupt priority = Earthrager.", type = "Call", id = "gui-GYOYji6W6EU" },
      { role = "TANK", text = "Grab aggro fast — missed adds = heavy party damage.", type = "Mechanic", id = "gui-rCXgUetZWII" },
      { role = "TANK", text = "Drag boss away from any CC’d n|Earthrager| to prevent breaking it.", type = "Mechanic", id = "gui-CQHGvKcSmhw" },
      { role = "TANK", text = "Reposition out of Quake zones quickly — don’t linger.", type = "Mechanic", id = "gui-2bd0z7REOSY" },
      { role = "HEALER", text = "CDs for Resonant Quake + empowered n|Earthrager| pulses.", type = "Call", id = "gui-rUXSDa3ze8" },
      { role = "HEALER", text = "Top fixate targets fast — bleed stacks hurt.", type = "Mechanic", id = "gui-OupPlCRtn8" },
      { role = "DPS", text = "Burn infused n|Earthrager| before Quake or wipe.", type = "Mechanic", id = "gui-TPd4j2bopw" },
      { role = "DPS", text = "Stun/knock/root unempowered Earthragers to delay fixates.", type = "Mechanic", id = "gui-x9vr0FQDC2s" }
    },
  },
  
  ["Rixxa Fluxflame"] = {
    id = "enc-motherlode-rixxa",
    order = 5,
    header = "Boss: Rixxa Fluxflame",
    entries = {
      { role = "ALL", text = "Propellant Blast on me — aiming to clear puddles.", type = "Call", id = "gui-c9HJ1PNbGdE" },
      { role = "ALL", text = "Catalyst on me — dropping pool near edge.", type = "Call", id = "gui-8y856ktUNxY" },
      { role = "ALL", text = "Interrupt Transmute: Goo and Caustic Compound.", type = "Interrupt", id = "gui-NmtJDucKAq8" },
      { role = "TANK", text = "Stay in melee — boss uses magic only, not autos.", type = "Mechanic", id = "gui-Hl3P3gsHNk" },
      { role = "TANK", text = "Face boss away from group. Avoid dragging puddles into others.", type = "Position", id = "gui-oDLPTqkriYM" },
      { role = "TANK", text = "Reposition boss after Blast to free up safe ground.", type = "Position", id = "gui-2Bjni0ExFE" },
      { role = "TANK", text = "Fixate on me — I’ll kite toward outer edge.", type = "Call", id = "gui-UtWCnS6YLY" },
      { role = "TANK", text = "Walk forward during Fixate — don’t backpedal into Gush.", type = "Mechanic", id = "gui-ctWSxHmE3JU" },
      { role = "TANK", text = "Use defensive on Guzzle/Gush overlap — group splash hits hard.", type = "Mechanic", id = "gui-g9s1DtCV1g" },
      { role = "HEALER", text = "Dispel poison and magic DoTs on trash.", type = "Mechanic", id = "gui-AVf6mq1tSw0" },
      { role = "HEALER", text = "CDs if Propellant Blast overlaps with Catalyst or Fixate.", type = "Call", id = "gui-2ssNcTJGmw" },
      { role = "DPS", text = "Blast thick puddles — aim carefully.", type = "Mechanic", id = "gui-aNCAWGdR1y4" },
      { role = "DPS", text = "Drop Catalyst near existing pools — avoid clutter.", type = "Mechanic", id = "gui-gyCeUWYeG8g" }
    },
  },
  
  ["Mogul Razdunk"] = {
    id = "enc-motherlode-razdunk",
    order = 6,
    header = "Boss: Mogul Razdunk",
    entries = {
      { role = "ALL", text = "Homing Missile on me — running out, using defensive.", type = "Call", id = "gui-TKxXTvzkeU" },
      { role = "ALL", text = "Gatling Gun — watch spin direction and reposition fast.", type = "Call", id = "gui-QSvRGWTZHrM" },
      { role = "ALL", text = "Missile Bots glow before firing. Stack in safe zone ahead of time.", type = "Mechanic", id = "gui-GvzOVUPEA0" },
      { role = "ALL", text = "Interrupt Buster Shot from Skyscorchers in Phase 2.", type = "Interrupt", id = "gui-fx43gTWMeU" },
      { role = "TANK", text = "Face Gatling Gun away. Reposition during drone waves.", type = "Position", id = "gui-3Zt6Gh7UPg" },
      { role = "TANK", text = "Razdunk deals fire magic — use magic mitigation, not physical CDs.", type = "Mechanic", id = "gui-DaJWGXluzC4" },
      { role = "TANK", text = "Start pull at front-left. Rotate with drills clockwise.", type = "Call", id = "gui-ANdj9QKlU0" },
      { role = "TANK", text = "Tank near edge but avoid Drill Smash walls — trap risk.", type = "Mechanic", id = "gui-PlzERKs0D8" },
      { role = "TANK", text = "Mitigate overlap: Machine Gun + Drill + Bomb Bots.", type = "Mechanic", id = "gui-Cz3VjFnkgk" },
      { role = "TANK", text = "Pick up Skyscorchers quickly — prevent fire spam.", type = "Mechanic", id = "gui-3b8Zo7wwwU" },
      { role = "TANK", text = "Pull bomb bots in and stun. Keep boss mid for control.", type = "Position", id = "gui-XXPoXcAPoB8" },
      { role = "HEALER", text = "CDs for Drill Smash + Buster Shot overlap.", type = "Call", id = "gui-0k4eSTkgPMY" },
      { role = "HEALER", text = "Top Homing Missile target or cleanse DoT.", type = "Mechanic", id = "gui-zP2UXMqOHUs" },
      { role = "DPS", text = "Burn Skyscorchers — reduce fire spam Phase 2.", type = "Mechanic", id = "gui-lT8aKejdWd4" },
      { role = "DPS", text = "Stand on rocket during Drill Smash to clear stacks.", type = "Mechanic", id = "gui-CVc8pND6A" }
    },
  }  
}
