DungeonGuide_Guides["The Rookery"] = {
  id = "dung-rookery",
  season = "TWW-S2",
  guideType = "M+",
  ["The Rookery"] = {
    id = "enc-rookery-guide",
    order = 1,
    header = "Intro",
    entries = {
      { order = 1, role = "ALL", text = "Interrupts: Lightning Bolt (Thunderers), Lightning Surge (Rooktenders), Void Bolt (Oracles/Ascendants).", type = "Interrupt", id = "gui-jACtGQKZI" },
      { order = 2, role = "ALL", text = "Stormrooks cast Energized Barrage - spread + dodge swirlies.", type = "Mechanic", id = "gui-OHdznq0AmbY" },
      { order = 3, role = "ALL", text = "Void Diffusers: Interrupt Attracting Shadows, avoid Arcing Void cleave.", type = "Mechanic", id = "gui-oc2UNftmcDk" },
      { order = 4, role = "ALL", text = "Gorren: Pass Chaotic Corruption debuff, place Crush puddles at edges.", type = "Mechanic", id = "gui-eyRR3zJeu5Q" },
      { order = 5, role = "ALL", text = "Monstrosity: Burn at 80% - 20s stun + 100% dmg taken. Line up CDs.", type = "Mechanic", id = "gui-YZTbIKVhGFs" },
      { order = 6, role = "ALL", text = "Assign players to shatter Voidstone Fragments with Stormrider's Charge after Upheaval.", type = "Mechanic", id = "gui-Eog56kRtif4" },
      { order = 7, role = "TANK", text = "Void Claw (Crushers) reduces healing. Kite to reset.", type = "Mechanic", id = "gui-UdrQPzHDC64" },
      { order = 8, role = "TANK", text = "Face Oblivion Wave away (Monstrosity). Stay in melee - prevent Entropy casts.", type = "Mechanic", id = "gui-O6dkB0GBW4" },
      { order = 9, role = "TANK", text = "Keep mobs out of Entropy fields and AoE puddles when possible.", type = "Mechanic", id = "gui-0XEMYdlfOI" },
      { order = 10, role = "HEALER", text = "Big healing: Lightning Torrent (Kyrioss), Arcing Void, Unleash Darkness, Upheaval.", type = "Mechanic", id = "gui-kuf4hO9pPJg" },
      { order = 11, role = "HEALER", text = "Dispel: Chaotic Corruption (Gorren), Seeping Corruption (Oracles), Feasting Void (Ascendants), Unleash Corruption (Monstrosity).", type = "Mechanic", id = "gui-0273WTlIiE" },
      { order = 12, role = "DPS", text = "Kill priority: Void Diffusers, Stormrooks, Ascendants.", type = "Mechanic", id = "gui-PcHTIgE7Os" },
      { order = 13, role = "DPS", text = "Use movement buffs to rotate during beam phase.", type = "Mechanic", id = "gui-n9frkwintA" },
      { order = 14, role = "DPS", text = "Assign shard duty: 1 per platform. Pop Charge after Upheaval swirls clear.", type = "Call", id = "gui-XhH8hYKjB4U" }
    },
  },

  ["Route"] = {
    id = "enc-rookery-route",
    order = 2,
    header = "Route",
    entries = {
      { order = 1, role = "ALL", text = "Pull Quartermaster Corti + right-side guards for extra count.", type = "Call", id = "gui-KsZDSRTIow" },
      { order = 2, role = "ALL", text = "Focus Corti quickly. Watch Bounding Void frontal.", type = "Mechanic", id = "gui-5CnFPSceC4" },
      { order = 3, role = "ALL", text = "Move into Storm's Roost: right side first, grab patrol + adjacent pack.", type = "Call", id = "gui-vnjfOAC0nw" },
      { order = 4, role = "ALL", text = "Kick Cursed Thunderers. Watch Storm Rook unavoidable group damage.", type = "Mechanic", id = "gui-1UTBeFhEmSI" },
      { order = 5, role = "ALL", text = "Clear around Storm's Roost room one pack at a time.", type = "Call", id = "gui-Qgl0kn3APYM" },
      { order = 6, role = "ALL", text = "Optional: Skip triple-caster pack if group coordination is low.", type = "Mechanic", id = "gui-RMcy8ta5rCE" },
      { order = 7, role = "ALL", text = "Boss Fight: Kyrioss", type = "Jump", target="Kyrioss", id = "gui-X4zJcBEyngc" },
      { order = 8, role = "ALL", text = "After boss, pull patrol + adjacent pack downstairs.", type = "Call", id = "gui-EPpkidq44fw" },
      { order = 9, role = "ALL", text = "Ignore corner pack after boss. Not needed for count.", type = "Call", id = "gui-yJdatMZ6tzM" },
      { order = 10, role = "ALL", text = "One pack at a time after patrol. Respect Attracting Shadows damage.", type = "Mechanic", id = "gui-xSH2xTeRc8" },
      { order = 11, role = "ALL", text = "Walk past sleeping Void Crushers safely. Short aggro radius.", type = "Call", id = "gui-RJen33yyZ8U" },
      { order = 12, role = "ALL", text = "Next key pull: double Void Diffuser pack. Focus one fast.", type = "Call", id = "gui-eQS76l50FgM" },
      { order = 13, role = "ALL", text = "Leading into Gorak Goran: pull 8 trash onto boss.", type = "Call", id = "gui-aevbSI8g3VE" },
      { order = 14, role = "ALL", text = "Boss Fight: Stormguard Gorren", type = "Jump", target="Stormguard Gorren", id = "gui-fiAVSYvJuN0" },
      { order = 15, role = "ALL", text = "After Gorak Goran, pull two Crushers + Void Ascendant together.", type = "Call", id = "gui-BhKTWA8rNdM" },
      { order = 16, role = "ALL", text = "Ascendant orb projectiles: melee position carefully.", type = "Mechanic", id = "gui-XzQHeKe3Z2c" },
      { order = 17, role = "ALL", text = "Head downstairs. Mass pull Afflicted Civilians for cleave.", type = "Call", id = "gui-LEEshVyusRc" },
      { order = 18, role = "ALL", text = "Skip Crushers in lower section if safe on count.", type = "Mechanic", id = "gui-G1tDdQ6DWA0" },
      { order = 19, role = "ALL", text = "Pull Radiating Voidstone solo. Avoid damage debuff stacking.", type = "Call", id = "gui-afBdIaIc5c0" },
      { order = 20, role = "ALL", text = "Kill 3 Void Ascendants to spawn final boss.", type = "Call", id = "gui-bx8BYL4wWg" },
      { order = 21, role = "ALL", text = "Pull Crushers + Voidstone if short on count at end.", type = "Call", id = "gui-QoQqFgxTGc" },
      { order = 22, role = "ALL", text = "Boss Fight: Voidstone Monstrosity", type = "Jump", target="Voidstone Monstrosity", id = "gui-9RGtYJ9Gfqo" }
    },
  },
    
  ["Kyrioss"] = {
    id = "enc-rookery-kyrioss",
    order = 3,
    header = "Boss: Kyrioss",
    entries = {
      { order = 1, role = "ALL", text = "Crashing Thunder - spread 8yds. Use minor defensives.", type = "Call", id = "gui-vISN8oa9X9M" },
      { order = 2, role = "ALL", text = "Wild Lightning - stack in melee after Thunder to control line spawns.", type = "Mechanic", id = "gui-q1woDK8Vs" },
      { order = 3, role = "ALL", text = "Lightning Torrent phase - group near grates, rotate as a unit.", type = "Call", id = "gui-BjdCHJr9F6E" },
      { order = 4, role = "ALL", text = "Watch for Grounding Bolts - circles drop under each player.", type = "Mechanic", id = "gui-oYR6OvMfUhE" },
      { order = 5, role = "ALL", text = "Avoid Lightning Dash at phase end - 12yd AoE on random player.", type = "Mechanic", id = "gui-jSqUXMZK8o" },
      { order = 6, role = "TANK", text = "Face boss away during melee phase. Maintain safe space.", type = "Position", id = "gui-PyKv7b2c6lc" },
      { order = 7, role = "TANK", text = "Hold boss near mid for phase transition positioning.", type = "Position", id = "gui-iieV2nXuvw" },
      { order = 8, role = "HEALER", text = "CDs for Lightning Torrent - heavy ticking AoE + ground effects.", type = "Call", id = "gui-IUGxteikpw" },
      { order = 9, role = "HEALER", text = "Top group after Crashing Thunder and Dash phase.", type = "Mechanic", id = "gui-jJMvdk3aTc8" },
      { order = 10, role = "DPS", text = "Stack after Thunder to align Wild Lightning paths.", type = "Mechanic", id = "gui-M9LEw6i1nzE" },
      { order = 11, role = "DPS", text = "Dodge into safe space during Lightning Torrent beams.", type = "Mechanic", id = "gui-S3puXGEBfNw" }
    },
  },
  
  ["Stormguard Gorren"] = {
    id = "enc-rookery-stormguard-gorren",
    order = 4,
    header = "Boss: Stormguard Gorren",
    entries = {
      { order = 1, role = "ALL", text = "Crush Reality targeting soon - move to edge to soak. Avoid beam lines.", type = "Call", id = "gui-P6uxsPqzckI" },
      { order = 2, role = "ALL", text = "Corruption DoT on me. Passing to tank, then safe player.", type = "Call", id = "gui-3476UGN3M4" },
      { order = 3, role = "ALL", text = "Spread ranged around edges to control Crush placement.", type = "Mechanic", id = "gui-hmkA5rEigiU" },
      { order = 4, role = "ALL", text = "Run from boss during Dark Gravity - 10yd explosion radius.", type = "Mechanic", id = "gui-zDwFLgN5BBM" },
      { order = 5, role = "ALL", text = "Interrupt Void Bolt from Corrupted Oracles.", type = "Interrupt", id = "gui-RJx83fKVoE8" },
      { order = 6, role = "TANK", text = "Soak 2nd Corruption stack if needed - use defensive for Vulnerability hit.", type = "Mechanic", id = "gui-ZJ0kaTriiqM" },
      { order = 7, role = "TANK", text = "Face away before Crush leap - prevent beam cleave on group.", type = "Position", id = "gui-2mw1V17GI9s" },
      { order = 8, role = "TANK", text = "Help soak puddles at edge. Rotate position post-leap.", type = "Position", id = "gui-UpLyTvzUk" },
      { order = 9, role = "HEALER", text = "CDs for Dark Gravity + Crush overlap - high spike.", type = "Call", id = "gui-8N5H8H3J5C4" },
      { order = 10, role = "HEALER", text = "Top players holding Corruption - especially if soaking Crush too.", type = "Mechanic", id = "gui-PRPRSdjZfQI" },
      { order = 11, role = "HEALER", text = "Dispel Seeping Corruption (curse) if players don't have CDs.", type = "Mechanic", id = "gui-9ElFhlGqh3Y" },
      { order = 12, role = "DPS", text = "Help pass Corruption debuff safely - avoid bouncing to same player twice.", type = "Mechanic", id = "gui-qTi6eWhQ1Ao" },
      { order = 13, role = "DPS", text = "Dodge beam lines after Crush. Save space near edges.", type = "Mechanic", id = "gui-jBxE8cuPBEo" },
      { order = 14, role = "DPS", text = "Hold CDs for clean post-jump phase when safe.", type = "Call", id = "gui-YINS4uKh0ps" }
    },
  },
 
  ["Voidstone Monstrosity"] = {
    id = "enc-rookery-voidstone-monstrosity",
    order = 5,
    header = "Boss: Voidstone Monstrosity",
    entries = {
      { order = 1, role = "ALL", text = "Null Upheaval soon - spread, pop defensive, dodge swirlies.", type = "Call", id = "gui-tzLscDZxxk" },
      { order = 2, role = "ALL", text = "Void Shell breaks at 80% - burn phase with 100% damage amp.", type = "Call", id = "gui-RNOHujHBYFs" },
      { order = 3, role = "ALL", text = "Stormrider's Charge on me - running to my shard.", type = "Call", id = "gui-4Etd7GicpQs" },
      { order = 4, role = "ALL", text = "Stand clear of Oblivion Wave frontal - wide line AoE.", type = "Mechanic", id = "gui-PcHYdtFKab4" },
      { order = 5, role = "ALL", text = "Destroy all 3 Voidstone Fragments within 15s or adds spawn.", type = "Mechanic", id = "gui-DkWKe204dLs" },
      { order = 6, role = "TANK", text = "Never leave melee. Entropy wipe if boss idle.", type = "Mechanic", id = "gui-0eU2ID1AB7U" },
      { order = 7, role = "TANK", text = "Face boss away for Oblivion Wave. Never leave melee or boss spams Entropy.", type = "Mechanic", id = "gui-To4GlTNTeN0" },
      { order = 8, role = "TANK", text = "Major CD on Oblivion Wave - heavy shadow damage to all in line.", type = "Mechanic", id = "gui-RJH0EHm0Sxw" },
      { order = 9, role = "TANK", text = "Reposition boss slightly each cycle to control puddle zones.", type = "Position", id = "gui-txaU9fwusZw" },
      { order = 10, role = "HEALER", text = "CDs for Null Upheaval + Unleash Darkness overlap.", type = "Call", id = "gui-1t5DfIoUEbU" },
      { order = 11, role = "HEALER", text = "Dispel Unleash Corruption quickly - position player to avoid melee puddles.", type = "Mechanic", id = "gui-EOZrxHGA8ws" },
      { order = 12, role = "HEALER", text = "Float between shard platforms if a runner fails.", type = "Mechanic", id = "gui-PhRDSuJDJMQ" },
      { order = 13, role = "DPS", text = "Hold CDs for Storm's Vengeance burn phase (20s window).", type = "Call", id = "gui-UwCVB7xx8Eg" },
      { order = 14, role = "DPS", text = "Assigned shard runner - wait for swirlies, then charge platform.", type = "Mechanic", id = "gui-JNphiCesux4" },
      { order = 15, role = "DPS", text = "Destroy Fragments fast - avoid add spawns from Corruption Overload.", type = "Mechanic", id = "gui-kIuDGPRti5k" }
    },
  }
}
